### ISSUE TITLE
miui 13.0.8 global+magisk - controls- navbar-left\right button functions are not working

### ISSUE THREAD

**Issue by allyalla** [MonwF/customiuizer#10]
Custom buttons on navbar were working awesome on miui 12.5. But on miui 13.0.6 and 13.0.8 this mod is not functioning.

**Comment by MonwF** [comment]
get version v220805 and feedback

**Comment by allyalla** [comment]
At the bottom line - it is working now. Both additional buttons are displayed as dots and functions are working as intended. But personally I was able to get it working ONLY after uninstallation and then fresh installation via mine alternative android package installer. 
And small non critical new isue left with navbar, navbar in landscape screen is staying in vertical state anyways, so if we reeding from left to right turning the phone vertically, now the right button is at place of the left one and vice versa.
Thanks a lot for maintaing this candy, in the world of monkey people and increasing dumbness and stupidity, it help to keep your own device personalized according your OWN needs.

**Comment by allyalla** [comment]
By the way , another small thing - open volume dialog function does nothing, while rise vol one for instance do opening that volume dialog overlay.

**Comment by MonwF** [comment]
> 

i will work on opening vol dialog.
navbar buttons on the right side of landscape screen are placed wrongly

**Comment by MonwF** [comment]
> By the way , another small thing - open volume dialog function does nothing, while rise vol one for instance do opening that volume dialog overlay.

1. open volume dialog fixed
2. navbuttons need to repositon on landscape screen. i've decided not to fix it because this is a rare scene
