### ISSUE TITLE
[Bug] Extra navbar buttons swap sides on screen rotation (portrait←→landscape)

### ISSUE THREAD

**Issue by Henri-J-Norden** [MonwF/customiuizer#104]
Hi and thanks for the great work!

Section: Controls → Navigation bar → Left/Right button actions
As the title says, I would expect the right navbar button to stay next to the back button when changing to landscape orientation, but instead its actions now seem to be swapped with the left button.

**Comment by Henri-J-Norden** [comment]
If this is the intended behaviour, there should be a toggle to enable/disable swapping in landscape mode, because this is very unintuitive to me. I always press the wrong one in landscape...

**Comment by MonwF** [comment]
it's a known bug. i don't fix it as few people care about up or down in landscape mode. may be i will fix it later

**Comment by MonwF** [comment]
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/10379097/app-release.apk.zip)
