### ISSUE TITLE
Add a function in lock screen menu 

### ISSUE THREAD

**Issue by masshuvo** [MonwF/customiuizer#105]
Status bar, calendar, lock screen open hidden when our phone is locked, but here we need to add one more function.For example, if the phone is locked, clicking the volume button will not work. Because if someone can control the volume button while the phone is locked, then the mobile can be silenced. So I think this function needed to be added after locking the phone the volume button won't work After unlocking the phone, it will work

**Comment by MonwF** [comment]
a rare case. not planned
