### ISSUE TITLE
[Bug] Network speed mods

### ISSUE THREAD

**Issue by erfirya** [MonwF/customiuizer#107]
when I try to enter the network speed mods setting, the app force closes, and the indicators are way too big.
![Screenshot_2023-01-06-20-20-25-681_com teslacoilsw launcher](https://user-images.githubusercontent.com/71990871/211012716-dc52f2a0-b8da-4d69-a6f9-b11183729969.jpg)
![Screenshot_2023-01-06-20-20-12-752_com teslacoilsw launcher](https://user-images.githubusercontent.com/71990871/211012729-c0a14e4f-84d1-4c6f-9d0d-77c52b900d10.jpg)
![Screenshot_2023-01-06-20-20-00-693_name monwf customiuizer](https://user-images.githubusercontent.com/71990871/211012737-b6ce2779-c471-4477-a0bf-f9bcc41f38b9.jpg)
this happened after the latest update.

**Comment by MonwF** [comment]
sorry, i will fix it soon

**Comment by MonwF** [comment]
redownload the apk from  https://github.com/MonwF/customiuizer/releases/tag/v23.01.06

**Comment by erfirya** [comment]
I can now go to the settings just fine, but it's font size is still way too big. thank you
![Screenshot_2023-01-06-21-38-55-605_name monwf customiuizer](https://user-images.githubusercontent.com/71990871/211023826-36b392d2-ed71-42f2-aaac-cba4c33962a8.jpg)
![Screenshot_2023-01-06-21-39-21-131_com teslacoilsw launcher](https://user-images.githubusercontent.com/71990871/211023838-7f3ff427-ef61-4143-9e4a-11a8e02a6bf3.jpg)

**Comment by MonwF** [comment]
you can change the font size to 8dip. when turn on the dual row, the font size will change auto. but not for exist setting

**Comment by erfirya** [comment]
ohh didn't know that sorry. it's back to normal now thank you
