### ISSUE TITLE
更新MIUI 14 V14.0.23.1.3.DEV开发版后截图设置成png或webp截图无法预览

### ISSUE THREAD

**Issue by XY50** [MonwF/customiuizer#108]
23.1.6版本，截图格式设置成png或webp后无法预览和保存截图

**Comment by MonwF** [comment]
这块功能很久没动过了，之前版本可用吗

**Comment by MonwF** [comment]
我这边试了下png没问题

**Comment by XY50** [comment]
上个版本可以用

**Comment by XY50** [comment]
https://user-images.githubusercontent.com/121076219/211041820-8a5572e7-9aee-42b9-8309-a221886da56d.mp4

**Comment by MonwF** [comment]
系统应用管理里搜索截图，看下版本号呢？今天有没更14的开发版

**Comment by XY50** [comment]
应该是更新了系统的原因，我刚才退回了旧本也没法保存png的截图了，截图版本号RELEASE-1.4.34-12151541

**Comment by XY50** [comment]
我今天更新了miui14最新的开发版

**Comment by WakiJi** [comment]
更新了最新的MIUI14开发版 MUNCH_V14.0.23.1.3.DEV
截图保存PNG也不可用
截图之后，相册里面找不到

**Comment by MonwF** [comment]
直接用1.5.9的截屏apk吧，1.4.34加了些代码，好像1.5.9又去掉了。现在修了，到时可能又挂掉
