### ISSUE TITLE
Rotation Suggestion with Hide fullscreen indicator

### ISSUE THREAD

**Issue by 3zozHashim** [MonwF/customiuizer#109]
Normally the rotation suggestion only works with navigation bar and with full screen gestures (with pill) but it doesnt work with the hidden pill option "Hide fullscreen indicator"

It would be great if it was possible to make it work with hidden fullscreen indicator

**Rotation Suggestion with Navigation bar**
![IMG_20230108_175501](https://user-images.githubusercontent.com/115328790/211206347-d04c513d-d280-49a2-8871-b343015ff9c9.png)

**Rotation Suggestion with Full Screen Gestures (with pill)**
![IMG_20230108_175518](https://user-images.githubusercontent.com/115328790/211206383-0734d1d2-8c23-47f5-b2d3-804b53ffa57d.png)

**Full Screen Gestures with "Hide fullscreen indicator"**
![IMG_20230108_175446](https://user-images.githubusercontent.com/115328790/211206427-91cabd90-61f1-4393-b8b8-c2461de9fca7.png)

**Comment by 3zozHashim** [comment]
> how to trigger the indicator display? i saw it few times

by rotating the phone landscape (using locked orientation)

**Comment by MonwF** [comment]
sorry. no navigationbar would be created if you hide gesture line.
