### ISSUE TITLE
The issue of non-support for MIUI 13 based on Android 11

### ISSUE THREAD

**Issue by glanheit** [MonwF/customiuizer#11]
Some devices, such as the Redmi Note 11 Pro 5G, run MIUI13 based on Android 11.

I set up the sdk in my environment based on previous comments at issues and rewrote some of the versions and installed.
However, the app could not run properly although it could be opened.

Can you make it support miui13 in a larger frame?

**Comment by MonwF** [comment]
sorry. i don't have an phone with android 11

**Comment by glanheit** [comment]
All right. Unfortunately, I will wait until the Android 12 based update comes down.
Thank you.

**Comment by MonwF** [comment]
> All right. Unfortunately, I will wait until the Android 12 based update comes down. Thank you.

try version before v0803
