### ISSUE TITLE
Secure Quick Settings

### ISSUE THREAD

**Issue by Parylo-D** [MonwF/customiuizer#113]
Don't work Secure Quick Settings in lockscreen in Android 13 MIUI 14.

**Comment by MonwF** [comment]
[app-release.zip](https://github.com/MonwF/customiuizer/files/10389705/app-release.zip)

**Comment by Parylo-D** [comment]
> [app-release.zip](https://github.com/MonwF/customiuizer/files/10389705/app-release.zip)
> 

Thank you. All working now:)
