### ISSUE TITLE
Extended power menu

### ISSUE THREAD

**Issue by kirill8618** [MonwF/customiuizer#12]
Restart System UI and Restart Launcher not showing in Extended power menu.

**Comment by MonwF** [comment]
you should restart system

**Comment by kirill8618** [comment]
l restart system

**Comment by kirill8618** [comment]
[ 2022-08-10T15:27:24.911     1000:  2220:  2220 I/LSPosed-Bridge  ] [CustoMIUIzer][EnhancedSecurityHook] Failed to hook powerLongPress method in com.android.server.policy.PhoneWindowManager
[ 2022-08-10T15:27:33.168     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][NoSOSHook] Failed to hook updateEmergencyCallButton method in com.android.keyguard.EmergencyButton
[ 2022-08-10T15:27:33.177     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][ExtendedPowerMenuHook] Failed to hook getExtendedPowerMenuEnabled method in com.miui.systemui.SettingsManager
[ 2022-08-10T15:27:33.180     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][SecureControlCenterHook] Failed to hook updateKeyguardState method in com.android.systemui.statusbar.phone.StatusBar
[ 2022-08-10T15:27:33.181     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][SecureControlCenterHook] Failed to hook panelEnabled method in com.android.systemui.miui.statusbar.ControlCenter
]
[ 2022-08-10T15:27:36.095     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][after] Failed to hook handleClick method in com.android.systemui.qs.tiles.MiuiCellularTile
[ 2022-08-10T15:27:36.097     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][after] Failed to hook handleClick method in com.android.systemui.qs.tiles.MiuiBluetoothTile
[ 2022-08-10T15:27:36.101     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][after] Failed to hook handleClick method in com.android.systemui.qs.tiles.MiuiWifiTile
[ 2022-08-10T15:27:36.117     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][after] Failed to hook handleClick method in com.android.systemui.qs.external.CustomTile
[ 2022-08-10T15:27:36.121     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][after] Failed to hook handleClick method in com.android.systemui.qs.tiles.MiuiHotspotTile
[ 2022-08-10T15:27:36.125     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][after] Failed to hook handleClick method in com.android.systemui.qs.tiles.MiuiLocationTile
[ 2022-08-10T15:27:36.127     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][after] Failed to hook handleClick method in com.android.systemui.qs.tiles.MiuiAirplaneModeTile
[ 2022-08-10T15:27:36.230     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][after] Failed to hook handleClick method in com.android.systemui.qs.tiles.MiuiNfcTile
[ 2022-08-10T15:27:36.232     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][after] Failed to hook handleClick method in com.android.systemui.qs.tiles.EditTile
[ 2022-08-10T15:27:36.884     1000:  2870:  2870 I/LSPosed-Bridge  ] [CustoMIUIzer][after] Failed to hook handleClick method in com.android.systemui.qs.tiles.SyncTile

**Comment by MonwF** [comment]
without any info. only god helps

**Comment by MonwF** [comment]
android and miui version, cn or eu

**Comment by kirill8618** [comment]
Android 12 miui 13.0.2 global (SKSMIXM)

**Comment by MonwF** [comment]
> Android 12 miui 13.0.2 global (SKSMIXM)

test with v08.11

**Comment by kirill8618** [comment]
> > Android 12 miui 13.0.2 global (SKSMIXM)
> 
> test with v08.11

v08.11 Not working (Restart System UI and Restart Launcher not showing)

**Comment by kirill8618** [comment]
![Screenshot_2022-08-11-07-14-56-098_com android chrome](https://user-images.githubusercontent.com/110995156/184063946-84b5e96f-1b21-4fa7-b671-3795073d4639.jpg)

**Comment by MonwF** [comment]
> > > Android 12 miui 13.0.2 global (SKSMIXM)
> > 
> > 
> > test with v08.11
> 
> v08.11 Not working (Restart System UI and Restart Launcher not showing)

sorry, i was not reading your issue carefully. 
the two actions have been moved, and now you can trigger it via actionbar menu action

**Comment by MonwF** [comment]
by the way, hide the controlcenter on the lockscren is working now
