### ISSUE TITLE
[Request] please add option to force qs clock follow system font 

### ISSUE THREAD

**Issue by hsx02** [MonwF/customiuizer#122]
![Screenshot_2023-01-15-00-23-51-504_org bromite bromite](https://user-images.githubusercontent.com/72127977/212522334-9833ebf4-2160-4d3f-b8ea-5fb25b99187e.jpg)
![Screenshot_2023-01-15-00-23-46-075_com android settings](https://user-images.githubusercontent.com/72127977/212522336-63650f5e-f2d9-4a18-a3d7-4469f730d48d.jpg)
![Screenshot_2023-01-15-09-31-20-387_com android settings](https://user-images.githubusercontent.com/72127977/212522339-03ff1da9-a876-4200-b1f3-3a435d4931b2.jpg)

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/10419768/app.zip)

**Comment by hsx02** [comment]
Thanks working!!!!
