### ISSUE TITLE
A12 Statusbar

### ISSUE THREAD

**Issue by 3zozHashim** [MonwF/customiuizer#123]
It would be splendid, if there was an option to remove these A12 statusbar notifications

![Screenshot_2023-01-15-22-09-59-632_com mi android globallauncher](https://user-images.githubusercontent.com/115328790/212564496-91c6b266-3411-4f61-b2e0-8eb9c3cf4466.png)
![Screenshot_2023-01-15-22-09-49-189_com android soundrecorder](https://user-images.githubusercontent.com/115328790/212564515-23bd323e-db41-4f9a-86e1-9167a8aa3269.png)
![Screenshot_2023-01-15-22-09-06-682_com mi android globallauncher](https://user-images.githubusercontent.com/115328790/212564541-1aa4365d-5958-4bee-b48e-93055da5b734.png)
![Screenshot_2023-01-15-22-07-26-279_com mi android globallauncher](https://user-images.githubusercontent.com/115328790/212564558-7914b2c9-53fa-436b-a0d2-662466ef40de.png)

**Comment by MonwF** [comment]
call indicator should  not be hidden. others like camera can be turned off in system settings
