### ISSUE TITLE
红米note11 t pro安卓12上无效

### ISSUE THREAD

**Issue by XiaoDongOwO** [MonwF/customiuizer#126]
![Screenshot_2023-01-16-22-49-59-667_com android settings](https://user-images.githubusercontent.com/72956296/212706176-3787ff85-73d5-4337-ab59-4010c8f20dd3.png)
出厂版本，设置充电时不点亮屏幕无效。

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/10453825/app.zip)
