### ISSUE TITLE
Low and midrange device have a lag issue while opening qs and control centre, it can be fixed by manually selecting bg for qs.

### ISSUE THREAD

**Issue by hsx02** [MonwF/customiuizer#132]
![Screenshot_2023-01-20-08-23-39-218_com android settings](https://user-images.githubusercontent.com/72127977/213608345-9f99758a-c2ab-486b-b772-0e9fbe43b3fd.jpg)
![Screenshot_2023-01-20-08-23-32-710_com android settings](https://user-images.githubusercontent.com/72127977/213608378-c00f60be-25dd-4106-aaac-8374dcb08e1a.jpg)
![Screenshot_2023-01-20-08-23-20-463_com android settings](https://user-images.githubusercontent.com/72127977/213608387-a8463fbf-20cf-43d0-8d22-997736905ac6.jpg)

**Comment by MonwF** [comment]
no idea
