### ISSUE TITLE
seconds in the clock on the taskbar do not work

### ISSUE THREAD

**Issue by Bladius2022** [MonwF/customiuizer#135]
in the latest version, the seconds in the clock on the taskbar do not work. They appear after uploading an older version and after updating back to the latest, but they disappear after restarting the device. MIUI 13.0.11.0

**Comment by guillermorojaz** [comment]
The seconds are not updated in the Custom format section. Try all possible formats. hh:mm:ss h:m:s

I add;
Get them updated by installing the Chimi module, which has the option Clock refresh interval 1 sec.

**Comment by MonwF** [comment]
breaking change. you should config clock again

**Comment by guillermorojaz** [comment]
excuse me was the translator. I have tried several formats and it does not update the seconds. 
HH:mm:ss  
h:m:s
h:mm:ss

**Comment by MonwF** [comment]
it doesn't work even if custom format set to HH:mm:ss?

**Comment by Bladius2022** [comment]
I didn't change the time format, I have hh:mm:ss set by default.  I don't even know how to change to custom.  The Chimi module has been removed from GitHub and there is no way to download it, it is also difficult to find due to the Chinese name of the package.  Since it worked in the previous version and works after the update until the device is restarted, then corrections would have to be made.

**Comment by Bladius2022** [comment]
in the version from 21.1.2023 still do not work.  There are only those after expanding the notification bar, but not the clock on the taskbar.

**Comment by MonwF** [comment]
> in the version from 21.1.2023 still do not work. There are only those after expanding the notification bar, but not the clock on the taskbar.

what's your settings? provide screenshot

**Comment by Bladius2022** [comment]
![Uploading Screenshot_2023-01-21-15-47-08-374_name.monwf.customiuizer.jpg…]()

**Comment by Bladius2022** [comment]
I just have the option Show seconds selected and from the 2nd version it does not work

**Comment by MonwF** [comment]
reupload. i cant view the oic

**Comment by Bladius2022** [comment]
![Uploading Screenshot_2023-01-21-15-47-08-374_name.monwf.customiuizer.jpg…]()

**Comment by Bladius2022** [comment]
I can not help it.  it's GitHub's fault.  There is no other way to upload a screenshot.  but I don't even know what to show you, it's only one option

**Comment by MonwF** [comment]
sorry. i can't help without a device on miui 13

**Comment by MonwF** [comment]
chimi https://github.com/yonghen/chimi-/releases

**Comment by Bladius2022** [comment]
The seconds module in the clock I was talking about was something else.  How to enable seconds in the taskbar clock in Chimi?

**Comment by Bladius2022** [comment]
Unfortunately, Chimi is very outdated.  I've tested them before.  It practically does not work in it.  Most options do not make any changes.  I do not know what you changed in the code, but in my opinion it is enough to undo the changes and restore what was in the version from 6.1.2023.  There were seconds

**Comment by MonwF** [comment]
undo is impossible. just keep old version then

**Comment by Bladius2022** [comment]
On MIUI 14 with Android 12 (Redmi Note 10 - sunny) second still not working

**Comment by MonwF** [comment]
backup settings and upload xml or screenshot

**Comment by MonwF** [comment]
> > backup settings and upload xml or screenshot
> 
> what is the location of the created copy? I can not find her

use chimi.

**Comment by guillermorojaz** [comment]
The WooBox module is working perfectly in that section. 


![Screenshot_2023-02-02-15-53-39-089_com lt2333 simplicitytools](https://user-images.githubusercontent.com/110266701/216436079-460af1d5-1d25-45fe-91e1-0360548a58df.jpg)
 

![Screenshot_2023-02-02-15-53-39-089_com lt2333 simplicitytools](https://user-images.githubusercontent.com/110266701/216436106-f9e12e89-779f-4fb6-9dc4-22983284c8c4.jpg)
