### ISSUE TITLE
Clock does not change position.

### ISSUE THREAD

**Issue by guillermorojaz** [MonwF/customiuizer#136]
The watch does not change position when trying to move it to the right. the signal indicators if they can move to the left. miui13a12 global

**Comment by MonwF** [comment]
no device with miui 13 to test

**Comment by Ankit2502** [comment]
Btw how I can enable seconds in status bar??
I can't find the option

![Screenshot_2023-02-12-15-38-17-149_name monwf customiuizer](https://user-images.githubusercontent.com/89592455/218304871-6e9683aa-1c3e-40d5-9e60-617c2da76c3a.jpg)
![Screenshot_2023-02-12-15-37-36-148_name monwf customiuizer](https://user-images.githubusercontent.com/89592455/218304872-80889755-c677-492f-bd67-303ef3822b21.jpg)
![Screenshot_2023-02-12-15-37-07-903_com kiwibrowser browser](https://user-images.githubusercontent.com/89592455/218304874-b0218882-d993-4a8f-8317-6e6f20785e28.jpg)

**Comment by MonwF** [comment]
system - statusbar - clock settings

**Comment by ahsim** [comment]
In my case clock can change position to right only in portrait mode. In landscape clock doesn't displayed. Can you check this? My miui also 13, android 12.
