### ISSUE TITLE
seconds don't update

### ISSUE THREAD

**Issue by guillermorojaz** [MonwF/customiuizer#137]
Seconds are not updated in the Custom Format section. Try all possible formats. hh:mm:sshⓂ️s

I add;
Get them updated by installing the Chimi module, which has the option Clock refresh interval 1 sec.

**Comment by MonwF** [comment]
how about turn off custom format

**Comment by guillermorojaz** [comment]
works. 
Disable Custom format and enable show seconds. 
I hope they can solve that detail in the custom format. 
My preference is h:m:s (9:8:7)

**Comment by MonwF** [comment]
> works. Disable Custom format and enable show seconds. I hope they can solve that detail in the custom format. My preference is hⓂ️s (9:8:7)

format must contains :ss
