### ISSUE TITLE
[Request] Enable / Disable new powermenu that's from SystemUI Plugin 

### ISSUE THREAD

**Issue by gemerfoxymk2** [MonwF/customiuizer#138]
It would be nice if that Global users can enable the new power menu implementation and CN users who wants older power menu without decompile and recompile System.

This might helpful for some custom theme that themed the power menu.

**Comment by MonwF** [comment]
miui eu rom has new power menu style by default

**Comment by gemerfoxymk2** [comment]
Not everyone has MIUI EU, especially Mediatek devices, and not everyone liking the new power menu

**Comment by MonwF** [comment]
sorry for that.
