### ISSUE TITLE
Fix for package installer doesn't work

### ISSUE THREAD

**Issue by fixsssator** [MonwF/customiuizer#14]
Hello. 
The problem is - I can't install system package updates 
Fix for package installer doesn't work.

**Comment by MonwF** [comment]
which version of miui package installer

**Comment by fixsssator** [comment]
V4.3.7-20220726

**Comment by MonwF** [comment]
provide error message or screenshot or apk

**Comment by fixsssator** [comment]
![image](https://user-images.githubusercontent.com/74709706/184294099-9a4abd3a-894e-49a4-87d7-691f395bfd54.png)
Sure

**Comment by MonwF** [comment]
> ![image](https://user-images.githubusercontent.com/74709706/184294099-9a4abd3a-894e-49a4-87d7-691f395bfd54.png) Sure

install apk from Files app

**Comment by fixsssator** [comment]
That's always work if I use file explorer 
That's why this fix was created. To install anywhere and anyhow. And it doesn't work

**Comment by MonwF** [comment]
get 08.17 and try

**Comment by fixsssator** [comment]
Thank you. You are amazing. The problem is solved.
