### ISSUE TITLE
Bug, you can't set the volume level for notifications separately.

### ISSUE THREAD

**Issue by Bladius2022** [MonwF/customiuizer#141]
Bug, you can't set the volume level for notifications separately.  The bar is positioned the same as the multimedia slider

**Comment by MonwF** [comment]
> Bug, you can't set the volume level for notifications separately. The bar is positioned the same as the bell slider

restart system first?

**Comment by Bladius2022** [comment]
Test, and not work

**Comment by Ankit2502** [comment]
Well you can also look into this...
The extended notification ui is not optimised for miui pad hence giving weired look

![Screenshot_2023-02-12-07-50-50-554_com kiwibrowser browser](https://user-images.githubusercontent.com/89592455/218289495-cf6c28bc-33c0-4616-9523-1d127d21e1b3.jpg)

Not a big issue bec I don't use this option much and I don't need bec this tab doesn't have sim support... So no call or useless massages.. in WhatsApp telegram their is option to mute faltu chats...
