### ISSUE TITLE
[feature request] Able to add the mic/camera indicator for MIUI 14

### ISSUE THREAD

**Issue by JaneValleyhasBtaken** [MonwF/customiuizer#142]
It seems like the MIUI 14 kills the both indicators (the green dot) and tiles for mic/camera access.
Would you consider add them back by this app?

**Reason**: Not having this feature is really pain in the ass, I can't tell if my VoIP app is still using mic or not. And if the mic is accidently turn off (not muted from the VoIP app), I can toggle this tile on and off to reenable it. But MIUI kill the tiles and indicators.

未来是否能从这个软件添加被MIUI 14砍掉的“麦克风/摄像头使用”的设置磁贴和指示器？非常感谢。

**Comment by MonwF** [comment]
指示器好像在隐私听保护里能开关？原来的磁贴没见过

**Comment by JaneValleyhasBtaken** [comment]
我不太确定（现在我回到了类原生所以没法确定）
我当时刷的是EU，翻遍了整个设置都没找到指示器开关。
而至于磁贴，它本身是在MIUI13是有的（Android12新功能），在控制中心里可以添加。但是到了14就消失了。
所以这个问题大概是无疾而终了

**Comment by chenxiccc** [comment]
在 手机管家 隐私保护 照明弹 里 开启“应用敏感行为提醒”

**Comment by chenxiccc** [comment]
![Screenshot_2023-01-27-23-01-46-591_com.miui.securitycenter-edit.jpg](https://user-images.githubusercontent.com/1096853/215118362-43c8dda6-fb57-46bc-a89b-df93576b0e73.jpg)

**Comment by JaneValleyhasBtaken** [comment]
原来在这里…
