### ISSUE TITLE
[Feature request] Network Speed dual row style

### ISSUE THREAD

**Issue by Luq4dmin** [MonwF/customiuizer#143]
![IMG_20230122_141339](https://user-images.githubusercontent.com/66191105/213903376-41ed2f9e-0619-43b2-9d17-08f93133e56f.jpg)
Hello great dev. Can I request to add this style of Network Speed label in the status bar in future updates ? It would be great if we have this minimalist option instead of the default huge one. Thanks 😁

**Comment by MonwF** [comment]
not planned
