### ISSUE TITLE
[Bug] show brightness percentage

### ISSUE THREAD

**Issue by erfirya** [MonwF/customiuizer#144]
its not displaying the brightness level when I change the brightness in qs, using the latest v23.01.21. it wasn't working in the previous version too

**Comment by MonwF** [comment]
miui 14 with new control center doesn't work. whats your env

**Comment by erfirya** [comment]
MIUI 13 android 12

**Comment by MonwF** [comment]
keep use old version. i dont have a device on miui13 now

**Comment by erfirya** [comment]
also can we have the setting back for clock settings & network speed mod where you choose to set the update interval between the start/end of a second. thank you

**Comment by MonwF** [comment]
network speed interval didn't support before?

**Comment by erfirya** [comment]
I'm not talking about this 
![Screenshot_2023-01-23-10-07-58-296_name monwf customiuizer](https://user-images.githubusercontent.com/71990871/213955012-3414840c-efa2-47ee-b88c-20c6e4c61504.jpg)
 what I'm asking is the one where you set it to update at the start of a second/end of a second. but now it was removed

**Comment by MonwF** [comment]
clock in status bar does support the start point. i dont think it is important so i removed it

**Comment by erfirya** [comment]
can we please have it back? because even though I've set network speed update interval to 1s, its not synchronized with the seconds in the clock status bar. because the clock in status bar updates at the start of a second while I've set the network speed interval to the end of a second before the setting was removed.

**Comment by MonwF** [comment]
[app-release.zip](https://github.com/MonwF/customiuizer/files/10496286/app-release.zip)

add clock sync point option

**Comment by MonwF** [comment]
> its not displaying the brightness level when I change the brightness in qs, using the latest v23.01.21. it wasn't working in the previous version too

which style of control center do you prefer about showing brightness pct ? 
i'll fix it in the next release

**Comment by erfirya** [comment]
i'm using the new version of control center. also, the clock sync point option didn't fix the sync issues because in the previous version it was for the network speed mod, so if you can add it to network speed mod too i'd be very happy

**Comment by MonwF** [comment]
> i'm using the new version of control center. also, the clock sync point option didn't fix the sync issues because in the previous version it was for the network speed mod, so if you can add it to network speed mod too i'd be very happy

no, the sync point option was not for network speed in version 3.2.1. i have checked the source

**Comment by erfirya** [comment]
oh sorry. then can you please make an option to choose when time (second) will update between the start or the end of a second?

not like this
![Screenshot_2023-01-31-16-46-38-241_name monwf customiuizer](https://user-images.githubusercontent.com/71990871/215712832-ff020739-deec-4713-b3a0-abb49a55a865.jpg)

**Comment by MonwF** [comment]
you can try to turn off this sync point option? this option has the same effect as before.

get this apk. show percentage should be fixed


[app.zip](https://github.com/MonwF/customiuizer/files/10545183/app.zip)
