### ISSUE TITLE
Problems with the clock statusbar v230121

### ISSUE THREAD

**Issue by guillermorojaz** [MonwF/customiuizer#146]
In version 230114, in the custom format allowed me to give 2 lines to the clock format. In this case I was using h m ss and the second line E d and giving the result that I show in the image. 
having activated the Dual rom statusbar.
  

![Screenshot_2023-01-22-12-00-00-805_name monwf customiuizer](https://user-images.githubusercontent.com/110266701/213926178-7bb4b35e-37b4-4c20-a477-d462b52248cb.jpg)

in v230121 this changed. the clock has been completely reduced having the same Configurations.  

![Screenshot_2023-01-22-12-14-35-470_name monwf customiuizer](https://user-images.githubusercontent.com/110266701/213926601-a54adad9-abff-4d67-a733-db0f13492bc1.jpg) 

note: can i use spanish to address here?

**Comment by guillermorojaz** [comment]
I add: 
I have reinstalled v230114, resetart systemui and everything is back to my liking. 

You can undo those changes that you made in the section of clock settings leaving them as they were in v230114?
It's great to have the time and date in the same place!

**Comment by MonwF** [comment]
so whats your final format and result  in 23.1.21 . one thing is clear that the format must contain :ss if you want to show seconds correctly

**Comment by guillermorojaz** [comment]
The final format or result of v23.1.21 is a very small size. 
Does not take into account the setting FONT SIZE. 
I am already clear that the format must be: ss so that it updates every second.

**Comment by guillermorojaz** [comment]
v23.1.21 is a very small size. 

![Screenshot_2023-01-22-17-07-12-375_name monwf customiuizer](https://user-images.githubusercontent.com/110266701/213940646-15bddf40-eb94-49c1-a01a-f4512d2fdcd0.jpg)
![Screenshot_2023-01-22-17-07-32-152_name monwf customiuizer](https://user-images.githubusercontent.com/110266701/213940665-a3b17c45-d89c-472c-8949-eb1b80924501.jpg)
![Screenshot_2023-01-22-17-07-54-538_name monwf customiuizer](https://user-images.githubusercontent.com/110266701/213940670-260c687a-c7f8-4194-a169-f47ae1070ee5.jpg)
![Screenshot_2023-01-22-17-07-47-204_name monwf customiuizer](https://user-images.githubusercontent.com/110266701/213940733-10a0556c-34bd-44e4-b171-d6f3b9fbf852.jpg)

**Comment by MonwF** [comment]
font size will be set to 8 if it is greater than 10. did you set font size to 15?

**Comment by guillermorojaz** [comment]
Yeah. I have always kept the font size at 15. 
The same Tried various sizes but the result is the same. 
I will leave you shots of v23.1.14!

**Comment by guillermorojaz** [comment]
V2.1.14
![Screenshot_2023-01-22-17-22-25-665_name monwf customiuizer](https://user-images.githubusercontent.com/110266701/213941381-e0b7d470-91f6-42c8-8279-6314a67fe266.jpg)
![IMG_20230122_172316](https://user-images.githubusercontent.com/110266701/213941403-a5236d34-fb23-4262-b172-f1ec14098459.jpg)
![Screenshot_2023-01-22-17-23-40-868_name monwf customiuizer](https://user-images.githubusercontent.com/110266701/213941407-7c0d2767-edcb-4dbd-865c-bac3f488ae9a.jpg)

**Comment by guillermorojaz** [comment]
Because my suggestion to go back to the v23.1.14 format, Which if it takes the adjustment of the font size.

**Comment by MonwF** [comment]
you set font size to 15. so it will be set to 8 in 23.1.21

**Comment by MonwF** [comment]
> for that reason my suggestion to go back to the v23.1.14 format, Which if it takes the adjustment of the font size.

no. many people have question about display error with large font and dual lines format

**Comment by guillermorojaz** [comment]
The problem with v23.1.21 is giving it a 2-line format in the custom format section!

**Comment by guillermorojaz** [comment]
![Screenshot_2023-01-22-17-38-50-056_name monwf customiuizer](https://user-images.githubusercontent.com/110266701/213942227-86e97fc6-5bc8-4cdf-a36f-384ef3459de5.jpg)
![Screenshot_2023-01-22-17-42-11-180_name monwf customiuizer](https://user-images.githubusercontent.com/110266701/213942229-82aef986-224c-46a7-a213-4982405ea9b1.jpg)

**Comment by MonwF** [comment]
display in 2 lines with large font is edge case
