### ISSUE TITLE
截图时隐藏叠加层无效果

### ISSUE THREAD

**Issue by zzzsw7** [MonwF/customiuizer#15]

**Comment by MonwF** [comment]
提供基本的信息先 系统版本 哪个app的叠加层
另外要加产生叠加层的app加入到lsp作用域

**Comment by zzzsw7** [comment]
> 提供基本的信息先 系统版本 哪个app的叠加层 另外要将产生叠加层的app加入到lsp作用域

系统版本为a12MIUI13 22.6.22开发内测 叠加层应用为HttpCanary 已加入lsp作用域并重启截屏发现无效 重启手机也并无效果

**Comment by MonwF** [comment]
> > 提供基本的信息先 系统版本 哪个app的叠加层 另外要将产生叠加层的app加入到lsp作用域
> 
> 系统版本为a12MIUI13 22.6.22开发内测 叠加层应用为HttpCanary 已加入lsp作用域并重启截屏发现无效 重启手机也并无效果

它这个“叠加层”是用画中画实现的，类似于视频app小窗播放，暂时不支持

**Comment by zzzsw7** [comment]
> > > 提供基本的信息先 系统版本 哪个app的叠加层 另外要将产生叠加层的app加入到lsp作用域
> > 
> > 
> > 系统版本为a12MIUI13 22.6.22开发内测 叠加层应用为HttpCanary 已加入lsp作用域并重启截屏发现无效 重启手机也并无效果
> 
> 它这个“叠加层”是用画中画实现的，类似于视频app小窗播放，暂时不支持

除小窗播放类型的叠加层 悬浮球之类的也无法隐藏 例如FV悬浮球或scene5的负载监视器悬窗等

**Comment by MonwF** [comment]
> > > > 提供基本的信息先 系统版本 哪个app的叠加层 另外要将产生叠加层的app加入到lsp作用域
> > > 
> > > 
> > > 系统版本为a12MIUI13 22.6.22开发内测 叠加层应用为HttpCanary 已加入lsp作用域并重启截屏发现无效 重启手机也并无效果
> > 
> > 
> > 它这个“叠加层”是用画中画实现的，类似于视频app小窗播放，暂时不支持
> 
> 除小窗播放类型的叠加层 悬浮球之类的也无法隐藏 例如FV悬浮球或scene5的负载监视器悬窗等

[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9466569/app-release.apk.zip)
只能做到这个样子了，后面半透明层搞不定

**Comment by MonwF** [comment]
测试最新版 @zzzsw7

**Comment by zzzsw7** [comment]
> 测试最新版 @zzzsw7

最新版截图的同时悬浮层会闪烁一下 截图后叠加层确实不会出现在截图中 期待有一天录屏也能隐藏👍

**Comment by MonwF** [comment]
> > 测试最新版 @zzzsw7
> 
> 最新版截图的同时悬浮层会闪烁一下 截图后叠加层确实不会出现在截图中 期待有一天录屏也能隐藏👍

截图时先隐藏，截图完再显示出来。。全局侧边栏也是这样的原理。

----
录屏是系统录屏吗？之前好像是可以的，咋还改挂了

**Comment by zzzsw7** [comment]
> > > 测试最新版 @zzzsw7
> > 
> > 
> > 最新版截图的同时悬浮层会闪烁一下 截图后叠加层确实不会出现在截图中 期待有一天录屏也能隐藏👍
> 
> 截图时先隐藏，截图完再显示出来。。全局侧边栏也是这样的原理。
> 
> 录屏是系统录屏吗？之前好像是可以的，咋还改挂了

啊哈  是系统录屏呀 录屏确实一点效果都没有

**Comment by MonwF** [comment]
系统录屏我这边完全没问题呀，添加到作用域里没

**Comment by zzzsw7** [comment]
> 系统录屏我这边完全没问题呀，添加到作用域里没 @zzzsw7
确实不行，截图是可以隐藏的，录屏就完全没效果，重启过作用域应用和录屏了

**Comment by zzzsw7** [comment]
![Screenshot_2022-11-03-18-12-57-797_com miui gallery](https://user-images.githubusercontent.com/104837265/199695623-d8f2ba47-b18a-430b-803e-e5ab90187504.jpg)
![Uploading Screenshot_2022-11-03-18-12-38-394_com.miui.home.jpg…]()

**Comment by MonwF** [comment]
我懂你的意思了，是在录屏期间隐藏悬浮层。。我理解成录屏的计时器在截图时没有隐藏成功，等后续吧，搞其他功能了
