### ISSUE TITLE
Ext Power Menu

### ISSUE THREAD

**Issue by Ricc4rdo0107** [MonwF/customiuizer#153]
The function Extend Power Menu is not working on MIUI 13 Global Android 12

**Comment by MonwF** [comment]
don't have device to debug and support for miui 13 is discontinued

**Comment by MonwF** [comment]
extract systemui apk from your system.

**Comment by 3zozHashim** [comment]
works here

android 12, miui 13

poco f3 (indonesia stock)

**Comment by Ricc4rdo0107** [comment]
I found a solution, just installed customiuizer14
