### ISSUE TITLE
Bug. Charging information.

### ISSUE THREAD

**Issue by YurKa336** [MonwF/customiuizer#155]
In the latest version of the customiuizer, zeros are shown instead of charging information
![Screenshot_2023-02-03-15-05-53-757-edit_lockscreen](https://user-images.githubusercontent.com/107347313/216617735-ec5f7e1a-d9e5-4ddb-83fc-397473a9a6fe.jpg)

**Comment by MonwF** [comment]
is the previous version ok?

**Comment by YurKa336** [comment]
In v23.01.21 everything was fine

**Comment by MonwF** [comment]
restart system. is this on lockscreen?

**Comment by YurKa336** [comment]
Rebooting the system does not help
![Screenshot_2023-02-03-16-31-37-202_lockscreen](https://user-images.githubusercontent.com/107347313/216630050-d30e9904-398b-44a0-92f6-6eb924fe087a.jpg)

and just installed the previous version again and everything works there

**Comment by MonwF** [comment]
i didn't change related code. everything seems ok on my device with miui 14

**Comment by YurKa336** [comment]
I have redmi note 10 pro with miui 13.0.17.  It's sad, it was a good feature.  I wonder what is causing this problem

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/10662826/app-develop.zip)

try this build

**Comment by YurKa336** [comment]
It work. Thanks:)
