### ISSUE TITLE
[Request] gesture with 3rd party launcher

### ISSUE THREAD

**Issue by UniverseCodex01** [MonwF/customiuizer#156]
It's possible to add an option to force miui launcher gestures with all 3rd party launchers, because since a11 we can't use gestures with any launcher and any Dev provided a 100% working solution. For example a modification in that miui launcher still as default home screen but home gestures invoke the 3rd party launcher and 3rd party launcher also is hidden from recent items and is locked in memory to generate the effect of 3rd party launcher is the default home screen, idk.

**Comment by MonwF** [comment]
it's a hard work

**Comment by RevealedSoulEven** [comment]
What about working on it? It's only the major requirement left to add

**Comment by MonwF** [comment]
no plan
