### ISSUE TITLE
Bug DISABLE SIGNATURE

### ISSUE THREAD

**Issue by QPLAYid** [MonwF/customiuizer#157]
Disable signature not working on miui 13.0.15  miui global

Redmi note 10 pro 
Android 12

Disable signagure enable but cant install apk (after kill signature) or unsing apk cnt install

**Comment by MonwF** [comment]
apk must be signed with v2

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/10967848/app-develop.zip)
