### ISSUE TITLE
[Small bug] Brightness percentage

### ISSUE THREAD

**Issue by MMETMA** [MonwF/customiuizer#158]
The Brightness percentage in dark mode is black text on dark background it should be white text
![Screenshot_2023-02-04-22-53-39-618_com android chrome](https://user-images.githubusercontent.com/79155572/216789229-e6c105ff-18b6-498c-a8d9-46295bd3fb12.jpg)

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/10610552/app-develop.zip)
