### ISSUE TITLE
Wifi Standard issue

### ISSUE THREAD

**Issue by bobydj** [MonwF/customiuizer#163]
When connection automatically switch to wifi 4 to Wifi 5 its only showing wifi 4.
![Screenshot_2023-02-06-11-57-33-248_com android chrome-edit](https://user-images.githubusercontent.com/81475046/216894792-c9b1ab27-8b68-4343-980c-8a59de266277.jpg)
![Screenshot_2023-02-06-11-58-08-128_com android settings-edit](https://user-images.githubusercontent.com/81475046/216894821-5045dff3-7fc6-4804-8eac-52fdb38bfa65.jpg)

**Comment by MonwF** [comment]
cannot fix it because info is got from  miui wifi controller
