### ISSUE TITLE
[KernelSU]hook不生效，日志显示Cannnot read module's SharedPreferences, some mods might not work!

### ISSUE THREAD

**Issue by toraidl** [MonwF/customiuizer#166]
你好，
机型：小米10，第三方MIUI14。
米客版本：V23.02.03
最近尝试用KernelSU代替Magisk，Zygisk也替换成KernelSU版本的。
LSPosed大部分模块感觉都是正常的。就米客目前所有修改都不生效。 
请问下这个是不兼容的原因吗？

**Comment by MonwF** [comment]
如果lsposed其他模块正常，米客大概率不会有问题. 对照这个排查下吧，我还没使用kernelsu，所以无法提供帮助
https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences

**Comment by toraidl** [comment]
> 

感谢回复，这边再排查一下。
