### ISSUE TITLE
Various --> Alarm Clock Compatibility

### ISSUE THREAD

**Issue by jrotaetxe** [MonwF/customiuizer#17]
Hello again
Would you be so kind as to check the "Alarm clock compatibility" in the "Various" menu?
Thank you in advance, and very ggratefuf for all your effort

**Comment by MonwF** [comment]
> Hello again Would you be so kind as to check the "Alarm clock compatibility" in the "Various" menu? Thank you in advance, and very ggratefuf for all your effort

i can't test it for you. waiting for feedback
[miuizer-test-a12-0817.apk.zip](https://github.com/MonwF/customiuizer/files/9359342/miuizer-test-a12-0817.apk.zip)
