### ISSUE TITLE
System Notification disable stoped working in latest

### ISSUE THREAD

**Issue by Ankit2502** [MonwF/customiuizer#170]
Earlier I was easy used to disable system notification by use this app but now option to disable notification is missing for system notification

![Screenshot_2023-02-11-23-42-36-221_com miui home](https://user-images.githubusercontent.com/89592455/218274519-fc9343aa-9609-491a-b04f-c963c7b17f0c.jpg)

![Screenshot_2023-02-12-06-42-09-132_name monwf customiuizer](https://user-images.githubusercontent.com/89592455/218287875-9037f489-6002-4b86-9e0a-0c701a18a0f4.jpg)

I know this bug bec I use to disable this notification earlier and boot into dsu by dsu sideloader app...

**Comment by MonwF** [comment]
some notifications can not be disabled.

**Comment by Ankit2502** [comment]
> some notifications can not be disabled.

Okay.. i created this bug issue bec I used to disable this before...

 I am using dsu from long time and i always disable the notification of dsu and bootinto dsu by sideloader apk, 

when I had to flash other rom in dsu then I enable notification flash reboot from notification once and again disable notification.. so when ever I had to boot in dsu again I go in dsu app and boot from their.. 

It was disable even before too, just to flash other rom in dsu I enable its notification and now after rebooting when I try to disable it didn't... Anyways...
