### ISSUE TITLE
No Vibration on Failure Not Working

### ISSUE THREAD

**Issue by bobydj** [MonwF/customiuizer#171]
Vibration also running after activate feature "No Vibration on Failure" please check issue and fix next version

![Screenshot_2023-02-13-13-33-27-072-edit_name monwf customiuizer](https://user-images.githubusercontent.com/81475046/218397955-bfc40a82-2a60-4443-bccb-e984896c8f59.jpg)

**Comment by MonwF** [comment]
provide system info

**Comment by bobydj** [comment]
how to collect info?

**Comment by bobydj** [comment]
Rom type: Indian Global Miui Version: 13.0.9.0 Device: Mi 11X

**Comment by MonwF** [comment]
fixed
[app.zip](https://github.com/MonwF/customiuizer/files/10774488/app.zip)
