### ISSUE TITLE
cant import settinge

### ISSUE THREAD

**Issue by HoriKyoukosimp** [MonwF/customiuizer#172]
I tried to import settings and it just show

You'll have to manually enable permission for this option now, good job!

What should i do?

**Comment by MonwF** [comment]
app info - permission - grant storage permission
or activate module and restart. import again

**Comment by HoriKyoukosimp** [comment]
Well funny thing is

There is no way i can enable storage access permission...

**Comment by HoriKyoukosimp** [comment]
![Screenshot_2023-02-13-19-55-11-221_com.google.android.permissioncontroller.png](https://user-images.githubusercontent.com/36318840/218463862-57e91eff-d8f5-4a8b-81e9-cd120f721180.png)
