### ISSUE TITLE
detailed network speed

### ISSUE THREAD

**Issue by AlexPashenko** [MonwF/customiuizer#180]
Greetings. On the latest update, the detailed network speed is reflected only in the control center. It's not in the status bar. Previous version work fine. Xiaomi mi 12 PRO  14.0.23.2.6 by Xiaomi.eu
![Screenshot_2023-02-16-18-08-39-793_com miui home-edit](https://user-images.githubusercontent.com/34424408/219424617-9ad43e04-7198-4074-a681-da1d5024ab67.png)
![Screenshot_2023-02-16-18-15-51-438_com miui home-edit](https://user-images.githubusercontent.com/34424408/219424721-58b54113-9034-455d-ad9b-62e4fe2d74f4.png)

**Comment by MonwF** [comment]
downlad the fixed latest release from github

**Comment by thecodymetalist** [comment]
It happened again on the latest version again. How can I fix it? @MonwF
