### ISSUE TITLE
Screenshots for app in dark theme

### ISSUE THREAD

**Issue by jcperil** [MonwF/customiuizer#182]
Some of us are blinded by light theme screenshots. Please add screenshots for the app in dark theme.

**Comment by MonwF** [comment]
soory. can you explain more?

**Comment by jcperil** [comment]
The screenshots provided with PlayStore or F-Droid are in light mode. As someone who uses system Dark mode, seeing a white color picture suddenly was blinding to my eyes.

That is why, in addition to the light theme screenshots, I requested screenshots for PlayStore and F-Droid in dark theme.

**Comment by MonwF** [comment]
i think you should contact with Mikanoshi.

**Comment by jcperil** [comment]
cc @Mikanoshi

**Comment by Mikanoshi** [comment]
@jcperil My version was last updated years ago, why are you still looking at its screenshots? 😅

**Comment by jcperil** [comment]
I am not. MonwF told me to contact you which I didn't understand why.

@MonwF what I meant is that the screenshots I found in [IzzyOnDroid F-Droid Repo](https://apt.izzysoft.de/fdroid/index/apk/name.monwf.customiuizer) are light themed.

<img src="https://user-images.githubusercontent.com/89805719/219965687-a68ba8ff-ce89-4178-ab10-61dc4c38f344.jpg" height="300px"/>

**Comment by MonwF** [comment]
> I am not. MonwF told me to contact you which I didn't understand why.
> 
> @MonwF what I meant is that the screenshots I found in [IzzyOnDroid F-Droid Repo](https://apt.izzysoft.de/fdroid/index/apk/name.monwf.customiuizer) are light themed.
> 
> <img alt="" height="300px" src="https://user-images.githubusercontent.com/89805719/219965687-a68ba8ff-ce89-4178-ab10-61dc4c38f344.jpg">

i didn't upload apk to f-droid site

**Comment by jcperil** [comment]
The platform is not the issue. The screenshots in Play Store are also light themed.
