### ISSUE TITLE
[Suggestion] Option to increase fingerprint failed attempts

### ISSUE THREAD

**Issue by MMETMA** [MonwF/customiuizer#183]
Add option to increase MAX_FAILED_ATTEMPTS
In `/system/framework/services.jar` class `com.android.server.biometrics.sensors.fingerprint.hidl.LockoutFrameworkImpl` field `MAX_FAILED_ATTEMPTS_LOCKOUT_TIMED`

**Comment by MonwF** [comment]
can you do a pr?

**Comment by MMETMA** [comment]
> can you do a pr?

I don't know how to do it i got the info from a commit in AOSP rom

**Comment by MonwF** [comment]
no plan
