### ISSUE TITLE
[FEATURE] Save screenshots to SD

### ISSUE THREAD

**Issue by V10lator** [MonwF/customiuizer#187]
Would be great to have an option to save to SD or maybe even freely select the save folder instead of just a few hardcoded selections.

**Comment by MonwF** [comment]
screenshot app's code is obfuscated

**Comment by V10lator** [comment]
But you are already altering the folder path here: https://github.com/MonwF/customiuizer/blob/main/app/src/main/java/name/mikanoshi/customiuizer/mods/System.java#L4320-L4350

So why is it possible to change it on internal memory but not to SD card? Don't get me wrong, please: I'm not trying to be mean, I'm just curious.

**Comment by V10lator** [comment]
Looked deeper into the codes: It seems anything is in place, just disabled. So this little patch should do the trick:
```
diff --git a/app/src/main/res/values/arrays.xml b/app/src/main/res/values/arrays.xml
index 20d1ad1..4555ad5 100644
--- a/app/src/main/res/values/arrays.xml
+++ b/app/src/main/res/values/arrays.xml
@@ -784,13 +784,13 @@
                <item>@string/array_default</item>
                <item>Pictures</item>
                <item>DCIM</item>
-<!--           <item>@string/array_path</item>-->
+               <item>@string/array_path</item>
        </string-array>
        <string-array name="screenshotpath_val">
                <item>1</item>
                <item>2</item>
                <item>3</item>
-<!--           <item>4</item>-->
+               <item>4</item>
        </string-array>
        <array name="config_forbidenLongScreenshot">
                <item>com.tencent.map</item>
```
Compiling fails for me through and I don't have the time to check why, so I can't confirm it works.
