### ISSUE TITLE
希望能够添加去除“应用频繁安装”验证弹窗和要求开启“安全守护”提示弹窗

### ISSUE THREAD

**Issue by lvzhenbo** [MonwF/customiuizer#188]
实在过于烦了，原本想开WooBox的，但怕和米客冲突，应用频繁安装的可以参考WooBox，但安全守护的我还没找到有模块

**Comment by MonwF** [comment]
暂不会添加，应该不会冲突。。针对安装器的修改，米客只有显示安装详情和移除来源限制

**Comment by lvzhenbo** [comment]
行吧，慢慢等
