### ISSUE TITLE
Not working: No Vibration on Failure 

### ISSUE THREAD

**Issue by bobydj** [MonwF/customiuizer#189]
Updated to latest but this feature not working on Mi 11X rom 13.0.6.0 Indonesia version. Vibrating on Failure Fingerprint

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/10810304/app.zip)

try this build

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/10967869/app-develop.zip)
@bobydj
