### ISSUE TITLE
Bug. Volume buttons

### ISSUE THREAD

**Issue by YurKa336** [MonwF/customiuizer#190]
Volume up and down actions not working
Phone: Redmi Note 10 Pro, MIUI 13.0.17, android 12.

**Comment by vdmvdm** [comment]
Yes! Please fix :(

**Comment by MonwF** [comment]
> Yes! Please fix :(

miui 13?

**Comment by vdmvdm** [comment]
> > Yes! Please fix :(
> 
> miui 13?

Yes MIUI 13

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/10948983/app.zip)

**Comment by vdmvdm** [comment]
> [app.zip](https://github.com/MonwF/customiuizer/files/10948983/app.zip)

Thanks a lot, but this doesn't work for me. I deactivated my Chi Mi Module so it didn't interfere with custoMIUIzer, but I can't control music with the volume buttons

**Comment by MonwF** [comment]
> Thanks a lot, but this doesn't work for me. I deactivated my Chi Mi Module so it didn't interfere with custoMIUIzer, but I can't control music with the volume buttons

[app.zip](https://github.com/MonwF/customiuizer/files/10967980/app.zip)

**Comment by vdmvdm** [comment]
This is incredibly fast work, wow!
It now mostly works, I can pause songs but I can't really make them play again after. Skipping songs works like a charm tho

**Comment by MonwF** [comment]
ok. without miui 13 device it may be difficult

**Comment by vdmvdm** [comment]
Ah that sucks..Hopefully someday tho

**Comment by MonwF** [comment]
> Ah that sucks..Hopefully someday tho

if you want to play\pause songs, you should add the music app to lsposed scope @vdmvdm

**Comment by vdmvdm** [comment]
@MonwF ,hm I think I did what you meant but I couldnt get it to work by adding it to lsposed (yt music)
