### ISSUE TITLE
开启无字模式后解锁桌面布局数量失效

### ISSUE THREAD

**Issue by XY50** [MonwF/customiuizer#193]
开启无字模式后解锁桌面布局数量失效

**Comment by MonwF** [comment]
是网格选择没有，还是设置后，布局没改

**Comment by MonwF** [comment]
已修复，网盘下载

**Comment by XY50** [comment]
虽然显示出来了，但设置无效

**Comment by XY50** [comment]
无字模式下，不管将布局设置为几乘几，都会被强制改为4×7

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/10879364/app-develop.zip)
试下

**Comment by XY50** [comment]
好了

**Comment by XY50** [comment]
无字模式下的布局不会自动缩放图标，布局太紧，需要自己单独调整图标大小
