### ISSUE TITLE
Screenshot options bug

### ISSUE THREAD

**Issue by MMETMA** [MonwF/customiuizer#195]
Setting the screenshot format to png or webp just creates a 0 bytes file
![IMG_20230223_225812](https://user-images.githubusercontent.com/79155572/221028876-33f8ac33-83b6-48a4-aed2-fab5ca8d00c4.jpg)

.
.
.

Also the screenshot folder option is duplicated once in system/other and the other in system/other/screenshot configuration

.
.
.

And in screenshot configuration there's a grayed out   ##"selected path" option
![IMG_20230223_230231](https://user-images.githubusercontent.com/79155572/221029701-fc5f52fa-2077-4e73-9f02-f2b178d085c8.jpg)

**Comment by MonwF** [comment]
update screenshots app to 1.5.
one for screenshot save folder. the other is for album

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/11218746/app.zip)
