### ISSUE TITLE
图标问题

### ISSUE THREAD

**Issue by XY50** [MonwF/customiuizer#196]
图标都换了，图标太小问题还是没有解决
明明把24改成30改有两个数字就能解决，却一直没有修复，逼死强迫症啊∽
![Screenshot_2023-02-24-08-30-14-677_com android settings-edit](https://user-images.githubusercontent.com/121076219/221064681-e34d8fe1-4e35-424b-aeb8-7dbdda1c2b96.jpg)
![Screenshot_2023-02-24-02-05-41-024_com android settings-edit](https://user-images.githubusercontent.com/121076219/221064717-89352261-5b68-4aae-b644-009a2f333392.jpg)
![Screenshot_2023-02-24-08-52-30-933_bin mt plus canary-edit](https://user-images.githubusercontent.com/121076219/221065315-fc81f366-530a-4ce2-a618-bdedf15356d5.jpg)
难道说只有我手机显示这个图标太小

**Comment by XY50** [comment]
我是小白，对这些不太懂，如果说错了请忽略

**Comment by MonwF** [comment]
因为我的手机更合适

**Comment by XY50** [comment]
好吧。。。

**Comment by MonwF** [comment]
这里是取header_icon_size，你看下settings里面的这个dimen值是多少

**Comment by XY50** [comment]
![Screenshot_2023-02-24-15-01-33-629_ru maximoff apktool](https://user-images.githubusercontent.com/121076219/221114140-c21904d9-9119-44ca-8c30-8c37b977f4d6.jpg)
![Screenshot_2023-02-24-15-01-13-846_ru maximoff apktool](https://user-images.githubusercontent.com/121076219/221114173-e622c3cb-b902-4363-b58c-b08245069a3c.jpg)
是这个吗？
