### ISSUE TITLE
希望添加“音乐通知颜色调整的功能”

### ISSUE THREAD

**Issue by Duck-Deng** [MonwF/customiuizer#198]
MIUI14的音乐通知根据专辑图取色，这就会导致文字颜色与专辑图颜色相似，难以辨认。希望可以添加一个更改文字颜色的功能，或者给专辑图片加个遮罩
![Screenshot_2023-02-26-21-17-17-201_com lemurbrowser exts](https://user-images.githubusercontent.com/64295725/221412731-718b7bed-0e13-4736-afe3-b66a22b4e2d7.jpg)
![Screenshot_2023-02-26-21-15-42-828_com zuoyebang knowledge](https://user-images.githubusercontent.com/64295725/221412735-19b7d86c-e40a-470b-8bc1-c9d059b484d0.jpg)

**Comment by Ankit2502** [comment]
Also pls add option to disable music notification even it it's playing as in miui china you get option in control center which looks cool and good so don't need this extra music playing notification in notification area...

**Comment by Duck-Deng** [comment]
> 

There doesn't seem to be any player that disables music notifications, including YouTube and spotify. maybe you could look for the Xposed module? Or open a new issues?

**Comment by Ankit2502** [comment]
> > 
> 
> There doesn't seem to be any player that could disables music notifications, including YouTube and spotify. maybe you could look for the Xposed module? Or open a new issues?

Their are no Xposed module or any way to remove that notification... Earlier that notification ipused to get disable from settings notification but now idk what miui does.. even that doesn't work...

**Comment by MonwF** [comment]
use miui extra
