### ISSUE TITLE
Secure Tiles doesn't work

### ISSUE THREAD

**Issue by Vader77Darth** [MonwF/customiuizer#20]
I can't secure Tiles on the lock screen on miui 13.0.2.0 SJGEUXM

**Comment by MonwF** [comment]
> I can't secure Tiles on the lock screen on miui 13.0.2.0 SJGEUXM

please help test this build
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9572259/app-release.apk.zip)

**Comment by Vader77Darth** [comment]
That fixed it for me!
