### ISSUE TITLE
[question] Settings management 

### ISSUE THREAD

**Issue by YurKa336** [MonwF/customiuizer#200]
I switched to miui 14 and I have such a problem, how to solve it?
![Screenshot_2023-03-03-00-13-26-671_name monwf customiuizer-edit](https://user-images.githubusercontent.com/107347313/222573261-c34c0032-0927-4967-aadb-3cfd83a60af5.jpg)

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/10877951/app.zip)
try this build
