### ISSUE TITLE
No option at all is working. MIUI 14.0.6 CN

### ISSUE THREAD

**Issue by alpha4041** [MonwF/customiuizer#201]
I'm using customiuizer version 23.02.25, but I also tried 23.02.21.
My device is Xiaomi 11 Lite 5G NE with MIUI 14.0.6 CN A13

After enabling the module and rebooting, opening the app and enabling options doesn't do anything at all, except change the state of the switch in the app.
Options regarding APK signatures don't even change the switch state in 23.02.21 but it at least does that in 23.02.25
After rebooting the state of the switches gets reset, and no effect of any option is visible at all.

The Lsposed version is 1.8.6 and the logs say this:
> Cannot read module's sharedpreferences [...]

Sorry if I didn't include the full logs but I don't know why the log zip extraction fails.

**Comment by MonwF** [comment]
lsposed's full version?

**Comment by alpha4041** [comment]
> lsposed's full version?

6838

**Comment by MonwF** [comment]
downgrade to 6712 https://github.com/LSPosed/LSPosed/releases
