### ISSUE TITLE
底栏边距无效！

### ISSUE THREAD

**Issue by XY50** [MonwF/customiuizer#202]
底栏边距无效！
另外我想把这三个点调中间去，怎么调都调不上去，所以希望增加底部网格边距，和页面指示器高度最小值调成0
![Screenshot_2023-03-03-19-21-06-209_name monwf customiuizer-edit](https://user-images.githubusercontent.com/121076219/222872366-72d7e539-fd87-42fa-b691-2d10f8ed6aa7.jpg)
![Screenshot_2023-03-04-10-49-31-320_com miui home-edit](https://user-images.githubusercontent.com/121076219/222872371-c8aa78a8-40ef-40b8-a156-69787e7572df.jpg)

**Comment by MonwF** [comment]
不是调这个的，桌面相关请用miuihomer
