### ISSUE TITLE
Bug. Unlock frame rate in screen recording app

### ISSUE THREAD

**Issue by YurKa336** [MonwF/customiuizer#204]
The unlock frame rate function in the screen recording app does not work.
Screen recording app version: 3.12.6.4.0
Phone: Redmi Note 10 Pro, A13, MIUI Global 14.0.1
![Screenshot_2023-03-04-12-15-50-707_com miui screenrecorder-edit](https://user-images.githubusercontent.com/107347313/222894391-ecc726bc-4e90-4427-bff5-e69b5a3b42e7.jpg)

**Comment by MonwF** [comment]
any lsp log? ensure screenrecorder app is in the scope

**Comment by YurKa336** [comment]
![Screenshot_2023-03-04-12-28-19-528_com android shell-edit](https://user-images.githubusercontent.com/107347313/222894827-a7cec4d1-f86a-4192-9692-6537e48a5555.jpg)

[LSPosed_2023-03-04T12_31_41.673420.zip](https://github.com/MonwF/customiuizer/files/10888060/LSPosed_2023-03-04T12_31_41.673420.zip)

**Comment by YurKa336** [comment]
Judging by the logs, there are still hook errors somewhere
maybe detailed logs are needed?

**Comment by MonwF** [comment]
can't be fixed. apps in miui global rom are all obfuscated

**Comment by 3zozHashim** [comment]
> can't be fixed. apps in miui global rom are all obfuscated

there is an lsposed module that unlocks screen recorder max 120fps and 100 bitrate (im using global miui). It could be of help

It seems to have been removed from lsposed repo in lsposed manager but it still works perfectly

![Screenshot_2023-03-24-07-54-44-251-edit_org swiftapps swiftbackup](https://user-images.githubusercontent.com/115328790/227436565-b5a6434d-ba31-4d11-86a6-46cbdbb15c8b.png)

**Comment by YurKa336** [comment]
Unfortunately this still doesn't work for me.
