### ISSUE TITLE
System / Recent App List / Hide from recents NOT working

### ISSUE THREAD

**Issue by Gausak** [MonwF/customiuizer#206]
The function indicated in the title does not work on a POCO X5 Pro with MIUI.EU 14.0.5.0. Android 12 MIUI14.

This function is very useful to hide in the recent list those applications that you need to be running all the time, such as those used for smart watches but you don't need to see them, Since they just work in the background.

**Comment by MonwF** [comment]
latest module? extract your miuihome and upload. tested with miui eu 14.2.21 dev

**Comment by Gausak** [comment]
> 

Yes, latest module. I don't use the latest dev releases for my device. I can only use the latest stable version. MIUI.EU 14.0.5.0 (redwood)

How can I extract my MiuiHome?

**Comment by Gausak** [comment]
This? (Extracted from a file explorer on my device)
[MiuiHome.zip](https://github.com/MonwF/customiuizer/files/10888950/MiuiHome.zip)

**Comment by MonwF** [comment]
https://t.me/XiaomiEUApps try latest miuihome first

**Comment by Gausak** [comment]
> https://t.me/XiaomiEUApps try latest miuihome first

It still doesn't work after updating to the latest version of miuihome.apk as you indicated

**Comment by MonwF** [comment]
> > https://t.me/XiaomiEUApps try latest miuihome first
> 
> It still doesn't work after updating to the latest version of miuihome.apk as you indicated

did you restart launcher after updating?

**Comment by Gausak** [comment]
> > > https://t.me/XiaomiEUApps try latest miuihome first
> > 
> > 
> > It still doesn't work after updating to the latest version of miuihome.apk as you indicated
> 
> did you restart launcher after updating?

I guess restarting the device also counts as restarting the launcher.

It still doesn't work 😅

**Comment by MonwF** [comment]
screenshot miuihome app info? sorry for that

**Comment by Gausak** [comment]
> screenshot miuihome app info? sorry for that

![Screenshot_2023-03-04-17-09-33-230_com miui securitycenter](https://user-images.githubusercontent.com/126968957/222916552-4f08cadf-da07-45d3-b80e-a71f0ffe502c.jpg)

**Comment by MonwF** [comment]
i checked your miuihome in 14.0.5. it shouldn't be working indeed. but why does  it not work even after updating. i dont get any idea

**Comment by Gausak** [comment]
Don't worry, it's not an essential option either. Thanks for your time and hard work!

**Comment by MonwF** [comment]
try to reoptimize miuihome in lsposed scope list

**Comment by Gausak** [comment]
> try to reoptimize miuihome in lsposed scope list

It doesn't work either, sorry. If you need it, I think I can record a video with the screen recorder, but anyway, I think that everything is well configured since there are many other mods that they do work correctly

**Comment by MonwF** [comment]
export log from lsposed?

**Comment by Gausak** [comment]
[LSPosed_2023-03-14T14_20_20.069.zip](https://github.com/MonwF/customiuizer/files/10969062/LSPosed_2023-03-14T14_20_20.069.zip)
[LSPosed_2023-03-14T14_20_13.085.zip](https://github.com/MonwF/customiuizer/files/10969063/LSPosed_2023-03-14T14_20_13.085.zip)

^_^

**Comment by MonwF** [comment]
1. clean log from menu of lsposed manager.
2. restart launcher from customiuizer
3. trigger recents
4. save lsp log

**Comment by Gausak** [comment]
[LSPosed_2023-03-14T14_47_05.424.zip](https://github.com/MonwF/customiuizer/files/10969334/LSPosed_2023-03-14T14_47_05.424.zip)
[LSPosed_2023-03-14T14_47_09.642.zip](https://github.com/MonwF/customiuizer/files/10969336/LSPosed_2023-03-14T14_47_09.642.zip)

**Comment by MonwF** [comment]
[ 2023-03-14T14:17:46.304    10069:  3751:  3751 I/LSPosed-Bridge  ] [CustoMIUIzer][HideFromRecentsHook] Failed to hook needRemoveTask method in com.android.systemui.shared.recents.system.ActivityManagerWrapper

did you update miuihome??

**Comment by Gausak** [comment]
> [ 2023-03-14T14:17:46.304 10069: 3751: 3751 I/LSPosed-Bridge ] [CustoMIUIzer][HideFromRecentsHook] Failed to hook needRemoveTask method in com.android.systemui.shared.recents.system.ActivityManagerWrapper
> 
> did you update miuihome??

Yep, latest version 4.39.9.6144-0301138 (telegram channel)

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/10969866/app-develop.zip)
try it

**Comment by MonwF** [comment]
forget last build. restart launcher from customiuizer. get this apk
[app.zip](https://github.com/MonwF/customiuizer/files/10970005/app.zip)

**Comment by Gausak** [comment]
Now it works! The only thing is that if I restart the device, the applications reappear in the list of recent apps, but if I open them one by one from here, they are hidden. Video attached.

https://youtube.com/shorts/Fk4ExVHvgB4
