### ISSUE TITLE
Can you replicate the clock mod of the app WooBox?

### ISSUE THREAD

**Issue by guillermorojaz** [MonwF/customiuizer#207]
![Screenshot_2023-03-04-13-34-57-666_com lt2333 simplicitytools](https://user-images.githubusercontent.com/110266701/222920552-6b422cab-c30a-4011-a677-f984b1522014.jpg)

![Screenshot_2023-03-04-13-35-05-848_com lt2333 simplicitytools](https://user-images.githubusercontent.com/110266701/222920558-a9c19d54-6ec5-480a-a2a1-07f5a1d26d50.jpg)

![Screenshot_2023-03-04-13-35-13-076_com lt2333 simplicitytools](https://user-images.githubusercontent.com/110266701/222920562-589f1ee3-931b-409f-870c-d9df7d5b839a.jpg)

![IMG_20230304_133550](https://user-images.githubusercontent.com/110266701/222920577-74546077-4c80-456d-ac07-775cf8bf14db.jpg)

**Comment by MonwF** [comment]
this module has custom farmat tooo

**Comment by guillermorojaz** [comment]
Of course it does or has it, but when creating a double line it does not allow the change of size.

**Comment by guillermorojaz** [comment]
with the format of CustoMIUzer 14: 

![Screenshot_2023-03-05-11-06-54-372_name monwf customiuizer](https://user-images.githubusercontent.com/110266701/222968793-495e624f-facf-40d2-9905-6d1a45f17dcb.jpg)

![IMG_20230305_110801](https://user-images.githubusercontent.com/110266701/222968814-dc78d90e-337b-436a-a025-5ea1ca5c2040.png)



Double line = miniclock! 


 If the WooBox module can do it, why doesn't yours support these configurations?

**Comment by guillermorojaz** [comment]
In the version that incorporates the custom format of the clock it did keep the size that was given to it, but the following versions took the path of the chimi module that does not allow the change of the clock if it is in double row. 


Please consider checking out the WooBox module to replicate this format in CustoMIUzer 14!

**Comment by MonwF** [comment]
customiuizer14 allows you to change font size. but it has a max limit in dual row and a min limit in row. while woobox doesn't have this limit. so what's you want indeed is that clock displays across 2 lines in dual rows statusbar ?

**Comment by guillermorojaz** [comment]
https://user-images.githubusercontent.com/110266701/222976443-2325fd2d-4617-4ed1-a3b4-1200d069becc.mp4

You said it... That the double row clock has NO size limit. As it was in the initial version of custom clock format!  As well as allow the format in seconds in 1 single digit. You just have to see how WaaBox does it. It is free code.

**Comment by guillermorojaz** [comment]
Your module is wonderful. Please take requests from your users. The WooBox module is still there but I am using it only for the reason of this request, the custom clock format.

**Comment by MonwF** [comment]
Don't need to see how woobox does it. i bring the limit to customiuizer
