### ISSUE TITLE
应用分享使用小窗打开不支持 QQ

### ISSUE THREAD

**Issue by xuanmi666** [MonwF/customiuizer#210]
游戏内使用调用微信分享会以小窗模式打开，调用分享 QQ 不会通过小窗打开，但是使用系统相册分享时，通过 QQ 或微信分享都可

另外，能否增加支持应用内跳转以小窗打开，类似于魅族的小窗功能，比如在微信中打开一个文档，是以小窗模式运行

**Comment by MonwF** [comment]
qq的分享非标，需要单独处理，暂无计划

**Comment by MonwF** [comment]
今天上传的针对HyperOS的测试版已经支持
