### ISSUE TITLE
Colorize notification card not working on miui 13

### ISSUE THREAD

**Issue by nhanntt0401** [MonwF/customiuizer#212]
Hi developer,

Colorizing notification not working on miui 13, when i tries to update miui 14, it worked. But for some reason, I dont want to update miui 14. Please have a look at it

**Comment by MonwF** [comment]
without miui 13 device

**Comment by MonwF** [comment]
extract log from lsposed manager

**Comment by 3zozHashim** [comment]
would it be possible of you could restore the old option to make the notification name colored? (without coloring the entire notification)
