### ISSUE TITLE
Gboard 键盘底部填充功能无效

### ISSUE THREAD

**Issue by brainiac19** [MonwF/customiuizer#213]
mi 11 pro，MIUI 14 eu，底部填充数值设置无效

**Comment by MonwF** [comment]
gboard加入作用域没？

**Comment by brainiac19** [comment]
> gboard加入作用域没？

 确实没有，奇怪的是我翻遍了app列表都找不到gboard，不知道这个情况作者有经验吗

**Comment by MonwF** [comment]
> > gboard加入作用域没？
> 
> 确实没有，奇怪的是我翻遍了app列表都找不到gboard，不知道这个情况作者有经验吗

右上角看下有没隐藏系统应用

**Comment by brainiac19** [comment]
> > > gboard加入作用域没？
> > 
> > 
> > 确实没有，奇怪的是我翻遍了app列表都找不到gboard，不知道这个情况作者有经验吗
> 
> 右上角看下有没隐藏系统应用

谢谢作者，是我铸笔，问题已解决
