### ISSUE TITLE
Does not work remap volume keys action feature

### ISSUE THREAD

**Issue by Bagetta** [MonwF/customiuizer#214]
Hello. 
Controls > Volume keys > Volume Up/Down long press action last time worked in [23.01.21](tel:230121) version, newer versions can't remap volume keys at all. 
MIUI v14.0.23.2.6DEV Android 12. 
Please try to fix this issue 🙏

**Comment by MonwF** [comment]
can you help to test the 23.02.x versions?

**Comment by Bagetta** [comment]
> can you help to test the 23.02.x versions?

**Comment by MonwF** [comment]
i reviewed the code after 23.01.21, and didn't find any difference. any lsposed logs after soft reboot ?

**Comment by MonwF** [comment]
did you turn on "move cursor by volume keys" ?

**Comment by Bagetta** [comment]
What logs you need exactly? "Move cursor" feature is turn off.

**Comment by MonwF** [comment]
open lsposed manager, clear log. soft reboot from customiuizer. after reboot, long press volume key. export logs from lsposed.

**Comment by Bagetta** [comment]
[logs.zip](https://github.com/MonwF/customiuizer/files/10967671/logs.zip)

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/10967807/app-develop.zip)
install the apk and reboot

**Comment by Bagetta** [comment]
Yep, now works fine. Thank you!
