### ISSUE TITLE
Quick Rotation doesn't work

### ISSUE THREAD

**Issue by lutfufn** [MonwF/customiuizer#218]
![Screenshot_2023-03-16-18-54-06-195-edit_com opera browser](https://user-images.githubusercontent.com/94114770/225679209-ade9d55f-3691-4eb0-9a94-23416fe22878.jpg)
Quick screen rotation doesn't work. 
MIUI 13.0.4
Android 12
Poco X3 
Version 23.03.15

**Comment by lutfufn** [comment]
I just wanted to add that it does not even show up, It vanished.

**Comment by MonwF** [comment]
tile in cc or rotation suggest?

**Comment by lutfufn** [comment]
I meant that when we rotated the phone, this quick black tile would appear. and when we touch it, screen would rotate.
![225679209-ade9d55f-3691-4eb0-9a94-23416fe22878](https://user-images.githubusercontent.com/94114770/226112576-a0368c78-b8a6-49c7-9832-a7193cc4b8d6.jpg)
But now, After getting the update for customiuizer, It stopped working. And I am assuming this was the setting related to this on customiuizer. 
![Başlıksız](https://user-images.githubusercontent.com/94114770/226112816-eda60bfd-fe40-4e60-80b3-5eeac3484a96.jpeg)

**Comment by 3zozHashim** [comment]
> I meant that when we rotated the phone, this quick black tile would appear. and when we touch it, screen would rotate. ![225679209-ade9d55f-3691-4eb0-9a94-23416fe22878](https://user-images.githubusercontent.com/94114770/226112576-a0368c78-b8a6-49c7-9832-a7193cc4b8d6.jpg) But now, After getting the update for customiuizer, It stopped working. And I am assuming this was the setting related to this on customiuizer. ![Başlıksız](https://user-images.githubusercontent.com/94114770/226112816-eda60bfd-fe40-4e60-80b3-5eeac3484a96.jpeg)

this button only works with the pill

if you use the hide pill option (in gesture settings), it will stop appearing

**Comment by MonwF** [comment]
> > I meant that when we rotated the phone, this quick black tile would appear. and when we touch it, screen would rotate. ![225679209-ade9d55f-3691-4eb0-9a94-23416fe22878](https://user-images.githubusercontent.com/94114770/226112576-a0368c78-b8a6-49c7-9832-a7193cc4b8d6.jpg) But now, After getting the update for customiuizer, It stopped working. And I am assuming this was the setting related to this on customiuizer. ![Başlıksız](https://user-images.githubusercontent.com/94114770/226112816-eda60bfd-fe40-4e60-80b3-5eeac3484a96.jpeg)
> 
> this button only works with the pill
> 
> if you use the hide pill option (in gesture settings), it will stop appearing

right

**Comment by lutfufn** [comment]
Thanks it helped.
Is there a way for this to still work even if hide pill option is enabled?

**Comment by MonwF** [comment]
very hard. rotation suggest is a part of navbar

**Comment by lutfufn** [comment]
I got it.  It works. Wısh it was not hard. Cause the pill is distupting the full screen experience. 
Thanks again for the feedback.
