### ISSUE TITLE
读取闹钟有问题

### ISSUE THREAD

**Issue by langkiss** [MonwF/customiuizer#219]
软件获取的闹钟时间是错误的，与我实际设定的闹钟不相符，目前也没有根据相对时间确定出来具体差了多少。比如我连续设定的三个是周五7点，周六9点，周六10点，但通过锁屏界面显示是周五12点，周五22点和周六12点。
另外锁屏正常模式也无法显示闹钟，通过api读取出来的是如上所示错误的

**Comment by MonwF** [comment]
把闹钟转为系统应用
