### ISSUE TITLE
Feature request: Clock on right

### ISSUE THREAD

**Issue by hadiceberg** [MonwF/customiuizer#22]
Is it possible to add a feature to move clock to the right side of status bar? (Specially useful for devices with a notch)

**Comment by MonwF** [comment]
i have no idea now

**Comment by mhetralla** [comment]
[ChiMi](https://github.com/yonghen/chimi-) and [https://github.com/Simplicity-Team/WooBoxForMIUI](WooBox) can do this. WooBox is open source, maybe you can check how they do it [here](https://github.com/Simplicity-Team/WooBoxForMIUI/blob/main/app/src/main/java/com/lt2333/simplicitytools/hook/app/systemui/StatusBarLayout.kt).

**Comment by MonwF** [comment]
> [ChiMi](https://github.com/yonghen/chimi-) and [https://github.com/Simplicity-Team/WooBoxForMIUI](WooBox) can do this. WooBox is open source, maybe you can check how they do it [here](https://github.com/Simplicity-Team/WooBoxForMIUI/blob/main/app/src/main/java/com/lt2333/simplicitytools/hook/app/systemui/StatusBarLayout.kt).

why not just use them?

**Comment by hadiceberg** [comment]
Hi, I can't find "clock" in this submenu: System/Status bar/Move some icons to the right
Where should I look?

**Comment by MonwF** [comment]
[customiuizer-miui13-1109-test.apk.zip](https://github.com/MonwF/customiuizer/files/9970592/customiuizer-miui13-1109-test.apk.zip)

try this build with the above submenu

**Comment by hadiceberg** [comment]
Thank you.
The clock mod is working.
But when I select network speed indicator to be moved, it doesn't move and also my battery icon which i had hidden, comes back!
![photo_3_2022-11-09_15-17-40](https://user-images.githubusercontent.com/5326305/200823277-860bae24-2e8c-42f8-b230-71b18e2260e1.jpg)
![photo_2_2022-11-09_15-17-40](https://user-images.githubusercontent.com/5326305/200823281-63c7db40-23df-4641-b883-472afbb93626.jpg)
![photo_1_2022-11-09_15-17-40](https://user-images.githubusercontent.com/5326305/200823285-711103e6-6c07-4c55-9074-cdb3aa9aafff.jpg)

**Comment by hadiceberg** [comment]
I restarted systemui every time and opened the settings menu to show current toggles and took screenshots.
I'm using this ROM:
xiaomi.eu_multi_POCOX3Pro_V13.0.8.0.SJUMIXM_v13-12

**Comment by MonwF** [comment]
move clock to right side isn't working from your last picture ?

**Comment by hadiceberg** [comment]
If I only choose toggle Clock, it moves to the right.
But if I choose both network and clock, they both stay at the left and also my battery icon (which should be hidden) appears on the right.
If I only choose network, it doesn't work either.

But clock is fine on it's own.

**Comment by MonwF** [comment]
try to turn off hide notch in system settings

**Comment by MonwF** [comment]
have you got any other xposed tweak installed ?

**Comment by hadiceberg** [comment]
> try to turn off hide notch in system settings
done


> have you got any other xposed tweak installed ?

Only your's is enabled

![photo_1_2022-11-09_15-43-09](https://user-images.githubusercontent.com/5326305/200828055-90a62daf-f916-4ab4-b9f3-037417fe60e1.jpg)
![photo_2_2022-11-09_15-43-09](https://user-images.githubusercontent.com/5326305/200828062-a3766527-0ab0-46fc-9daf-9ed531f4392f.jpg)

**Comment by MonwF** [comment]
does move other icons to right work?
check if any error logs show in lsposed

**Comment by hadiceberg** [comment]
[modules_2022-11-09T15_10_38.34.log](https://github.com/MonwF/customiuizer/files/9970979/modules_2022-11-09T15_10_38.34.log)

**Comment by MonwF** [comment]
pls extract the systemui apk and send it to me

**Comment by MonwF** [comment]
i've found the reason and will fix it soon

**Comment by MonwF** [comment]
[app-release.zip](https://github.com/MonwF/customiuizer/files/9977058/app-release.zip)

get this apk

**Comment by MonwF** [comment]
have you tried it? @hadiceberg

**Comment by hadiceberg** [comment]
I tried it just now!
My phone boots into a black screen! and restarts after a while. how can I disable the module now?

**Comment by hadiceberg** [comment]
I booted into safe mode and now I can disable the module

**Comment by MonwF** [comment]
> I booted into safe mode and now I can disable the module

sorry for that. you can edit pref file located in /data/misc/lspd_xxx/prefs/name.monwf.customiuizer
or just delete it

**Comment by hadiceberg** [comment]
> sorry for that. you can edit pref file located in /data/misc/lspd_xxx/prefs/name.monwf.customiuizer or just delete it
No problem.
Good to know for the next time :)) Booting into safe mode messed up with my phone. After booting normally, all my homescreen shortcuts are gone and many system settings are reverted to default.

**Comment by MonwF** [comment]
in recovery mode， edit the prefs and reboot. i'll try to resolve it tomorrow

**Comment by MonwF** [comment]
[customiuizer13-1111-test.apk.zip](https://github.com/MonwF/customiuizer/files/9986412/customiuizer13-1111-test.apk.zip)

this apk should fix errors on miui 13.0.x

**Comment by hadiceberg** [comment]
Thank you. It's working now. both network speed and clock can be moved to the right.
