### ISSUE TITLE
[Feature Request] Add option to remove Forget Password on lockscreen

### ISSUE THREAD

**Issue by ag6ag1** [MonwF/customiuizer#225]
Device :Poco x3 pro
Miui 14.0.1
Android 13

Please if you can an option to remove the forget password on lockscreen when multiple wrong code entered on the new miui 14

![Screenshot_2023-03-25-18-58-15-863_lockscreen](https://user-images.githubusercontent.com/7378448/227731337-b4723894-fb30-4353-b19b-3a5f01ef77fc.jpg)
![Screenshot_2023-03-25-18-58-20-231_lockscreen](https://user-images.githubusercontent.com/7378448/227731349-70beb9fb-e56c-4834-a68e-11f50928ac7e.jpg)

**Comment by MonwF** [comment]
no plan. edge case
