### ISSUE TITLE
Feature：为应用信息内添加“打开支持的链接”入口

### ISSUE THREAD

**Issue by SummonHIM** [MonwF/customiuizer#227]
希望能在应用信息内添加“打开支持的链接”（android.settings.APP_OPEN_BY_DEFAULT_SETTINGS）入口的功能。

![Screenshot_2023-03-29-16-30-32-532_com android settings](https://user-images.githubusercontent.com/33192611/228475393-b7839725-064c-4ed1-8c5a-bdc7d7c202f3.jpg)

**Comment by MonwF** [comment]
这个可能会加的

**Comment by SummonHIM** [comment]
> 这个可能会加的

我看快6个月没回我以为没计划整了

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/12585235/app.zip)

done
