### ISSUE TITLE
Screenshot configuration doesn't work!

### ISSUE THREAD

**Issue by lutfufn** [MonwF/customiuizer#23]
I am running android 12 and miui 13.0.2 however screenshot configuration doesn't work. I want screenshots to be stored under the pictures folder. When I apply the settings, screenshots are stored under the same folder, which is DCIM.

**Comment by MonwF** [comment]
screenshot app version?

**Comment by lutfufn** [comment]
![Screenshot_2022-09-11-18-17-54-890_name monwf customiuizer](https://user-images.githubusercontent.com/94114770/189535390-cb9e8b60-8c80-4768-a8c4-961430197fb1.jpg)
![Screenshot_2022-09-11-18-19-15-411_name monwf customiuizer](https://user-images.githubusercontent.com/94114770/189535391-3247d97a-5337-4bf2-b676-9fd5136ad06e.jpg)

**Comment by MonwF** [comment]
miu eu or global rom?
i mean the version of miui screenshot app, not customiuizer

**Comment by lutfufn** [comment]
It is eu

**Comment by MonwF** [comment]
> It is eu

default save dir of eu rom is pictures/screenshot. just turn off mods

**Comment by lutfufn** [comment]
> > It is eu
> 
> default save dir of eu rom is pictures/screenshot. just turn off mods

When I disable it, screenshots are still stored in DCIM/SCREENSHOTS

**Comment by MonwF** [comment]
miuiscreenshot app version?

**Comment by mhetralla** [comment]
This happens to me too. Poco F3, MIUI Global 13.0.7,  CustoMIUIzer13 22.09.07, LSPosed 1.8.3 (Zygisk), Screenshot app RELEASE-1.3.12-02111106.

**Comment by MonwF** [comment]
> There's no such thing as miuiscreenshot app! I've been looking everywhere haven't found any!


![Screenshot_2022-09-13-07-25-09-099_com miui securitycenter](https://user-images.githubusercontent.com/1267050/189775379-311d0334-d554-4be7-b780-840fb0f6b248.png)

**Comment by MonwF** [comment]
> This happens to me too. Poco F3, MIUI Global 13.0.7, CustoMIUIzer13 22.09.07, LSPosed 1.8.3 (Zygisk), Screenshot app RELEASE-1.3.12-02111106.

can you look at the file name of saved pictures?

**Comment by lutfufn** [comment]
> > There's no such thing as miuiscreenshot app! I've been looking everywhere haven't found any!
> 
> ![Screenshot_2022-09-13-07-25-09-099_com miui securitycenter](https://user-images.githubusercontent.com/1267050/189775379-311d0334-d554-4be7-b780-840fb0f6b248.png)

![Screenshot_2022-09-13-10-13-12-777_com miui securitycenter](https://user-images.githubusercontent.com/94114770/189835064-8f7412ec-6e69-468b-92e2-734126cbd4b2.jpg)

**Comment by lutfufn** [comment]
> > This happens to me too. Poco F3, MIUI Global 13.0.7, CustoMIUIzer13 22.09.07, LSPosed 1.8.3 (Zygisk), Screenshot app RELEASE-1.3.12-02111106.
> 
> can you look at the file name of saved pictures?

Do you mean this 
![Screenshot_2022-09-13-10-15-04-066_com alphainventor filemanager](https://user-images.githubusercontent.com/94114770/189835343-c6e66304-a673-443e-98df-34e960526b67.jpg)

**Comment by MonwF** [comment]
> Do you mean this ![Screenshot_2022-09-13-10-15-04-066_com alphainventor filemanager](https://user-images.githubusercontent.com/94114770/189835343-c6e66304-a673-443e-98df-34e960526b67.jpg)

enter `Screenshots` folder and copy file name of pictures

**Comment by mhetralla** [comment]
> > This happens to me too. Poco F3, MIUI Global 13.0.7, CustoMIUIzer13 22.09.07, LSPosed 1.8.3 (Zygisk), Screenshot app RELEASE-1.3.12-02111106.
> 
> can you look at the file name of saved pictures?

For example, a screenshot from my browser is named `Screenshot_2022-09-13-09-35-28-238_com.kiwibrowser.browser.jpg`. It follows this pattern: `Screenshot_year-month-day-hour-minute-second-random number_package name of the app`.

**Comment by lutfufn** [comment]
![Screenshot_2022-09-13-12-26-29-722_com alphainventor filemanager](https://user-images.githubusercontent.com/94114770/189865273-b19e5210-a9aa-4540-8fc4-60631432088d.jpg)

**Comment by MonwF** [comment]
fixed. please get the latest apk from https://github.com/MonwF/customiuizer/releases/tag/v22.09.13.
@mhetralla @lutfufn

**Comment by lutfufn** [comment]
Thank you so so much! It works.
I have another thing in mind.  Why "selected path" is faded. Is it because of the OS or is it because I need to do something about it.
![Screenshot_2022-09-13-15-20-39-251_name monwf customiuizer](https://user-images.githubusercontent.com/94114770/189899600-a248abc4-e258-4fe2-8ebe-d12b7ba0268d.jpg)

**Comment by MonwF** [comment]
> Thank you so so much! It works. I have another thing in mind. Why "selected path" is faded. Is it because of the OS or is it because I need to do something about it. ![Screenshot_2022-09-13-15-20-39-251_name monwf customiuizer](https://user-images.githubusercontent.com/94114770/189899600-a248abc4-e258-4fe2-8ebe-d12b7ba0268d.jpg)

i disabled the option

**Comment by lutfufn** [comment]
> > Thank you so so much! It works. I have another thing in mind. Why "selected path" is faded. Is it because of the OS or is it because I need to do something about it. ![Screenshot_2022-09-13-15-20-39-251_name monwf customiuizer](https://user-images.githubusercontent.com/94114770/189899600-a248abc4-e258-4fe2-8ebe-d12b7ba0268d.jpg)
> 
> i disabled the option

Is there any particular reason ?

**Comment by MonwF** [comment]
> Is there any particular reason ?

it doesnt work anymore and i haven't got a solution now

**Comment by lutfufn** [comment]
> > Is there any particular reason ?
> 
> it doesnt work anymore and i haven't got a solution now

Thanks for the explanation and all your hard work!
