### ISSUE TITLE
最近任务-背景模糊 不会自动还原

### ISSUE THREAD

**Issue by Eric-Joker** [MonwF/customiuizer#231]
使用最近任务-背景模糊时，在最近任务界面点下空白处回到系统桌面模糊不会还原

**Comment by MonwF** [comment]
是否是官方桌面？

**Comment by Eric-Joker** [comment]
是的，miui14 a12，redmi note9 pro

**Comment by Ankit2502** [comment]
Yeah it happens in all miui even in china miui by all moding apps.. (woobox,wini,etc) so may be miui problem but for me it occurs less on miui 14 china...
