### ISSUE TITLE
最近任务-隐藏最近无效

### ISSUE THREAD

**Issue by Eric-Joker** [MonwF/customiuizer#232]
如题，已选了scene但是最近任务里还是存在，用的是双列的那个形式

**Comment by MonwF** [comment]
看下桌面版，升级下

**Comment by Eric-Joker** [comment]
系统桌面RELEASE-4.39.6.5833-12301031 已经是最新版了。。。

**Comment by Eric-Joker** [comment]
> 4.39.9试下

貌似机型老，官方商店没有这个版本

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/11310077/app.zip)
