### ISSUE TITLE
Apps Notification Icons to the right

### ISSUE THREAD

**Issue by 3zozHashim** [MonwF/customiuizer#237]
It would be marvelous, if a feature was added to send selected apps notification icons to the right.

for example, apps that are always on like adguard/battery guru

![Screenshot_2023-04-02-07-00-34-993_com android chrome-edit](https://user-images.githubusercontent.com/115328790/229332343-6a0b7ea2-d1c0-4eed-acb0-5377163a8363.jpg)

**Comment by MonwF** [comment]
hard to move some notify icons to right only
