### ISSUE TITLE
Vibration on success not working [MIUI14-Android 12]

### ISSUE THREAD

**Issue by Gausak** [MonwF/customiuizer#239]
The function indicated in the title does not work on a POCO X5 Pro with MIUI.EU 14.0.6.0. Android 12.

No vibration on failure woks great, but vibration on success not working. It is a useful function for people with problems of accessibility. 

![Screenshot_2023-04-02-22-15-48-515_name monwf customiuizer](https://user-images.githubusercontent.com/126968957/229376891-353a08ce-bf90-4e77-9293-f0c291657c8d.jpg)

**Comment by Gausak** [comment]
Works on Miui 14 Android 13, but not on Miui 14 Android 12. 

Is there a way to make it work on MIUI14/android 12? android version 13 has problems on my device... thanks in advance.

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/11310335/app.zip)

**Comment by Gausak** [comment]
It works perfect! Thank you very much for your great work

**Comment by Gausak** [comment]
EDIT: Now the vibration works correctly when putting the fingerprint, but there are times when even if it vibrates and the screen turns on as if it had unlocked, it does not exit the lock screen and I have to put the fingerprint again

**Comment by MonwF** [comment]
> EDIT: Now the vibration works correctly when putting the fingerprint, but there are times when even if it vibrates and the screen turns on as if it had unlocked, it does not exit the lock screen and I have to put the fingerprint again

sorry. i just add vibrate action and did nothing
