### ISSUE TITLE
[Feature Request] Android stock icons switcher for notifications

### ISSUE THREAD

**Issue by infecti0N-113** [MonwF/customiuizer#241]
![IMG_20230405_024021](https://user-images.githubusercontent.com/23217089/229915448-0dbd34ad-f34c-4734-bc3e-e4bee91255bb.jpg)

It would be nice to have this switch to android stock. =)

**Comment by MonwF** [comment]
keep using this module?

**Comment by infecti0N-113** [comment]
I don't need another one, there may be an error in the translation ..  =)
