### ISSUE TITLE
Add SDK 30 as min SDK level.

### ISSUE THREAD

**Issue by UniverseCodex01** [MonwF/customiuizer#243]
Can you add APK support for a11, with a waring message of unsupported version and  not responsibility if device gets problems.
Because a lot of features modify system UI and a11 has miui 13, probably some features can work, like official customiuizer with a11.

**Comment by MonwF** [comment]
no. someone did the job last year.

**Comment by UniverseCodex01** [comment]
> no. someone did the job last year. 
Who? Can you share project name or link?

**Comment by MonwF** [comment]
in some issue
