### ISSUE TITLE
[Feature Request] Add option modify clock and date in notification drawer. 

### ISSUE THREAD

**Issue by c6-dark** [MonwF/customiuizer#246]
Add option modify size, style and format, margin etc of clock and date in notification drawer. 

![IMG_20230409_030000](https://user-images.githubusercontent.com/124439140/230743379-d22a9091-99a4-44d9-a2ff-0deb6d7bd0c7.jpg)

![IMG_20230409_030057](https://user-images.githubusercontent.com/124439140/230743400-48470bd2-3e46-415c-b948-71e5fbf9a463.jpg)

**Comment by MonwF** [comment]
not planned

**Comment by c6-dark** [comment]
In addition to this feature request, if possible, please add option to increase volume steps to 25 or 30. 

Thank you for your work. Love this mod
