### ISSUE TITLE
[ add new function request ] long screenshot, scroll screenshot

### ISSUE THREAD

**Issue by masshuvo** [MonwF/customiuizer#253]
If you take a screenshot in many places, it can be a long screenshot. But there are some software where if you want to take a long screenshot, that option is disabled and does not allow you to take a long screenshot.I think a new function can be added where any software can take long screenshots.

**Comment by MonwF** [comment]
![image](https://user-images.githubusercontent.com/1267050/231325965-9d20aa6c-78fb-4527-b68a-30596650ef65.png)

you can take long screenshoot from chrome action menu
