### ISSUE TITLE
关于输入法全面屏优化

### ISSUE THREAD

**Issue by 00XM01** [MonwF/customiuizer#254]
![IMG_20230412_154327.jpg](https://user-images.githubusercontent.com/84411809/231387919-7164e63b-6168-4c94-938c-99ad387b59ce.jpg)

问一下作者大大，能不能用同样的方法修复一下开启小白条沉浸后，全面屏键盘优化底部抬高的问题🥺

**Comment by MonwF** [comment]
什么意思？你怎么隐藏的小白条

**Comment by 00XM01** [comment]
> 什么意思？你怎么隐藏的小白条

我想说的是

已知，开启“隐藏导航栏”后，全面屏键盘优化会有异常抬高，然后再打开下方“修复键盘异常”可以解决抬高问题

通过模块或者主题打开小白条沉浸后，全面屏键盘优化也会有异常抬高，感觉可以用类似的方法修复这个问题🤔

**Comment by MonwF** [comment]
你可以将代码稍微修改下，伪装成隐藏了小白条。米客不会提供对这种场景的支持
