### ISSUE TITLE
Increase font size up to 18 in clock settings in status bar

### ISSUE THREAD

**Issue by andrea-musci** [MonwF/customiuizer#257]
Hi,
please raise the maximum font size of System > Status bar > Clock settings up to 18 for people with high dpi.
Thx

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/11218373/app.zip)

**Comment by andrea-musci** [comment]
> [app.zip](https://github.com/MonwF/customiuizer/files/11218373/app.zip)

Thank you, but it seems to have no effect. I tried both 18 and 20 but it's same heigth. Any idea?

**Comment by MonwF** [comment]
clock in dual rows?

**Comment by andrea-musci** [comment]
> clock in dual rows?

Yup

**Comment by MonwF** [comment]
max size is 10.5 in dual rows

**Comment by andrea-musci** [comment]
> max size is 10.5 in dual rows

Well, if it's possible to remove this limit, I can try it out. I used to have dual row set to 18 with another lsposed plugin and it looked good. It's possible that it wasn't actually 18 but definetely more than 10.5.
Anyway, don't want to force anyone. If you think it's possible to remove or increase the limit, it would be nice.

**Comment by MonwF** [comment]
few people want to set size larger than 11 . but many people set by mistake. they can only see one row and report bug. so i add the limit. maybe i will remove the limit later
