### ISSUE TITLE
[bug] volume percentage

### ISSUE THREAD

**Issue by MMETMA** [MonwF/customiuizer#258]
Here's a video of how it woks https://mirror.bot66.workers.dev/0:/InShot_20230413_023729441.mp4?a=view
- it counts 30 steps even though they're only 15
- it doesn't show 0 (most of the time) even if it is 0 it shows 1 instead 
- when adjusting the volume using the touch screen (not the volume buttons) it shows like 300 steps
- it'd be better if it shows the percentage instead
- when i saw that line in the changelog i thought it would be something like this 👇 ([the percentage on the slider itself](https://github.com/Corvus-AOSP/android_frameworks_base/commit/e3f3e82383a03341207041e77270f340d062631d) )
![IMG_20230413_024154_376](https://user-images.githubusercontent.com/79155572/231619438-2549c5b3-3b3b-4f83-9b22-805094a94447.jpg)

Poco f3 
Xiaomi.eu 14.0.22.4.2 dev

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/11218375/app.zip)

it shows percentage now and 0 instead of 1

**Comment by MMETMA** [comment]
> [app.zip](https://github.com/MonwF/customiuizer/files/11218375/app.zip)
> 
> it shows percentage now and 0 instead of 1

Way better now thanks

![Screenshot_2023-04-13-07-55-34-786_com android chrome](https://user-images.githubusercontent.com/79155572/231666537-177beb21-dec9-4010-bb79-bfbbd23eab03.png)
