### ISSUE TITLE
启动器中的“解锁网格大小”在mix fold 2中工作异常

### ISSUE THREAD

**Issue by chenxiccc** [MonwF/customiuizer#26]
开启该开关后，在mix fold 2(miui fold 13.1.16)中，桌面变成了3*3显示，且桌面设置中未出现网格选项（比如5*6）

**Comment by MonwF** [comment]
> 开启该开关后，在mix fold 2(miui fold 13.1.16)中，桌面变成了3_3显示，且桌面设置中未出现网格选项（比如5_6）

折叠屏比较特殊，本身就隐藏了布局规则选项吧。miui 启动器版本提供下 有空会看 不定解决 没法测试

**Comment by chenxiccc** [comment]
系统桌面版本：RELEASE-4.38.0.5316-08021631
谢谢~

**Comment by chenxiccc** [comment]
> 折叠屏比较特殊，本身就隐藏了布局规则选项吧

是的，桌面设置中没有布局规则选项。只能使用系统默认的4*6.

**Comment by MonwF** [comment]
> 系统桌面版本：RELEASE-4.38.0.5316-08021631 谢谢~

测试下，先把菜单放出来了

[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9625334/app-release.apk.zip)

**Comment by chenxiccc** [comment]
大佬牛逼！
经测试，菜单出来了，并且更改后正常生效！
![Screenshot_2022-09-23-11-47-47-457-edit_com miui home](https://user-images.githubusercontent.com/1096853/191889102-f6061808-cf33-4628-87a3-49cfabebbee3.jpg)
![Screenshot_2022-09-23-11-48-03-298_com miui home](https://user-images.githubusercontent.com/1096853/191889112-e23134d9-55ac-48de-9cc7-15fe4cc01020.jpg)

**Comment by chenxiccc** [comment]
测试发现的问题：
从4×6调整为5×6后，调整完图标。重启后，桌面虽然仍保持5×6排列，但最右侧的图标又都被移动到后面一屏去了。
看起来就像重启后先应用了4×6的排列，（所以最右侧的图标被搬走了，之后模块起作用改成了5×6，但没有把搬走的图标移动回来。
即重启后从图一变成了图二。
![Screenshot_2022-09-23-13-55-04-967_com miui home](https://user-images.githubusercontent.com/1096853/191900095-7594d8a9-7ddf-45fa-9ab5-66e8f86393fe.jpg)
![Screenshot_2022-09-23-13-54-02-414_com miui home](https://user-images.githubusercontent.com/1096853/191900108-b78d4e3b-2b02-4ea9-92ec-3d66e4cc5024.jpg)

**Comment by MonwF** [comment]
> 测试发现的问题： 从4×6调整为5×6后，调整完图标。此时一切正常。 但，当手机重启后，桌面虽然仍保持5×6排列，但最右侧的图标又都被移动到后面一屏去了。 看起来就像重启后先应用了4×6的排列，（所以最右侧的图标被搬走了，之后模块起作用改成了5×6，但没有把搬走的图标移动回来。

这个不好测试，没机器，暂时不会看了

**Comment by chenxiccc** [comment]
> > 测试发现的问题： 从4×6调整为5×6后，调整完图标。此时一切正常。 但，当手机重启后，桌面虽然仍保持5×6排列，但最右侧的图标又都被移动到后面一屏去了。 看起来就像重启后先应用了4×6的排列，（所以最右侧的图标被搬走了，之后模块起作用改成了5×6，但没有把搬走的图标移动回来。
> 
> 这个不好测试，没机器，暂时不会看了

sad。当你想搞了，我可以协助测试。

**Comment by MonwF** [comment]
> > > 测试发现的问题： 从4×6调整为5×6后，调整完图标。此时一切正常。 但，当手机重启后，桌面虽然仍保持5×6排列，但最右侧的图标又都被移动到后面一屏去了。 看起来就像重启后先应用了4×6的排列，（所以最右侧的图标被搬走了，之后模块起作用改成了5×6，但没有把搬走的图标移动回来。
> > 
> > 
> > 这个不好测试，没机器，暂时不会看了
> 
> sad。当你想搞了，我可以协助测试。

协助测试太麻烦了，目前自用为主。你可以先看下有没其他模块

**Comment by chenxiccc** [comment]
经过测试，MIUIHOMER模块
https://github.com/Xposed-Modules-Repo/com.yuk.miuihomer
这个模块，打开“解锁桌面布局限制”后，虽然桌面选项中没有出现“桌面布局规则”的选项，但桌面还是自动变成了5×6的排列，且重启后不会重拍图标。
供参考。

**Comment by chenxiccc** [comment]
试出来了，要以一种很奇怪的姿势来配合使用这两个模块。
1 先通过您的模块解锁桌面布局规则菜单，重启桌面，在桌面布局规则中选择5×6。
2 关闭您的模块中的解锁桌面布局菜单，重启桌面，此时桌面恢复为了4×6，不用管他。
3 在MiuihomeR模块中，打开 解锁桌面布局限制 ，重启桌面，发现桌面变回了5×6布局。（虽然桌面设置中没有出现桌面布局规则菜单）
4 重启也不会失效，不会重排图标

**Comment by chenxiccc** [comment]
还有一个信息补充：
只使用您的模块，解锁桌面布局菜单后，设置为5×6后，使用您的模块中的重启桌面功能，桌面布局都会恢复为4×6，桌面设置中的选项也会恢复为4×6，看起来就像系统没有保存设置一样。

**Comment by MonwF** [comment]
> 还有一个信息补充： 只使用您的模块，解锁桌面布局菜单后，设置为5×6后，使用您的模块中的重启桌面功能，桌面布局都会恢复为4×6，桌面设置中的选项也会恢复为4×6，看起来就像系统没有保存设置一样。

没看出代码和它有什么区别 发tg号给我邮件 方便点
