### ISSUE TITLE
请截图时屏蔽下方导航栏

### ISSUE THREAD

**Issue by razilong** [MonwF/customiuizer#269]
米客已有截图时屏蔽状态栏的功能，保护隐私
希望能识别并屏蔽下方导航栏，防止被别有用心者直接暴力区分截图主人是全面屏手势使用者还是导航三键使用者，防社工开盒，保护隐私(因为导航是人的强固定习惯)。
如果能直接裁去状态栏导航栏而不是现在的留白，方为最佳。
![Screenshot_2023-04-23-01-33-36-957-edit_com miui home](https://user-images.githubusercontent.com/97635957/233798895-fef7f1be-4d10-47ab-b9a7-5e09611ca328.jpg)

**Comment by MonwF** [comment]
分辨率也是指纹之一，这种社工也太夸张了。。。先自己裁剪吧

**Comment by MonwF** [comment]
隐藏导航栏本身非常简单，只是相对状态栏，它包含的可暴露信息太少。隐藏功能受众也不多

**Comment by MonwF** [comment]
添加了

**Comment by MonwF** [comment]
小窗不是隐藏叠加层的范围，而且不需要把app加入作用域，米客绝大部分功能不需要将第3方app加入作用域，除非描述中有明确说明。
另外的问题a12暂时无设备测试

**Comment by MonwF** [comment]
音量下键双击需要在系统设置中为其分配1个动作
