### ISSUE TITLE
【新功能请求】可以强制开启应用支持分屏

### ISSUE THREAD

**Issue by chenxiccc** [MonwF/customiuizer#27]
【新功能请求】可以强制开启应用支持分屏
一些软件，如斗鱼，不允许进行分屏。期望可以解除这个限制，允许所有应用支持分屏。
<img width="382" alt="image" src="https://user-images.githubusercontent.com/1096853/191702399-da6f0bed-0510-4465-88a8-d9ba0f8a1ec0.png">

**Comment by MonwF** [comment]
不是这些，分屏是多窗口

**Comment by chenxiccc** [comment]
开发者选项中关于多窗口的只找到这个。这个也是打开了的。但对斗鱼无效，斗鱼仍然不让分屏。
<img width="371" alt="image" src="https://user-images.githubusercontent.com/1096853/191994454-1b8cb87b-a494-4a33-90ca-7686289da632.png">

**Comment by MonwF** [comment]
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9643223/app-release.apk.zip)

试下，我这边测试斗鱼没问题了(打开customiuizer里的多窗口开关) @chenxiccc

**Comment by chenxiccc** [comment]
测试通过，谢谢大佬~
![Screenshot_2022-09-26-15-44-14-415_name.monwf.customiuizer.jpg](https://user-images.githubusercontent.com/1096853/192221722-83263ec1-6af6-4b53-8600-9f2cf8b34852.jpg)

![Screenshot_2022-09-26-15-48-10-289_com.miui.home.jpg](https://user-images.githubusercontent.com/1096853/192221791-93998f48-cc1d-4d02-8d6a-4e1dae27f26c.jpg)
