### ISSUE TITLE
Power menu is not in Japanese.

### ISSUE THREAD

**Issue by reindex-ot** [MonwF/customiuizer#271]
I added a Japanese translation of the Power menu, but it is not in Japanese. Is it a bug?
![Screenshot_2023-04-24-15-36-08-868_name monwf customiuizer](https://user-images.githubusercontent.com/32851879/233917741-8420005b-2524-4bae-9b32-2e29027fb36d.jpg)
![Screenshot_2023-04-24-15-36-13-528_name monwf customiuizer](https://user-images.githubusercontent.com/32851879/233917772-ab250f5b-7c98-40d3-9192-818407eef076.jpg)

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/11310553/app.zip)
