### ISSUE TITLE
Blank Space Under Enhaced Keyboard

### ISSUE THREAD

**Issue by itspdp** [MonwF/customiuizer#274]
When we turn on Enhaced Keyboard from Device Settings, It add a Blank space under the enhaced Keyboard.

**Comment by itspdp** [comment]
Yes, it goes away when I turn off customiuizer.

Btw-
Miui 14.0.3, A12, Redmi K20 Pro

**Comment by MonwF** [comment]
hide nav bar?

**Comment by itspdp** [comment]
Yes I have disabled (hide) the Gesture Pill from system settings.

**Comment by itspdp** [comment]
![Screenshot_2023-04-27-20-01-30-970_com.reddit.frontpage.jpg](https://user-images.githubusercontent.com/44732170/234895693-0edba013-2d7a-4f78-a65c-03d688ce5d31.jpg)

**Comment by MonwF** [comment]
nav to control - navbar, and screenshot

**Comment by itspdp** [comment]
Nope, it's blank space showing whatever in background image/anything.
(In SS it's black because of black background)
