### ISSUE TITLE
Google keyboard padding doesn't work

### ISSUE THREAD

**Issue by Plank99** [MonwF/customiuizer#276]
Google keyboard bottom padding doesn't seem to function on MIUI 14 (XIAOMI EU ROM).

**Comment by MonwF** [comment]
add it to lsposed scope

**Comment by Plank99** [comment]
My bad. After adding to lsposed and restarting works flawlessly. Thank you!

**Comment by Plank99** [comment]
My bad. After adding to lsposed and restarting works flawlessly. Thank you!
