### ISSUE TITLE
[问题反馈]强制让应用支持从通知中心长按下拉后打开小窗不生效

### ISSUE THREAD

**Issue by chenxiccc** [MonwF/customiuizer#28]
我打开了 系统-浮动窗口-禁用黑名单  和  系统-弹窗通知-允许浮窗，并把淘宝后的绿色对号点亮。
但并不起作用，比如淘宝的物流通知，长按通知并未出现小横条，也无法下拉在小窗打开。

设备: Mi Mix Fold 2
系统:Miui fold 13.1.16

<img width="383" alt="image" src="https://user-images.githubusercontent.com/1096853/191961433-9a80adb7-96d9-4fe5-a10f-492bf71d4fef.png">

<img width="385" alt="image" src="https://user-images.githubusercontent.com/1096853/191962713-52089148-cd58-46db-966b-98e7525cb604.png">

![Screenshot_2022-09-23-14-23-59-255_name monwf customiuizer](https://user-images.githubusercontent.com/1096853/191903157-788ec01e-33f8-45fe-bfc6-fc87c87cf52d.jpg)
![Screenshot_2022-09-23-14-19-09-906_com xunmeng pinduoduo](https://user-images.githubusercontent.com/1096853/191903167-014e04eb-173c-4d6f-96d1-97598dfa2a4c.jpg)

**Comment by MonwF** [comment]
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9643447/app-release.apk.zip)

**Comment by chenxiccc** [comment]
> [app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9643447/app-release.apk.zip)
> 
> @chenxiccc 
> 

这个与 #27 中包的迭代版吗，是否这个包同时解决了 #27 与 该issue中的两个问题？
还是要分别安装测试？

**Comment by chenxiccc** [comment]
测试大部分通过。
但出现过一次淘宝卖家信息在通知栏长按没出现下拉小白条。
无法规律复现。
![Screenshot_2022-09-26-15-37-25-151_com.miui.home.jpg](https://user-images.githubusercontent.com/1096853/192219774-a563e08d-3e6e-4bd5-a45f-dedb54fe674d.jpg)

**Comment by MonwF** [comment]
> > [app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9643447/app-release.apk.zip)
> > @chenxiccc
> 
> 这个 #27 中提供的测试包的迭代版吗，是否这个包同时解决了 #27 与 该issue中的两个问题？ 还是要分别安装测试？

应该包含了，测试下吧。看哪个文件后上传的，没搞单独分支

**Comment by MonwF** [comment]
> 测试大部分通过。 但出现过一次淘宝卖家信息在通知栏长按没出现下拉小白条。 无法规律复现。 ![Screenshot_2022-09-26-15-37-25-151_com.miui.home.jpg](https://user-images.githubusercontent.com/1096853/192219774-a563e08d-3e6e-4bd5-a45f-dedb54fe674d.jpg)

如果通知的应用已经是最顶层应用，就不会出现进入小窗了

**Comment by chenxiccc** [comment]
> > > [app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9643447/app-release.apk.zip)
> > > @chenxiccc
> > 
> > 这个 #27 中提供的测试包的迭代版吗，是否这个包同时解决了 #27 与 该issue中的两个问题？ 还是要分别安装测试？
> 
> 应该包含了，测试下吧。看哪个文件后上传的，没搞单独分支

这个包确实都包含了。完美

**Comment by MonwF** [comment]
收到，后续有空再修复，现在只是移除了黑名单。这里miui应该本身实现就有bug

**Comment by chenxiccc** [comment]
> 收到，后续有空再修复，现在只是移除了黑名单。这里miui应该本身实现就有bug

确实。
测试了系统原生支持系统小窗的软件。
钉钉可以复现这个bug，而微信一切正常？

**Comment by MonwF** [comment]
> > 收到，后续有空再修复，现在只是移除了黑名单。这里miui应该本身实现就有bug
> 
> 确实。 测试了系统原生支持系统小窗的软件。 钉钉可以复现这个bug，而微信一切正常？

看代码，微信这里特殊处理了
