### ISSUE TITLE
"Open notification in floating window"

### ISSUE THREAD

**Issue by trinhloivn** [MonwF/customiuizer#281]
On lastest [v23.05.03] ver 
"Open notification in floating window" dont work some time
notification cann't open in float it open full screen app
Need reboot open customiui app
Pre-ver it work normal
I back old ver and it not happen

**Comment by MonwF** [comment]
read the changelog

**Comment by trinhloivn** [comment]
> read the changelog

Sorry my bad. "open notification in fullscreen window on homescreen or notification is from top package"
But i want Open notification only in floating window
I can do that?
Or not?
Thank for rep

**Comment by MonwF** [comment]
no. check the option 'remember state'

**Comment by trinhloivn** [comment]
> 

Sad,can u add option to  do that.hope...
I only want *Open notification all app only in floating window*
back to old ver can help
Thanks for help

**Comment by trinhloivn** [comment]
> no. check the option 'remember state'

Sad,can u add option to do that.hope...
I only want Open notification all app only in floating window
back to old ver can help
Thanks for help
