### ISSUE TITLE
Bug: Notification volume slider doesn't appear in expanded volume dialog

### ISSUE THREAD

**Issue by c6-dark** [MonwF/customiuizer#283]
Below is the image with notification volume slider toggle off.

![Screenshot_2023-05-06-19-51-30-793_name monwf customiuizer](https://user-images.githubusercontent.com/124439140/236629962-e5ebd617-ef3e-4072-836c-89e07b0a0a9e.jpg)

Below is the image with notification volume slider toggle on.

![Screenshot_2023-05-06-19-51-09-060_name monwf customiuizer](https://user-images.githubusercontent.com/124439140/236630003-40e91506-74bd-455a-9641-004287486005.jpg)

I am using Miui 14, Mi 11 ultra,  xiaomi.eu rom

**Comment by c6-dark** [comment]
Also If it's not too much to ask for a feature request, please increase the volume steps to 25 or more if possible.

**Comment by MonwF** [comment]
miui will add notification volume soon. so the hook is broken. i will not fix it
volume steps may be add
