### ISSUE TITLE
(Feature request) statusbar long press vibrate

### ISSUE THREAD

**Issue by NC503** [MonwF/customiuizer#288]
Hi bro. Can you add a vibration for statusbar long press shortcut? When shortcut executed, the vibration comes . So we know the shortcut executed

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/11881366/app-develop.zip)
try this build. turn on vibrate in settings app and toggle the option in customiuizer14
