### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by ammlr** [MonwF/customiuizer#3]
add remove untrusted touch (like chimi/woobox)

and I want to ask, why is this application closed source? I suggest open source

**Comment by MonwF** [comment]
this is an open-source mod

**Comment by ammlr** [comment]
![Screenshot_2022-07-01-01-53-07-516_com.lt2333.simplicitytools.jpg](https://user-images.githubusercontent.com/30746607/176756121-3657b46f-94ba-49fb-af13-bce94d943a1f.jpg)

please add this feature

because the customiuizer is not complete, I have to use woobox too

**Comment by ammlr** [comment]
![Screenshot_2022-07-01-01-53-07-516_com.lt2333.simplicitytools.jpg](https://user-images.githubusercontent.com/30746607/176756121-3657b46f-94ba-49fb-af13-bce94d943a1f.jpg)

please add this feature

because the customiuizer is not complete, I have to use woobox too

**Comment by ammlr** [comment]
![Screenshot_2022-07-01-01-56-45-915_com.lt2333.simplicitytools.jpg](https://user-images.githubusercontent.com/30746607/176756567-055e97b5-8993-41e8-ad10-f248938281b5.jpg)

"allow untrusted touch" also not found in customiuizer

**Comment by MonwF** [comment]
adb shell settings put global block_untrusted_touches 0
