### ISSUE TITLE
大佬，能不能加一个接触MIUI13官方降亮度的功能

### ISSUE THREAD

**Issue by k650dg4d2** [MonwF/customiuizer#30]
![Screenshot_2022-09-27-13-47-56-389-edit_chili xposed chimi](https://user-images.githubusercontent.com/32454224/192443401-4fcdc822-96f3-466f-aca9-ba4462922c8c.jpg)
就这个，在没有开启自动亮度的情况下，打开微信QQ屏幕亮度会自动下降

**Comment by MonwF** [comment]
就用chimi，挺好的啊，近期应该不会新增

**Comment by k650dg4d2** [comment]
> 就用chimi，挺好的啊，近期应该不会新增

听说痴迷有点费电，用两个不如一个好。暂时用chimi也行

**Comment by MonwF** [comment]
> > 就用chimi，挺好的啊，近期应该不会新增
> 
> 听说痴迷有点费电，用两个不如一个好。暂时用chimi也行

功能不开启 一般不费电
