### ISSUE TITLE
[Suggestion] Notification center at left

### ISSUE THREAD

**Issue by dranivil** [MonwF/customiuizer#300]
When we enable the function of using the notification control, change the side to go down and show it.  The top left for notification control and the top right for notifications.

**Comment by MonwF** [comment]
you can get this option in system - control center

**Comment by dranivil** [comment]
Nop, this function does not exist in system - control center

**Comment by MonwF** [comment]
i remember that it is visible on chinese rom only

**Comment by dranivil** [comment]
Can it be added in the global rom with customiuizer?

**Comment by MonwF** [comment]
no. i dont have device with global rom
