### ISSUE TITLE
一个疑似天玑机型的bug

### ISSUE THREAD

**Issue by ArtifactYu** [MonwF/customiuizer#301]
![Screenshot_2023-05-25-17-33-47-706-edit_name.monwf.customiuizer.jpg](https://github.com/MonwF/customiuizer/assets/108167445/0ddec61e-2482-46c7-9a11-7c53069a4ae8)

![Screenshot_2023-05-25-17-34-11-841-edit_flar2.exkernelmanager.jpg](https://github.com/MonwF/customiuizer/assets/108167445/02525636-9cd2-43d2-9ca4-5b17763eee19)

如图，这里的显示cpu温度似乎是用的电池温度，但实际上的cpu温度已经有50度了，机型k30u，处理器天玑1000+，系统MIUI14.0.1，而在我的高通机型上显示是正常的。

**Comment by MonwF** [comment]
某些机型读取cpu 温度还待优化

**Comment by MonwF** [comment]
试最新的hyperos
