### ISSUE TITLE
Add option to merge network and wifi signal icon

### ISSUE THREAD

**Issue by g0b1yn** [MonwF/customiuizer#304]
Hi,

It would be great if you could add an option to merge network and wifi signal same as AOSP Android 13.

**Comment by MonwF** [comment]
can you explain more? or give some pictures

**Comment by MmyGgithubAaccount** [comment]
I think they mean that mobile signal icons will be hidden when connected to the internet through wifi network, and wifi icon will be hidden when connected to the internet through mobile data
Separate icons
![E8_aDwaUcAkdJg8](https://github.com/MonwF/customiuizer/assets/58236619/635c33e0-e940-4aab-a14d-5f8288211f4b)

Combined icon (mobile signal bars hidden)
![E8_aEADUUAAeoUN](https://github.com/MonwF/customiuizer/assets/58236619/39d4defa-c6aa-4b50-9d7b-cf2865120dbb)

Here's the implementation in aospmods (a module similar to customiuizer, but for aosp)
https://github.com/siavash79/AOSPMods/blob/c2b73a6009e885362f387c780ad281e512ac7504/app/src/main/java/sh/siava/AOSPMods/modpacks/systemui/StatusbarMods.java#LL1238C15-L1238C33

**Comment by MonwF** [comment]
ok.i will add it later

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/11683328/app-develop.zip)

system - status bar - hide icons

@MmyGgithubAaccount
