### ISSUE TITLE
Mod unlocking 90 fps for screen recorder doesn't work

### ISSUE THREAD

**Issue by HuyMaster** [MonwF/customiuizer#307]
![Screenshot_2023-06-04-18-41-44-044_com.miui.screenrecorder.png](https://github.com/MonwF/customiuizer/assets/80255843/28c46e0f-dd90-4235-893e-0aef6c7d94cf)

MiUI 14 [T]

**Comment by MonwF** [comment]
miui global rom?

**Comment by HuyMaster** [comment]
> miui global rom?

Yes

**Comment by MonwF** [comment]
see https://github.com/MonwF/customiuizer/issues/204

**Comment by HuyMaster** [comment]
> see https://github.com/MonwF/customiuizer/issues/204

Before, I could still use it
