### ISSUE TITLE
[Feature] 米客有机会实现这些 Idea 吗

### ISSUE THREAD

**Issue by IlIllIl** [MonwF/customiuizer#309]
如果Cemiuier他们不打算做的话，大佬可以考虑实现一部分功能吗？
- https://github.com/Cemiuiler-Development-Team/Cemiuiler/issues/90
- https://github.com/Cemiuiler-Development-Team/Cemiuiler/issues/170
- https://github.com/Cemiuiler-Development-Team/Cemiuiler/issues/95
- https://github.com/Cemiuiler-Development-Team/Cemiuiler/issues/94
- https://github.com/Cemiuiler-Development-Team/Cemiuiler/issues/91

（虽然目前我还只会提建议，等我有机会学习了一定回来贡献代码的

**Comment by MonwF** [comment]
等cemiuiler实现吧，有些单独模块已经有了，集成到customiuizer优先级不高
