### ISSUE TITLE
suggestion for floating windows

### ISSUE THREAD

**Issue by MMETMA** [MonwF/customiuizer#311]
![Screenshot_2023-06-10-17-40-38-800_name monwf customiuizer-edit](https://github.com/MonwF/customiuizer/assets/79155572/2ecbc535-4375-40bb-ab2c-5419a442872f)

add option to enable this for listed apps only

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/11740829/app.zip)
