### ISSUE TITLE
[FEATURE REQUEST] DOUBLE TAP WAKE UP SCREEN.

### ISSUE THREAD

**Issue by guillermorojaz** [MonwF/customiuizer#318]
Could you add to the functions the double touch to force the wake up or turn on the screen? I know that it is present in Miui, like double tap to sleep. In the rom that I carry, the double tap or wake function tends to fail after a reboot or power on of the device, I correct it by deactivating it and reactivating it to make it work again. I'm sure your module would force this function to work correctly!  I hope you can take my request and add it to your module.  Thank you for your excellent work.

**Comment by MonwF** [comment]
this feature is included in miui system
