### ISSUE TITLE
[suggestion] Option to change the gradient orientation for the status bar clock bg

### ISSUE THREAD

**Issue by MMETMA** [MonwF/customiuizer#326]
Option to change the gradient orientation from LEFT_RIGHT

![IMG_20230708_213030](https://github.com/MonwF/customiuizer/assets/79155572/280c7313-44af-4062-9abd-d32ba593a371)

To TOP_BOTTOM

![IMG_20230708_213016](https://github.com/MonwF/customiuizer/assets/79155572/83014404-bac7-4d6e-b5d3-d9613612a1ef)

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/12010573/app.zip)
