### ISSUE TITLE
希望增加的几个功能

### ISSUE THREAD

**Issue by Cxy-2008** [MonwF/customiuizer#328]
1.可以在中孔屏和侧孔屏增加环状电量环或有通知、电话时环状泛红闪烁
2.MIUI倒数日精确到秒 不像是只有日期 特别是桌面组件
3.天气小组件可以显示更多信息 例如：湿度 PM2.5等
4.在WiFi界面 在每个WiFi的下方添加IP 技术标准等
以上就是我提的一些建议
祝
米客越做越好！

**Comment by MonwF** [comment]
1. 环形电量可能加。但闪烁应该加不来
2和3不会加
4. 标准应该显示了，但ip没连接的情况下没法显示

**Comment by Cxy-2008** [comment]
能否添加MIUI控制中心图标颜色自定义功能？

**Comment by xiaocenter** [comment]
建议加上去除ota验证  以及防止生成xldownload文件夹

**Comment by MonwF** [comment]
> 能否添加MIUI控制中心图标颜色自定义功能？

这个已经添加

**Comment by MonwF** [comment]
> 建议加上去除ota验证 以及防止生成xldownload文件夹

这个不会添加，请用其他模块

**Comment by Cxy-2008** [comment]
> > 能否添加MIUI控制中心图标颜色自定义功能？
> 
> 这个已经添加

请问这个功能在哪里打开？

**Comment by MonwF** [comment]
> > > 能否添加MIUI控制中心图标颜色自定义功能？
> > 
> > 
> > 这个已经添加
> 
> 请问这个功能在哪里打开？

hyperos版已添加miui已停止维护

**Comment by Cxy-2008** [comment]
可以增加状态栏实时模糊吗？
