### ISSUE TITLE
Can you help me? Please!

### ISSUE THREAD

**Issue by UniverseCodex01** [MonwF/customiuizer#333]
I want to disable wallpaper rotation due to on A10 on landscape mode wallpaper goes to the top on poriant aspect ratio and genete a balck rectangle on the bottom or on the right position of the landscape screen. I want to disable wallpaper service rotation, I suppose that it's configured on framework.jar or services.jar because I didn't found an option on framework.apk and systemui.apk. my device uses systemui imageWallpaper as wallpaper provider. I know that it's not related to you and your work but maybe you can help me because I don't have knowledge about edition of smali and java.

Bug appears with the usage of 3rd party launchers, I'm using Smart launcher V6 but also appears on nova launcher and all other launchers.

![Screenshot_2023-07-21-08-33-39-793_ginlemon flowerfree](https://github.com/MonwF/customiuizer/assets/93066706/07552044-06a4-4ed0-a935-69d2c29d9f67)
![Screenshot_2023-07-21-08-34-14-073_ginlemon flowerfree](https://github.com/MonwF/customiuizer/assets/93066706/5b434824-71b3-4f96-8957-7ad666a2cdae)
![Screenshot_2023-07-21-08-34-19-338_ginlemon flowerfree](https://github.com/MonwF/customiuizer/assets/93066706/af1bc11a-65e4-4031-888d-79199a99b345)

**Comment by MonwF** [comment]
sorry. i don't think i can give you any help
