### ISSUE TITLE
Translation Fix for Turkish

### ISSUE THREAD

**Issue by prescionx** [MonwF/customiuizer#337]
The translator for turkish lang. must be a very lovely guy. He has added "Aşkım" (my love in eng) on every toggle switch.
Its nonsense. Imagine adding my love on everything. Hello my love. Thank you for tip my love. Can u give me a big McChicken my love. Here is your rifle my commander my love etc. pls fix it.

**Comment by MonwF** [comment]
https://crowdin.com/project/customiuizer14
