### ISSUE TITLE
Charging rate on lockscreen not updating frequently

### ISSUE THREAD

**Issue by chaoscreater** [MonwF/customiuizer#339]
I've enabled the setting to show charging rate on the lockscreen. This updates very slowly, whereas the charging rate on the status bar will update frequently. Not sure if this is a bug?

**Comment by MonwF** [comment]
no. it updates when battery level changed

**Comment by chaoscreater** [comment]
But why does the status bar update the charging rate frequently (every second)? It's not consistent.
