### ISSUE TITLE
Disable forced Dark mode still not work

### ISSUE THREAD

**Issue by Bladius2022** [MonwF/customiuizer#34]
Please repair option Disable forced Dark mode. Still not work

**Comment by MonwF** [comment]
this option has been deprecated. what is it for

**Comment by Bladius2022** [comment]
> 

This option is intended to disable the dark black theme in applications that display poorly in this forced mode.  There are applications such as APKCombo Installer that are not adapted to this mode

**Comment by MonwF** [comment]
Dark mode for individual apps list can be found in the system settings

**Comment by Bladius2022** [comment]
this option has not been working for a long time, it has been disabled by Xiaomi.  The list came out recently after the CustoMIUIzer13 update, but it's not working.  Applications do not respond to any setting.  The ones that are disabled by default have the black theme anyway

**Comment by MonwF** [comment]
> this option has not been working for a long time, it has been disabled by Xiaomi. The list came out recently after the CustoMIUIzer13 update, but it's not working. Applications do not respond to any setting. The ones that are disabled by default have the black theme anyway

it works on miui eu. I have checked it just now

**Comment by Bladius2022** [comment]
I have XIAOMI.EU ROM 13.0.10.0 and not work

**Comment by MonwF** [comment]
apkcombo installer has dark theme inside. when  i turn off force dark mode for it，dark theme displays poorly. but if i turned on force dark， dark theme displays much better instead

**Comment by MonwF** [comment]
try this build
[customiuizer13-1113-test.apk.zip](https://github.com/MonwF/customiuizer/files/9997391/customiuizer13-1113-test.apk.zip)

**Comment by Bladius2022** [comment]
Still nothing.  However, there was an error - the color background does not work, although the Disable color background option is turned off

**Comment by MonwF** [comment]
test another app except apkcombo installer. Any lsposed log? how the error looks like? show me the pic

**Comment by Bladius2022** [comment]
I checked many apps that don't have dark mode.  mBank, PeoPay, Biedronka, Recharge, McDonald's, Moje Carrefour, Agora Bytom, Microsoft Authenticator.  No error message whatsoever.  I don't know how to generate CustoMIUIzer13 log

**Comment by MonwF** [comment]
first you check the app（eg authenticator）in the system settings. then enable the option in customiuizer. restart system and follow these steps after reboot :
0 enable dark mode
1 open authenticator and screenshot. 
2 open system dark mode settings and screenshot

**Comment by MonwF** [comment]
> I checked many apps that don't have dark mode. mBank, PeoPay, Biedronka, Recharge, McDonald's, Mój Carrefour, Agora Bytom, Microsoft Authenticator. No error message whatsoever. I don't know how to generate CustoMIUIzer13 log

you dont need to check any apps at all. just enable option in customiuizer and reboot

**Comment by Bladius2022** [comment]
Still not work

**Comment by MonwF** [comment]
> Still not work

what does not work means? without any more info, i'll not reply any more

**Comment by Bladius2022** [comment]
This means that it doesn't matter how you set the switch, even restarting the system does not change anything in this regard.  Apps that should have forced dark mode turned off still show up in dark mode.

**Comment by MonwF** [comment]
> This means that it doesn't matter how you set the switch, even restarting the system does not change anything in this regard. Apps that should have forced dark mode turned off still show up in dark mode.

after restart， all apps are reset to turned off in system settings？

**Comment by Bladius2022** [comment]
It means that even restarting the system doesn't help.  The app that wants to disable the dark theme still has it.

**Comment by MonwF** [comment]
go into system dark settings and take screenshot

**Comment by Bladius2022** [comment]
I got a little lost and confused.  So take it easy again.  APKCombo Installer - you can't disable the dark mode enforcement here (even if it's inside, it will be activated by turning on the dark theme in the system).  However, applications that do not have a dark mode (those from the list) cannot be turned on for them forced dark mode (the switch in the system does not change anything)

**Comment by Bladius2022** [comment]
I got a little lost and confused.  So take it easy again.  APKCombo Installer - you can't disable the dark mode enforcement here (even if it's inside, it will be activated by turning on the dark theme in the system).  However, applications that do not have a dark mode (those from the list) cannot be turned on for them forced dark mode (the switch in the system does not change anything)

**Comment by MonwF** [comment]
> I got a little lost and confused. So take it easy again. APKCombo Installer - you can't disable the dark mode enforcement here (even if it's inside, it will be activated by turning on the dark theme in the system). However, applications that do not have a dark mode (those from the list) cannot be turned on for them forced dark mode (the switch in the system does not change anything)

apps from the list cant be turned on because of customiuizer. all apps are reset when you leave the settings activity. apkcombo installer has dark mode inside and has been set dark mode automatic itself. 
you just need to check if authenticator is not in darkmode

**Comment by Bladius2022** [comment]
the one from Microsoft, however, does not have a dark mode.  in MIUI 12.5 it was possible to force him and other applications to artificial dark mode.  in MIUI 13 first those toggles in the dark mode option are gone.  They came back after the update but they didn't change anything.  APKCombo does not have a switch to disable the built-in dark mode.  this can only be disabled by disabling dark mode on your system.  I would like CustoMIUIzer13 to block such applications from activating the dark theme after turning it on in the system, if the application itself does not have the appropriate switch

**Comment by MonwF** [comment]
no. the customiuizer option isn't intended to do such thing. in miui 13，only some apps can be able to turn on force dark mode。this is controlled by xiaomi. all other apps are keep untouched.
but in 12.5，all apps are forced to enable dark mode，so this option is meaningful.

maybe you should ask the apkcombo installer to add an option

**Comment by MonwF** [comment]
so customiuizer can only disable forcd dark from miui but not from app itself
