### ISSUE TITLE
SKIP REQUEST TO ADD PIN/PATTERN BEFORE ADDING FINGERPRINT

### ISSUE THREAD

**Issue by guillermorojaz** [MonwF/customiuizer#345]
Before adding a fingerprint, miui requires a pin or pattern to be added.  
Can this be omitted?  
add my fingerprints without adding an annoying pin or pattern!!! 
This annoying action also occurs for facial blocking.

**Comment by MonwF** [comment]
no. strong auth must be set

**Comment by guillermorojaz** [comment]
thanks for prompt response.  
And could you create evasion of pin or pattern request after turning on the device?
