### ISSUE TITLE
Not reading/passing the alarm after locking

### ISSUE THREAD

**Issue by jrotaetxe** [MonwF/customiuizer#346]
Hi, MonwF
Seems the app is passing correctly the alarm time when I change the time in the stock clock application in MIUI 14 (Android 12) in my 10T.
But if I lock and unlock, the hour comes with 1 hour substracted... Pretty weird.
No problem at all with this if you find does not deserve the effort. I stated, I am fully grateful with the app the way it is now.
Best regards

**Comment by jrotaetxe** [comment]
Seems the alarm compatibility is broken. No matter it is activated or not, the result is the same (as described later)

**Comment by MonwF** [comment]
set clock app as system app. a12 is discontinued. sorry
