### ISSUE TITLE
Status bar icons not showing

### ISSUE THREAD

**Issue by cherlis** [MonwF/customiuizer#348]
Status bar icons not showing.
Icons (alarm clock, mute, headphones, etc.) are not displayed when moving them to the right row.  This error exists on versions v23.08.26 and v23.06.27.

**Comment by MonwF** [comment]
take screenshot pls

**Comment by cherlis** [comment]
![Screenshot_2023-08-26-19-46-42-268_name monwf customiuizer](https://github.com/MonwF/customiuizer/assets/17528476/be27612b-38a9-4b7c-a20f-c6c3a960ca86)

**Comment by cherlis** [comment]
Updated version.  Also, the icons on the right do not appear.
![Screenshot_2023-08-27-12-25-13-090_com android chrome](https://github.com/MonwF/customiuizer/assets/17528476/8d92dd2f-e9dc-48d2-8e88-75af5a616f90)

**Comment by MonwF** [comment]
miui version and device model?

**Comment by cherlis** [comment]
A12, MIUI13. Redmi Note 10 Pro.
Previous versions did not have this error. Now I use v23.05.26. All OK.

**Comment by cherlis** [comment]
The update contains the same bugs
![Screenshot_2023-08-28-07-42-55-796_com android chrome](https://github.com/MonwF/customiuizer/assets/17528476/c1d76d88-76dc-4c78-8ed3-45de38becf9a)

**Comment by MonwF** [comment]
fixed. please redownload from lsp or github
