### ISSUE TITLE
Bluetooth and disable screen lock

### ISSUE THREAD

**Issue by Hydro8** [MonwF/customiuizer#35]
Hi
I try to use disable screen lock option. It work well with wifi but not with bluetooth.
No devices appear when I enter on the "trusted bluetooth devices". However, I'm connect to my car bluetooth at the same time.

Do you know this problem? 

I have a mi10 with xiaomi.eu 13.0.7 (android 12).

Thanks !

**Comment by MonwF** [comment]
> Hi I try to use disable screen lock option. It work well with wifi but not with bluetooth. No devices appear when I enter on the "trusted bluetooth devices". However, I'm connect to my car bluetooth at the same time.
> 
> Do you know this problem?
> 
> I have a mi10 with xiaomi.eu 13.0.7 (android 12).
> 
> Thanks !

restart systemui from app menu first and look at log in lsposed

**Comment by Hydro8** [comment]
Sorry I don't achieve to save logs. I took screenshots :

![Screenshot_2022-10-02-17-04-12-998_com android shell](https://user-images.githubusercontent.com/5537697/193461152-c0909c69-bc6a-4409-a6d0-010f1ca6cf19.jpg)
![Screenshot_2022-10-02-17-04-35-002_com android shell](https://user-images.githubusercontent.com/5537697/193461156-3381a71f-09e2-4579-8671-8f452462860f.jpg)

**Comment by MonwF** [comment]
customiuizer may be failed to grant permissions. check if hide apps list in launcher is broken too ?

**Comment by Hydro8** [comment]
Hide apps seems to work fine.

**Comment by MonwF** [comment]
get build 11.26 apk

https://github.com/MonwF/customiuizer/releases/tag/v22.11.24

**Comment by Hydro8** [comment]
Thanks it works great !
