### ISSUE TITLE
Cannot change the date format in control center 

### ISSUE THREAD

**Issue by kkao0** [MonwF/customiuizer#352]
In system > control center (控制中心) > customize date format (自定義日期格式).
No matter how I change the settings, e.g. yyyy年M月d日 E aa. It will only show the default one on my 
![Screenshot_2023-08-30-14-48-28-002_com microsoft emmx-edit](https://github.com/MonwF/customiuizer/assets/19405916/285c83c2-52bc-41c4-8975-e48e7e19ef02)
![Screenshot_2023-08-30-14-49-01-245_name monwf customiuizer-edit](https://github.com/MonwF/customiuizer/assets/19405916/0acf11b3-d51f-4aee-95c9-4a9a256ed41a)
Even I select hide date, the date will show the default one.

My phone is Xiaomi 12X, MIUI 14.0.9

**Comment by MonwF** [comment]
android 12? extract your systemui.apk

**Comment by kkao0** [comment]
> android 12? extract your systemui.apk

It is android 13.
Where can i find or extract the systemui.apk?
I cannot find the systemUI directory or apk in both /system/app/ or /system/priv-app/

**Comment by MonwF** [comment]
> > android 12? extract your systemui.apk
> 
> It is android 13. Where can i find or extract the systemui.apk? I cannot find the systemUI directory or apk in both /system/app/ or /system/priv-app/

/system_ext/priv-app/MiuiSystemUI/

**Comment by kkao0** [comment]
> android 12? extract your systemui.apk
MiuiSystemUI.apk 
https://drive.google.com/file/d/1QQP5VZ3GmMw8FPb-GYu2ZmhsnnUp776q/view?usp=drivesdk

**Comment by MonwF** [comment]
如果使用新的控制中心是否生效？

**Comment by kkao0** [comment]
新版控制中心生效，但切回舊版就不生效。以前用舊版的好像也能改。

**Comment by MonwF** [comment]
确实有问题，我是eu的rom所以ok，最近修复下.
你升级最新测试版没，现在只提供modern api的版本了，要求lsposed 1.9.1。先备份，升级后再恢复

**Comment by MonwF** [comment]
网盘下载 ，但日期这个还没修复

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/12695769/app-develop.zip)

已经修复。先备份，再安装，再恢复备份

**Comment by kkao0** [comment]
> [app-develop.zip](https://github.com/MonwF/customiuizer/files/12695769/app-develop.zip)
> 
> 已经修复。先备份，再安装，再恢复备份

謝謝
