### ISSUE TITLE
红米k60至尊版开启双排网速无效果

### ISSUE THREAD

**Issue by chs72** [MonwF/customiuizer#356]
红米k60至尊版开启双排网速无效果

**Comment by chs72** [comment]
> 新状态栏，别乱开 可能会无限重启

早就中招了，哈哈，问题不大，这个有计划修复吗

**Comment by MonwF** [comment]
等我的k50u支持才会修。现在网速默认值和单位双排，对温度 电流显示这些都有影响

**Comment by chs72** [comment]
> 等我的k50u支持才会修。现在网速默认值和单位双排，对温度 电流显示这些都有影响

好的，谢谢大大

**Comment by MonwF** [comment]
试下最新测试版 盲修的

**Comment by chs72** [comment]
已经测试过，正常。
