### ISSUE TITLE
[Feature Update] Increase control center number of rows to 10

### ISSUE THREAD

**Issue by mojienjoyment** [MonwF/customiuizer#357]
I use smaller DPI for my screen and I set number of rows for control center to 8, but I have more space until bottom of screen, so I think I can add 2 rows more to it.
![Screenshot_2023-09-11-20-03-15-557_com mi android globallauncher](https://github.com/MonwF/customiuizer/assets/68327458/7059b906-02db-4b7c-8ead-3c77da46ed52)
![Screenshot_2023-09-11-20-03-32-977_name monwf customiuizer](https://github.com/MonwF/customiuizer/assets/68327458/8279036a-3e46-4048-9c74-7ff93047e810)

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/12585240/app.zip)

**Comment by mojienjoyment** [comment]
It worked. I think 9 rows is good for my dpi (517 dp). 10 rows, make control center scrollable.
9 rows
![Screenshot_2023-09-13-09-39-05-385_name monwf customiuizer](https://github.com/MonwF/customiuizer/assets/68327458/5871c2a9-b7fb-4198-b19c-5aa149b0a5de)

10 rows screenrecorder
https://github.com/MonwF/customiuizer/assets/68327458/e513a512-6d51-49ae-8578-623c51aa00e7
