### ISSUE TITLE
No hidden folder option doesn't works

### ISSUE THREAD

**Issue by Birraque** [MonwF/customiuizer#358]
I'm currently testing your custoMIUIzer14 (test) latest version.
The option to "Disable two-finger gesture that opens
hidden apps folder and secret phone code
is 233233" only works if the custoMIUIzer app still opened when *#*#233233#*#* be dialled.

Device: Redmi K40, Poco F3, alioth
OS: Android 13, MIUI 14 (14.0.7.0)

Let me know if more inputs needed, regards

![IMG_20230915_011237](https://github.com/MonwF/customiuizer/assets/44372413/d20bedaf-4579-4918-9e1f-9eeeb4da9cfd)

**Comment by MonwF** [comment]
yes. customiuizer must be running

**Comment by Birraque** [comment]
> yes. customiuizer must be running

It's already be running in background but also needs to be opened otherwise nothing happens when dial the default secret password.

**Comment by MonwF** [comment]
if it's be opened, how to dial?

**Comment by Birraque** [comment]
> if it's be opened, how to dial?

Both apps must be open at same time in the recent tab.
The Dialer app in the foreground to input the password.
The custoMIUIzer just running in background isn't enough. It must be open in the recent tab also.

![Screenshot_2023-09-15-01-33-35-578_com miui home](https://github.com/MonwF/customiuizer/assets/44372413/4d62b7f5-2feb-44af-8767-da83202edfbb)

**Comment by MonwF** [comment]
The custoMIUIzer running in background means that it is be opened in the recent tab.

**Comment by Birraque** [comment]
> The custoMIUIzer running in background means that it is be opened in the recent tab.

Doesn't custoMIUIzer auto start when the system boots like all other apps in the lsposed enabled apps?

**Comment by MonwF** [comment]
no. the module and app are diffrent

**Comment by Birraque** [comment]
> no. the module and app are diffrent

Thanks for your prompt response and awesome works!
Then none issue to fix.
Regards,

**Comment by MonwF** [comment]
i may add app shortcuts to open hidden folder

**Comment by MonwF** [comment]
next release will fix this bug. lsposed 1.9.1(modern api) is required

**Comment by Birraque** [comment]
> next release will fix this bug. lsposed 1.9.1(modern api) is required

Already tested the latest 米客-230919-A13-modern_api_安装务必.apk build and confirm that it's working flawlessly now. Thanks for your commitment to fix it. Regards,
