### ISSUE TITLE
Multiwindow+

### ISSUE THREAD

**Issue by 3zozHashim** [MonwF/customiuizer#36]
When i have two apps splitscreen and i try to open a floating window as well it doesnt work. I get a toast message from security app saying "split screen doesnt support floating windows"

Thank you for the awesome mods 👍

if possible, a feature to change location of default network speed indicator to the right would be awesome.

![Screenshot_2022-10-08-03-02-24-902_com google android youtube](https://user-images.githubusercontent.com/115328790/194680094-2881dc35-7d00-4483-94cc-f61d978a9c6b.jpg)

**Comment by MonwF** [comment]
did you open floating window from recents?
multiwindow+ works on my phones with cn and eu rom. what's your rom version?

**Comment by 3zozHashim** [comment]
> did you open floating window from recents? multiwindow+ works on my phones with cn and eu rom. what's your rom version?

i was using the sidebar for floating

Poco f3 global indonesia

MIUI (For Poco) = V13.0.3.0 
Android 12

**Comment by MonwF** [comment]
it is a bug that floating windows can't be opened from sidebar. You can do it from recents now

**Comment by 3zozHashim** [comment]
> it is a bug that floating windows can't be opened from sidebar. You can do it from recents now

i cant seem to open floating from recents while having splitscreen

floating works when im not in splitscreen

anyways, it doesnt really bother me, i dont use splitscreen much, i was just saying/reporting it to you.

thank you for the awesome mods

sorry for any inconveniences :)

**Comment by MonwF** [comment]
have you enabled the multiwindow+ switch in customiuizer settings?

**Comment by 3zozHashim** [comment]
> have you enabled the multiwindow+ switch in customiuizer settings?

yes

**Comment by MonwF** [comment]
the network speed indicator has been located at right from your screenshot?

**Comment by 3zozHashim** [comment]
> the network speed indicator has been located at right from your screenshot?
> 
> @3zozHashim

thats because im using a magisk module called nonedisplaycutout. It changes network position to the left but it also removes the AM/PM and the | that separates clock from notifications

**Comment by MonwF** [comment]
> > the network speed indicator has been located at right from your screenshot?
> > @3zozHashim
> 
> thats because im using a magisk module called nonedisplaycutout. It changes network position to the left but it also removes the AM/PM and the | that separates clock from notifications

try the lastest pre-release apk

**Comment by 3zozHashim** [comment]
> > > the network speed indicator has been located at right from your screenshot?
> > > @3zozHashim
> > 
> > 
> > thats because im using a magisk module called nonedisplaycutout. It changes network position to the left but it also removes the AM/PM and the | that separates clock from notifications
> 
> try the lastest pre-release apk

it didnt move it, it removed it.

thx for taking action on my request!!

**Comment by MonwF** [comment]
> > > > the network speed indicator has been located at right from your screenshot?
> > > > @3zozHashim
> > > 
> > > 
> > > thats because im using a magisk module called nonedisplaycutout. It changes network position to the left but it also removes the AM/PM and the | that separates clock from notifications
> > 
> > 
> > try the lastest pre-release apk
> 
> it didnt move it, it removed it.
> 
> thx for taking action on my request!!

keep waiting. i am looking for testers

**Comment by 3zozHashim** [comment]
> > > > > the network speed indicator has been located at right from your screenshot?
> > > > > @3zozHashim
> > > > 
> > > > 
> > > > thats because im using a magisk module called nonedisplaycutout. It changes network position to the left but it also removes the AM/PM and the | that separates clock from notifications
> > > 
> > > 
> > > try the lastest pre-release apk
> > 
> > 
> > it didnt move it, it removed it.
> > thx for taking action on my request!!
> 
> keep waiting. i am looking for testers

the nonedisplaycutout module is pretty good

it moves the network speed and it also moves the alarm and nfc to the right (in a new miui 13 update, the alarm and nfc changed position to the left)

so, you can check out that the module and maybe use the same codes to implement it in the app

idk much about coding and apps and stuff, so, if i said something that sounded stupid or something, im sorry

**Comment by MonwF** [comment]
somebody wants to move network speed only. you may find an option in developer settings and get the same effect

**Comment by MonwF** [comment]
you said that indicator was removed with the pre-release apk. can you watch a video and check if it will appear? i think it just disappears when speed is 0 kbps

**Comment by 3zozHashim** [comment]
> you said that indicator was removed with the pre-release apk. can you watch a video and check if it will appear? i think it just disappears when speed is 0 kbps

i tried downloading something and it progresses but the Network speed is invisible

**Comment by MonwF** [comment]
get the latest apk. move network speed to right side should  be working
