### ISSUE TITLE
Module doesn't work for me after 230411 version.

### ISSUE THREAD

**Issue by UzvarinatoR** [MonwF/customiuizer#363]
So all newer versions get crash on start. 230411 and earlier works just fine. 

Xiaomi Redmi 5A Lite
LineageOS 20 Official
Android 13
Magisk 23.6

**Comment by MonwF** [comment]
any log? you are the only one

**Comment by MonwF** [comment]
only miui is supported

**Comment by UzvarinatoR** [comment]
Yes, i have read in description "Mods are not guaranteed to fully work on any other versions", i fully understand this. I'm not demanding anything. Yet, i was glad to see that my device is on of those that actually also works with it. 230411 has almost all functions working. So its very upset to see app not even loading in next version. I though may be there is just one little thing is somewhere that prevents it to run, and may be you would be so kind to look for it. Of course i would be happy to provide logs and whatever is needed, just were i can find it?
