### ISSUE TITLE
Wave Charging Animation

### ISSUE THREAD

**Issue by judhistir88** [MonwF/customiuizer#370]
Feature request, 

Please try to add WAVE CHARGING ANIMATION if possible.

**Comment by MonwF** [comment]
use cemiuiler

**Comment by nakheel77** [comment]
> use cemiuiler

oh, thanks for reply, i also like cemiuiler. but before i have bootloop (i dont know what is in 1 of 2 module). but i like customize MIUI more. 

Now i have a problem, i cannot change any icon on my device. Someone can help me to fix it? Many thanks!!!
![photo_6152414225318918123_y](https://github.com/MonwF/customiuizer/assets/135938167/28d8f448-0fc0-4662-a320-48cd47e58c37)

Here is an animation of Black Shark version, it really nice. Someone tell me there is a module to make it, but i dont know where is to find and dowload that module. 
![photo_6154698989006600010_y](https://github.com/MonwF/customiuizer/assets/135938167/db7138cb-c29d-4d5b-971c-738ef76cf9bd)
