### ISSUE TITLE
更新以后桌面网格顶部间距失效了

### ISSUE THREAD

**Issue by wayzlin** [MonwF/customiuizer#371]
更新以后启动器→其他→桌面网格顶部间距这个选项失效了，型号是小米13，miui14.0.31。

**Comment by MonwF** [comment]
重新设置下呢？

**Comment by MonwF** [comment]
桌面版本是什么

**Comment by MonwF** [comment]
[app-release.zip](https://github.com/MonwF/customiuizer/files/12811693/app-release.zip)
