### ISSUE TITLE
lsposed中已经激活模块而且重启，但是打开米客的时候还是警告并未激活

### ISSUE THREAD

**Issue by 1001ace1001** [MonwF/customiuizer#372]
系统版本：MIUIcn 14.0.7-Android13
注入框架：zygisk-lsposed debug1.9.1-7006
米客版本：231004
root：magisk alpha 26301
机型：小米12-cupid
日志：
[LSPosed_2023-10-05T15_15_08.928679.zip](https://github.com/MonwF/customiuizer/files/12813481/LSPosed_2023-10-05T15_15_08.928679.zip)
注：在另一台note11tp上工作正常 14.0.3a13 ksu11238 相同框架和相同版本
#bug

**Comment by MonwF** [comment]
找lsp

**Comment by 1001ace1001** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正忙中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by 1001ace1001** [comment]
好。

**Comment by MonwF** [comment]
之前我看lsp的issue里有人反馈，把/data/apex/active清空，然后重刷lsp，重启后重新优化米客可以解决。从试下

**Comment by 1001ace1001** [comment]
已经确认问题，是对米客执行了mount_vold导致的。

**Comment by MonwF** [comment]
> 已经确认问题，是对米客执行了mount_vold导致的。

哪里操作的？

**Comment by 1001ace1001** [comment]
![image](https://github.com/MonwF/customiuizer/assets/100484574/73e410b6-1092-419e-bae5-2ac7dfdfad05)
说明它是打不开自己的配置文件才会这样的
抱歉浪费开发者的时间了。

**Comment by 1001ace1001** [comment]
> > 已经确认问题，是对米客执行了mount_vold导致的。
> 
> 哪里操作的？

在质感清理里面，这是一款对任意应用执行存储隔离的软件。

**Comment by MonwF** [comment]
我看到了这个日志，未激活的情况下，配置不会存储，所以会提示配置为空
