### ISSUE TITLE
Somethings new...

### ISSUE THREAD

**Issue by nakheel77** [MonwF/customiuizer#377]
Thank you very much for a best xiaomi module. 

i hope the next update, i can hide "airpalne" icon, and i can change battery icon in status bar!

many thanks!

here is a sample of battery icon on status bar, it like simple & interesting...
![Color-3D-Max-2](https://github.com/MonwF/customiuizer/assets/135938167/81aa3223-df47-4e78-b6f6-dd42ff8da45d)

**Comment by MonwF** [comment]
i will add 'hide airplane' in the next test build for android 13

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/12869610/app.zip)

A13+ and lsposed 1.9.1 are required
