### ISSUE TITLE
更新magisk后米客失效

### ISSUE THREAD

**Issue by actforjason** [MonwF/customiuizer#380]
>MIUI14.0.14.0.TLBCNXM，magisk更新到26.3，lsposed 1.9.2，米客最新版

其他模块都生效

**Comment by MonwF** [comment]
提示未激活？

**Comment by MonwF** [comment]
有没禁止关联启动 thanox之类的

**Comment by actforjason** [comment]
没有提示未激活，也没安装thanox。需要看什么日志吗？

**Comment by actforjason** [comment]
抱歉，好像不是没激活，而是米客的设置被重置了，看起来就像没起效果。

**Comment by MonwF** [comment]
看升级指南。。。
