### ISSUE TITLE
The Actions section in the Recent app list settings has disappeared

### ISSUE THREAD

**Issue by andrewk0** [MonwF/customiuizer#389]
In versions 23.08.26 and earlier there was a very convenient feature: mods System → Recent app list, at the very bottom — Actions:
![Screenshot_2023-11-15-11-42-52-594_name.monwf.customiuizer-edit.jpg](https://github.com/MonwF/customiuizer/assets/18374913/fa76d84e-633b-46d3-a093-b6004be62b78)
There you could replace the standard stupid labels with something of your own. For example:
![Screenshot_2023-11-15-12-15-28-197_com.miui.home-edit.jpg](https://github.com/MonwF/customiuizer/assets/18374913/de3cdfa0-3795-4763-8567-2bb94e7e5e49)

But in versions 23.10.04 and 23.10.30 there are no such items at all:
![Screenshot_2023-11-15-11-38-21-895_name.monwf.customiuizer-edit.jpg](https://github.com/MonwF/customiuizer/assets/18374913/50490da6-2dca-4fa9-8332-6f5c676813ae)

Is it possible to restore the functionality? It's really very convenient.
Xiaomi 11 Lite 5G NE, MIUI Global 14.0.5 (Android 13), Magisk 26.3, LSPosed 1.9.2.

**Comment by MonwF** [comment]
the function is removed and may not return
