### ISSUE TITLE
双排信号无法正常使用

### ISSUE THREAD

**Issue by Termux000001** [MonwF/customiuizer#39]
![Screenshot_2022-10-10-01-05-48-261-edit_name monwf customiuizer](https://user-images.githubusercontent.com/67861307/194799063-a1ca7285-2915-48c1-8dbb-95ff9a4337a1.jpg)
国行MIUI 13 v22.4.8
k40 a12
开启双排信号后只显示一排且只有一个

**Comment by MonwF** [comment]
你这不是显示得好好的？
app版本
