### ISSUE TITLE
澎湃os上，cpu温度读取不到

### ISSUE THREAD

**Issue by wldll** [MonwF/customiuizer#396]
![image](https://github.com/MonwF/customiuizer/assets/45764738/02d66ace-af6c-41d5-b6d7-848859c261ab)
![Screenshot_2023-11-22-22-46-23-106_mark via](https://github.com/MonwF/customiuizer/assets/45764738/ed9e988d-3ac4-410a-8e1c-e8572268461c)
![Screenshot_2023-11-22-22-46-52-203_com android settings](https://github.com/MonwF/customiuizer/assets/45764738/504feea2-0343-4636-b6e0-7cfa263965be)

**Comment by MonwF** [comment]
试下最新的

**Comment by wldll** [comment]
![Screenshot_2023-12-09-20-03-31-080_name monwf customiuizer-edit](https://github.com/MonwF/customiuizer/assets/45764738/9f27783a-11a3-4cc1-9462-091ea691b2e2)
![image](https://github.com/MonwF/customiuizer/assets/45764738/24ada31c-79f9-487b-bb01-9d6094416522)

还是不行，另外双排状态栏时间无法完全靠左

**Comment by MonwF** [comment]
无法靠左可能是和其他模块冲突，比如歌词。。
温度的话 能看下/sys/class/thermal/thermal_zone1目录吗

**Comment by wldll** [comment]
![image](https://github.com/MonwF/customiuizer/assets/45764738/b746b21a-8abc-4317-8714-e9cef2755138)
是这个目录么？

**Comment by 572644184** [comment]
最新版也不行

**Comment by wldll** [comment]
> 无法靠左可能是和其他模块冲突，比如歌词。。 温度的话 能看下/sys/class/thermal/thermal_zone1目录吗

排除了一下，确实是状态栏歌词的问题Orz

**Comment by MonwF** [comment]
是这个目录，看下下面的内容

**Comment by wldll** [comment]
> 是这个目录，看下下面的内容

都在长截图里了

**Comment by MonwF** [comment]
打开temp那个文件 里面就是温度

**Comment by wldll** [comment]
> 打开temp那个文件 里面就是温度

![image](https://github.com/MonwF/customiuizer/assets/45764738/6c2ce02e-4a22-44e7-8970-000b82aa5021)
里面只有数字0……

**Comment by 572644184** [comment]
我的也是

**Comment by MonwF** [comment]
看下其他的zone，里面有个type，要包含cpu，然后看下temp里面不为空就行

**Comment by wldll** [comment]
这个是吗？

**Comment by wldll** [comment]
![Screenshot_2023-12-09-21-15-36-074_bin mt plus](https://github.com/MonwF/customiuizer/assets/45764738/52b0c670-87a1-4899-a00c-9406513d4365)
![Screenshot_2023-12-09-21-15-26-585_bin mt plus](https://github.com/MonwF/customiuizer/assets/45764738/ba8aaa0b-ba80-475c-912d-f609da786c4e)
![Screenshot_2023-12-09-21-15-16-032_bin mt plus](https://github.com/MonwF/customiuizer/assets/45764738/4077120e-53af-4a26-8f6a-4dc18ed8c75c)

**Comment by 572644184** [comment]
type文件里有CPU的从zone10开始

**Comment by MonwF** [comment]
对，type要包含cpu。。。如果有命令行 可以进入目录 cat */type | grep cpu

**Comment by wldll** [comment]
> 对，type要包含cpu。。。如果有命令行 可以进入目录 cat */type | grep cpu

![image](https://github.com/MonwF/customiuizer/assets/45764738/cd9d4036-d84e-467e-8156-6d59140787f5)
看看

**Comment by MonwF** [comment]
这和以前机器的cpu传感器完全不一样了

**Comment by 572644184** [comment]
![Screenshot_2023-12-09-21-34-47-337_com byyoung setting](https://github.com/MonwF/customiuizer/assets/43559843/08f4b3f9-6f19-4571-bd9a-e4f95f772bb8)
这个可以读取出来

**Comment by MonwF** [comment]
应该是遍历去找cpu传感器，获得的温度。。。米客没有这样干，可以优化下

**Comment by wldll** [comment]
scene可以读出……

**Comment by wldll** [comment]
> `for z in /sys/class/thermal/thermal_zone*/;do echo -n $z;echo " $(cat $z/type)";done | grep cpu`
> 
> 执行下这个 可能取cpu温度不能现在这样简单粗暴了，不太准

![Uploading Screenshot_2023-12-09-22-48-48-029_bin.mt.plus.jpg…]()

**Comment by wldll** [comment]
![image](https://github.com/MonwF/customiuizer/assets/45764738/4b9b8150-028c-4578-b300-e0fb2c9f832e)

**Comment by MonwF** [comment]
试下 应该修了

**Comment by wldll** [comment]
> 试下 应该修了

![image](https://github.com/MonwF/customiuizer/assets/45764738/31de3733-6436-4f80-8161-40ffeb3bda16)
生效了

**Comment by 572644184** [comment]
![Screenshot_2023-12-10-09-27-53-524_name monwf customiuizer](https://github.com/MonwF/customiuizer/assets/43559843/0c8571de-f636-47c0-9d64-c680f5b7b052)
有了
