### ISSUE TITLE
时钟设置 小时补0 有个小瑕疵

### ISSUE THREAD

**Issue by Hvsenjan** [MonwF/customiuizer#398]
小时补0以后下滑通知栏，通知栏显示时间没有加0，会一个小跳动来显示0和隐藏0，

https://github.com/MonwF/customiuizer/assets/48145442/76d6c115-b25a-4105-b053-5a3b868e9078

虽然不影响使用，但是希望通知栏显示也能补个0
![Screenshot_2023-11-25-22-07-53-031_com android shell](https://github.com/MonwF/customiuizer/assets/48145442/c3514dd5-d62c-45d2-bc32-0e66f0f35f3d)
![Screenshot_2023-11-25-22-08-03-067_name monwf customiuizer](https://github.com/MonwF/customiuizer/assets/48145442/297e04ab-3fbf-40c6-b995-3ae23eaee82e)

**Comment by Hvsenjan** [comment]
![IMG_20231125_222249](https://github.com/MonwF/customiuizer/assets/48145442/c8b6fdfc-46d3-43a1-8d7b-e0c175e127a4)

**Comment by MonwF** [comment]
通知抽屉的时钟可以设置自定义格式，如hh:mm或者HH:mm，以实现补0
