### ISSUE TITLE
Silent any audio feature missing? 

### ISSUE THREAD

**Issue by NC503** [MonwF/customiuizer#399]
Hı mate. Thank you for your perfect work. I used the silent some system audio with your APK for a while . But ı did not find this feaute now. Can you add this option again?

**Comment by MonwF** [comment]
maybe nerver

**Comment by NC503** [comment]
Bro, ı dont want a new feature. I want only silent audio feature back. 26 Kas 2023 03:41 tarihinde MonwF ***@***.***> yazdı:
maybe nerver

**Comment by MonwF** [comment]
i removed some features that few people require to keep it simple. sorry for that. you can build it yourself

**Comment by NC503** [comment]
Come on man.. It's very simple feature. Please... 26 Kas 2023 09:43 tarihinde MonwF ***@***.***> yazdı:
i removed some features that few people require to keep it simple. sorry for that. you can build it yourself

**Comment by NC503** [comment]
Mate, i don't know coding..This feature is very simple.Please add this feature again.Or maybe you can add disabling audio option for the waterdropprewiev.ogg sound.It plays when disabling the silent profile.26 Kas 2023 10:06 tarihinde Melikşah ÇIRAKOĞLU ***@***.***> yazdı:Come on man.. It's very simple feature. Please... 26 Kas 2023 09:43 tarihinde MonwF ***@***.***> yazdı:
i removed some features that few people require to keep it simple. sorry for that. you can build it yourself

**Comment by NC503** [comment]
Hi mate. I tried 1to add this option but i can't. Please can you add again? Please.  My device android 13 miui 14 26 Kas 2023 09:43 tarihinde MonwF ***@***.***> yazdı:
i removed some features that few people require to keep it simple. sorry for that. you can build it yourself
