### ISSUE TITLE
反馈一个bug:清理打开方式菜单 部分应用无法调用

### ISSUE THREAD

**Issue by wzgrx** [MonwF/customiuizer#40]
清理打开方式菜单
从打开方式菜单移除所选应用
在里面勾选过一些应用后，然后取消或者关闭这个功能。很多应用无法调用起来。
比如ins登录调用Facebook，打开方式菜单找不到Facebook，wps登录调用QQ，方式方式找不到QQ
请问这个怎么恢复呢？
关闭模块和功能还是恢复不了，求开发者测试一下，红包奉上

**Comment by MonwF** [comment]
不好意思，造成了影响。
粗略看了下，这个功能不会侵入系统配置或者文件，理论上关闭后重启就会恢复，晚点看下

**Comment by wzgrx** [comment]
> 

好多，谢谢开发者，主要我试了关闭功能，关闭模块，重新刷rom，都没有恢复，不知道这个功能hook的是那个系统组件，我可以试试清理这个组件的应用数据试试

**Comment by MonwF** [comment]
wps调用QQ这个过程能录下屏吗？

**Comment by wzgrx** [comment]
> wps调用QQ这个过程能录下屏吗？

**Comment by wzgrx** [comment]
> wps调用QQ这个过程能录下屏吗？

发不了视频，可以其他方式联系不，QQ邮箱或者什么的

**Comment by MonwF** [comment]
邮箱在个人github主页有
