### ISSUE TITLE
希望音量百分比显示高度能往下调整一点

### ISSUE THREAD

**Issue by callng** [MonwF/customiuizer#403]
![Screenshot_2023-11-29-04-38-11-449_name.monwf.customiuizer.png](https://github.com/MonwF/customiuizer/assets/64207250/4adaf9f8-362e-4219-9f73-e200c4e606a2)

上图因为截图的原因看不出来，小米13ultra前置摄像头是居中的。这会导致看起来顶部会被遮住了一样，非常难受！希望下个版本将这个调整一下。

**Comment by MonwF** [comment]
在亮度百分比下面可以调整顶部位置
