### ISSUE TITLE
源码同步

### ISSUE THREAD

**Issue by buffcow** [MonwF/customiuizer#404]
你好，最新版源码没同步吗，还想着想提几个 PR 来着🥲

**Comment by MonwF** [comment]
感谢，暂时还未同步，在另一个仓库里，准备过段时间再重构些东西，一起放出来。到时欢迎pr

**Comment by buffcow** [comment]
> 感谢，暂时还未同步，在另一个仓库里，准备过段时间再重构些东西，一起放出来。到时欢迎pr

嗯嗯好的，辛苦了

**Comment by buffcow** [comment]
> 感谢，暂时还未同步，在另一个仓库里，准备过段时间再重构些东西，一起放出来。到时欢迎pr

所以还是没有开源吗(手动滑稽)

**Comment by MonwF** [comment]
> > 感谢，暂时还未同步，在另一个仓库里，准备过段时间再重构些东西，一起放出来。到时欢迎pr
> 
> 所以还是没有开源吗(手动滑稽)

还没有，坑太多了，想把ui层和资源hook再搞搞。你可以直接往西米露提pr，用户和维护者更多。。。我这可能随时停止开发

**Comment by buffcow** [comment]
> > > 感谢，暂时还未同步，在另一个仓库里，准备过段时间再重构些东西，一起放出来。到时欢迎pr
> > 
> > 
> > 所以还是没有开源吗(手动滑稽)
> 
> 还没有，坑太多了，想把ui层和资源hook再搞搞。你可以直接往西米露提pr，用户和维护者更多。。。我这可能随时停止开发

停止开发就很可惜了老哥，西米露给人的感觉太重了所以才来的米客，比较轻而且日常用也足够了。
想着能为这个项目提些pr，修修补补也好。总好过一个人维护
