### ISSUE TITLE
miui14上有几个选项不生效

### ISSUE THREAD

**Issue by 7mm** [MonwF/customiuizer#406]
小米13Ultra，miui14系统，目前使用过程基本良好，但遇到几个无法生效的选项，基本都在系统-其他中，比如开启查看wifi密码后实际仍旧无法查看；选择了取消打开应用确认，实际上还是会弹出确认提示。其他的暂时没有遇到，期待后续完美，辛苦了，感谢！

**Comment by MonwF** [comment]
用其他模块，精力有限。只维护hyperos了
