### ISSUE TITLE
the number in front is not visible 

### ISSUE THREAD

**Issue by ammlr** [MonwF/customiuizer#41]
in app installer info, I think the numbers on the front are very important in comparing app versions. maybe you can fix it sir
![195583297-b7140097-6534-4aa5-b1e9-252ae046c437](https://user-images.githubusercontent.com/30746607/195826245-6800aa2f-4998-4c51-9232-05e6d4d9c26f.jpg)

**Comment by MonwF** [comment]
why package installer is opened in dialog?

**Comment by MonwF** [comment]
no further info
