### ISSUE TITLE
米客在lsposed中激活后并重启仍然显示未激活

### ISSUE THREAD

**Issue by 1001ace1001** [MonwF/customiuizer#411]
[LSPosed_2023-12-17T19_08_57.222691.zip](https://github.com/MonwF/customiuizer/files/13695873/LSPosed_2023-12-17T19_08_57.222691.zip)
以上是日志，上次已经排除到了是重定向的原因，现在在没有对米客使用重定向的时候也出现这个问题。

**Comment by MonwF** [comment]
未激活前，日志肯定没有信息。只有2个原因，一个是lsp版本太低，一个是被其他app限制了自启动

**Comment by 1001ace1001** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正忙中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by 1001ace1001** [comment]
> 太低，一个是被

不可能太低，是7049debug，但是那个出bug的时候lsposed也闪退了 cannot get resource
[LSPosed_crash_report1702815135.zip](https://github.com/MonwF/customiuizer/files/13696070/LSPosed_crash_report1702815135.zip)
[LSPosed_crash_report1702813912.zip](https://github.com/MonwF/customiuizer/files/13696073/LSPosed_crash_report1702813912.zip)
[LSPosed_crash_report1702813619.zip](https://github.com/MonwF/customiuizer/files/13696074/LSPosed_crash_report1702813619.zip)
[LSPosed_crash_report1702811688.zip](https://github.com/MonwF/customiuizer/files/13696075/LSPosed_crash_report1702811688.zip)

**Comment by MonwF** [comment]
未激活和get resource无关，激活检测要依赖provider启动后 进行的binder通信，如果lsp启动米客换provider失败，就无法激活。。。你看下ifw模块有没影响
