### ISSUE TITLE
Can't install?

### ISSUE THREAD

**Issue by ValerioWasTaken** [MonwF/customiuizer#413]
![Screenshot_2023-12-25-17-25-55-953_com google android packageinstaller-edit](https://github.com/MonwF/customiuizer/assets/101035427/1bbe06fc-bcb1-4798-8f46-2d8657b619d9)

Not even the telegram version. Is this only for hyperos? If so why does it say to update the MIUI version on LSPosed

**Comment by MonwF** [comment]
yes. see changelog for the previous versions. you can download the legacy versions for miui 14 or 13
