### ISSUE TITLE
希望妥善处理MIUI14的更新提示问题

### ISSUE THREAD

**Issue by AXEVO** [MonwF/customiuizer#414]
新版本模块不再支持MIUI14，但是有一些手机却永远留在了MIUI14，这些机器上没法更新模块，lsp框架就会一直置顶提示可更新模块，显示红点，且lsp内置仓库没有忽略功能，这个红点和更新提示没法消除看着非常烦人，希望能妥善处理MIUI14这边的问题，可以像西米露一样更换包名，hyper上使用新包名，装旧包名的模块就不会提示更新，也可以加个检测，让旧机器可以更新，检测到旧系统就只显示那些旧系统能用的功能

**Comment by MonwF** [comment]
1. 给lsp提需求
2. 更换包名会让大部分用户备份再导入
3. 兼容旧版本：个人精力有限，也不想维护太复杂
4. 可行的方案：改下米客的版本号，重新安装

**Comment by MonwF** [comment]
重新打包了个版本比较高的A13的包，绕过lsp的检测更新
