### ISSUE TITLE
“两侧向内滑动并停顿”未生效

### ISSUE THREAD

**Issue by jim4ever** [MonwF/customiuizer#415]
全面屏导航手势中的“两侧向内滑动并停顿”设置后，操作有震动，但未触发设置的操作

**Comment by MonwF** [comment]
确保官方桌。。。没日志，信息太少

**Comment by jim4ever** [comment]
手机：小米14Pro
系统版本：hyperOS 1.0.27.0
桌面为官方桌面
米客版本为最新的23.12.24
经过测试，同样的操作在左下角和右下角上划动作中可触发，在两侧内滑并停顿无法触发。
请问在哪里可以导出日志？

**Comment by MonwF** [comment]
你设置的动作是什么？

**Comment by jim4ever** [comment]
> 你设置的动作是什么？

展开侧边栏和展开通知中心都有试过。主要是想设置展开侧边栏。
初次设置未触发后，做过以下的测试：
1、首次设置为两侧内滑展开侧边栏，左下角上划展开通知栏。结果：内滑展开侧边栏未生效，左下角上划触发通知栏成功。
2、测试对调设置，两侧内滑展开通知栏，左下角上划展开侧边栏。结果：内滑展开通知栏未生效，左下角上划触发侧边栏成功。

**Comment by MonwF** [comment]
设置成简单的如锁屏之类的动作试试？记得重启桌面

**Comment by jim4ever** [comment]
> 设置成简单的如锁屏之类的动作试试？记得重启桌面

设置为锁定桌面后依然未生效，做为对比，将右下角上划设置为同样的操作，右下角上划触发成功。

**Comment by MonwF** [comment]
桌面版本呢？

**Comment by jim4ever** [comment]
> 桌面版本呢？

系统桌面版本为：RELEASE-4.39.14.7718-11212221

**Comment by MonwF** [comment]
确定是官方桌面？？？不行就更新下桌面吧

**Comment by jim4ever** [comment]
> 确定是官方桌面？？？不行就更新下桌面吧

确定是官方的，刚root。软件市场没看到有更新啊，请问需要在哪里更新桌面？

**Comment by MonwF** [comment]
酷安上搜索下

**Comment by jim4ever** [comment]
> 酷安上搜索下

下载了同版本系统桌面重新安装后好了，感谢。
