### ISSUE TITLE
更新到HyperOS后，网速移动到第2排显示设置失效。

### ISSUE THREAD

**Issue by wjf0214** [MonwF/customiuizer#416]
今天系统从MIUI 14更新到HyperOS 1.0.4.0.UMREUXM，米客同步升级到v23.12.24版本。
但是发现之前第二排的网速显示没有了，经过不断的测试发现网速信息在第1排的左边和右边都可以正常显示。在第2排不行。
通过  `系统->状态栏->图标位置调整->系统图标移到第2排显示（网速）->开启` 设置无效。
电池信息和温度信息可以正常显示在第2排，网速不行。
具体系统版本和状态效果如下图。

系统信息：
![6b81bf971208f29995c43dd233193e7](https://github.com/MonwF/customiuizer/assets/23102821/1379484d-f21e-4e2f-af6c-bfaf07d1d486)

状态栏设置第2排显示后信息状态：
![f2ea44f3460a5096ec772bf34af3036](https://github.com/MonwF/customiuizer/assets/23102821/4b05ab61-9f14-45d9-8f61-e305453a32fc)

**Comment by MonwF** [comment]
是的，还没支持

**Comment by MonwF** [comment]
已支持，从模块主页下载测试版即可
