### ISSUE TITLE
设置“时钟设置”补秒后，解决元素抖动的建议

### ISSUE THREAD

**Issue by Zerorigin** [MonwF/customiuizer#418]
设置👉米客👉系统👉控制中心👉时钟设置

1、建议增加一项使用自定义字体的选项
2、在米客内置一些字体或者使用系统字体库里的字体
(P.S.：对于 Rooted 的设备，米客使用者自行安装新字体到系统字体库应该没有太大的难度)
3、允许使用者自行选择一些内置了等宽数字的字体

只有这样才能从根本解决相邻元素抖动的问题

另外“设置👉米客👉系统👉其它👉飞行模式设置”内的 NFC 相关选项的“关闭”及“关闭并禁用”似乎已经失效，不会在开启飞行模式时执行相应操作

**Comment by MonwF** [comment]
自定义字体这个不会加，太重了，不是米客的方向..
飞行模式模式下nfc这个是直接调用的系统api，miui把它删了，这个场景比较小，我也没兴趣把它加回来。原作者在下面加了行字，应该是这个意思
