### ISSUE TITLE
Skip permission intercept timer not working 

### ISSUE THREAD

**Issue by Bladius2022** [MonwF/customiuizer#42]
In the latest version, the option has stopped working "Skip permission intercept timer". You have to wait 10 seconds again.

**Comment by MonwF** [comment]
provide Security app version

**Comment by Bladius2022** [comment]
7.2.2-221014.0.1
it also happened on the factory version.  It fixed itself, however, I had to remove the root and upload it again with the magisk and re-load all modules.  It is possible that LSPosed crashed because I reinstalled CustoMIUIzer13 several times on different versions and nothing.  But it's already working fine

**Comment by MonwF** [comment]
> 7.2.2-221014.0.1 it also happened on the factory version. It fixed itself, however, I had to remove the root and upload it again with the magisk and re-load all modules. It is possible that LSPosed crashed because I reinstalled CustoMIUIzer13 several times on different versions and nothing. But it's already working fine

just uncheck and recheck on security in the scope settings
