### ISSUE TITLE
发送截图界面新应用不以小窗流转的形式显示

### ISSUE THREAD

**Issue by edge-sky** [MonwF/customiuizer#421]
在大部分涉及分享等页面下，以小窗流转是非常有用的，但在MIUI或是HyperOS下的截图后点击分享，选择分享的应用后截图分享界面本身几乎已无其他其他用处。希望添加 从截图页面发起的应用流转不以小窗打开 的选项。
![Screenshot_2024-01-04-12-45-18-751_com android mm](https://github.com/MonwF/customiuizer/assets/95955401/6c0474b8-b806-4994-8a84-b78c6ce1f5a0)

**Comment by MonwF** [comment]
暂不会专门这个场景去优化
