### ISSUE TITLE
双击音量下键打开手电筒的功能无效

### ISSUE THREAD

**Issue by 970844297** [MonwF/customiuizer#422]
如题，更新澎湃之后就这样了。应该是bug吧。面具版本26.1，lsp 1.9.2 米客24.01.02。麻烦了

**Comment by MonwF** [comment]
一切正常。请在系统设置中开启音量下键打开相机

**Comment by 970844297** [comment]
> 一切正常。请在系统设置中开启音量下键打开相机

但我想保留电源键打开相机，记得miui14的时候是可以的😥

**Comment by MonwF** [comment]
不冲突啊，多个键都可以设置为打开相机
