### ISSUE TITLE
“默认USB配置”设置无效

### ISSUE THREAD

**Issue by 7mm** [MonwF/customiuizer#423]
小米13U，澎湃os，设置默认usb配置为MTP无效，一直都是默认充电，希望大大考虑修复下，感谢！

**Comment by MonwF** [comment]
![Screenshot_2024-01-26-17-03-11-785_com android settings](https://github.com/MonwF/customiuizer/assets/1267050/ddb4088c-7df5-4ecf-9532-9705c26e2b17)


这个功能已经在开发者选项里提供了，后面会删除
