### ISSUE TITLE
Navigation bar modification missing

### ISSUE THREAD

**Issue by dranivil** [MonwF/customiuizer#429]
In customiuizer for miui there was an option to modify the height of the navigation bar and add 2 extra buttons.  With the version for HyperOS both options have disappeared, although strangely it allows you to select the action for those extra buttons.

**Comment by MonwF** [comment]
modify nav height option has been removed. i will check the extra button feature

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/14032909/app-develop.zip)

fixed extra buttons
