### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [MonwF/customiuizer#430]
My APK scanner just got a few new checks implemented lately, and reported on today's update here:

```
! repo/name.monwf.customiuizer_69.apk declares flag(s): usesCleartextTraffic
! repo/name.monwf.customiuizer_69.apk declares risky permission(s): android.permission.ACCESS_FINE_LOCATION android.permission.ACCESS_COARSE_LOCATION android.permission.READ_EXTERNAL_STORAGE android.permission.QUERY_ALL_PACKAGES
```

Could you please clarify what these permissions are needed for – and why `cleartextTraffic` is required? Thanks in advance!

**Comment by MonwF** [comment]
usesCleartextTraffic is inherited from the previous module and can be set to fasle. 
those permissons are for wifi unlock and selecting apps.
remember. lsp module can get everything without permissions. so scanner is useless

**Comment by IzzySoft** [comment]
> usesCleartextTraffic is inherited from the previous module and can be set to fasle.

So will you do that?

> remember. lsp module can get everything without permissions. so scanner is useless

I know running with root powers (as Xposed modules do) they can access everything. That you request those permissions nevertheless shows you care for transparency of what you access, which is a very good thing – thanks for that! But to make that really transparent to those using your module, it's even better if the background is made clear. Which is what my scanner takes care for.

If you take a look [here](https://apt.izzysoft.de/fdroid/index/apk/name.monwf.customiuizer) (your module in my repo), scroll down to "Packages" and then expand the "Permissions", this is what you'll currently see:

![image](https://github.com/MonwF/customiuizer/assets/6781438/8c13c9a5-0696-4d62-8e03-7a0e0cff3299)

The "chocolate colored once" are sensitive permissions that should be accompanied by explanations, as it's e.g. done for [this app](https://apt.izzysoft.de/fdroid/index/apk/com.craxiom.networksurvey/):

![image](https://github.com/MonwF/customiuizer/assets/6781438/765bea2d-b897-4241-b6e9-16c1bb0f4489)

You see there the "chocolate" turned blue as the reasons for the permissions are clear and justified. To make things that transparent builds trust – and that's what this is about :wink:

**Comment by IzzySoft** [comment]
@MonwF so no?

**Comment by MonwF** [comment]
usesCleartextTraffic removed

**Comment by IzzySoft** [comment]
Thanks! And is there some explanation I could put with those 4 "chocolate" permissions? Isn't `READ_EXTERNAL_STORAGE` even ignored with Android 13 and higher (replaced by `MANAGE_EXTERNAL_STORAGE`)?

**Comment by IzzySoft** [comment]
@MonwF today's update sent me the warning again:

```
! repo/name.monwf.customiuizer_70.apk declares sensitive permission(s):
  android.permission.ACCESS_FINE_LOCATION android.permission.ACCESS_COARSE_LOCATION
  android.permission.READ_EXTERNAL_STORAGE android.permission.QUERY_ALL_PACKAGES
! repo/name.monwf.customiuizer_70.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

As for that `DEPENDENCY_INFO_BLOCK`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by MonwF** [comment]
DEPENDENCY_INFO_BLOCK will be removed in the next release.
need location permission to scan wifi and bluetooth for unlock devices

**Comment by IzzySoft** [comment]
Thanks for removing the blob and confirming the location permissions! Can you confirm what `android.permission.READ_EXTERNAL_STORAGE` and `android.permission.QUERY_ALL_PACKAGES` are needed/used for, too?

![image](https://github.com/MonwF/customiuizer/assets/6781438/5fb30dd3-022c-45be-a776-aa2c88ce501f)

**Comment by MonwF** [comment]
QUERY_ALL_PACKAGES - select apps
READ_EXTERNAL_STORAGE - will remove
