### ISSUE TITLE
禁用系统完整性检查 “启用” 没效果

### ISSUE THREAD

**Issue by insignificance** [MonwF/customiuizer#431]
版本：24.01.24 在最新的hyperOS 1.0.31.0 xiaomi14上无法正常使用  ”禁用系统完整性检查“ 功能
上一个测试版本24.01.19-test 能正常使用

希望大大考虑修复下，感谢！

**Comment by MonwF** [comment]
1月24的版本和1.19的代码99%是一样的，没有改这块功能。如果测试版本能用，就继续用吧。。。你先确认下是系统升级导致还是模块升级导致

**Comment by insignificance** [comment]
好的已排查出问题，是我的锅，不是米客的问题。抱歉抱歉
