### ISSUE TITLE
[BUG] Cannot install on MIUI 14?

### ISSUE THREAD

**Issue by n00b69** [MonwF/customiuizer#433]
As the title says, the package is invalid when trying to install it on MIUI 14. The Github says MIUI 13 and 14 are supported.

![IMG_20240127_145445_150](https://github.com/MonwF/customiuizer/assets/83274506/8a9a84a5-44d7-433d-846b-11bc57922c8c)

**Comment by MonwF** [comment]
https://github.com/MonwF/customiuizer/releases/tag/v23.11.26
