### ISSUE TITLE
深色模式下桌面文件夹背景发黑

### ISSUE THREAD

**Issue by actforjason** [MonwF/customiuizer#436]
希望可以自调节透明度
![Screenshot_2024-01-31-10-32-37-018_com.miui.home.png](https://github.com/MonwF/customiuizer/assets/57058325/4ec8f031-615d-457b-829f-67e0097fd7d9)

**Comment by MonwF** [comment]
让第3方主题自己适配

**Comment by actforjason** [comment]
使用是默认桌面主题，第三方主题太花里胡哨了，hyperos相比MIUI的文件夹在深色模式下统一调黑了。
