### ISSUE TITLE
可否添加一个能把所有通知给运行关闭的功能

### ISSUE THREAD

**Issue by hrflni** [MonwF/customiuizer#439]
有很多APP的通知选项是关闭不了的，一定要打开。
新版的手机管家以前是可以直接关闭通知的，新版的就把这个给固定了，不能取消。

**Comment by MonwF** [comment]
开启了允许修改任何应用的通知没

**Comment by hrflni** [comment]
> 开启了允许修改任何应用的通知没

打开了，但还是修改不了。红米11TP。

**Comment by MonwF** [comment]
单个通知的关闭是权限控制的，不方便hook，你可以先关闭某些类别的通知。。不过，可以在系统界面里过滤特定app的通知，应该也能达到一样的效果。
