### ISSUE TITLE
状态栏温度字体

### ISSUE THREAD

**Issue by buzenm** [MonwF/customiuizer#44]
状态栏显示温度的字体能不能改成和别的内容相同呢

**Comment by buzenm** [comment]
大小，粗细这些

**Comment by MonwF** [comment]
粗细没调整，大小特意调小的，短期内不会改了

**Comment by buzenm** [comment]
如果是因为长度的话，能否考虑只保留整数呢，相比于状态栏的空间，温度的小数点显示的意义感觉优先级很低

**Comment by MonwF** [comment]
只显示温度 字体大点

**Comment by buzenm** [comment]
还是得保留℃单位，要不会和旁边的数字混淆，不容易区分的

**Comment by MonwF** [comment]
你可以只显示电流

**Comment by buzenm** [comment]
![注释大小对其方式代码.PNG.jpg](https://user-images.githubusercontent.com/25559469/197330640-82026763-be8c-4f11-8fd5-254dc3613cc2.jpg)
![更改字体大小.PNG.jpg](https://user-images.githubusercontent.com/25559469/197330655-fb720b93-579b-4519-82a7-f0c6fd252547.jpg)
注释掉可以吗？改了感觉有点不对，还是改成什么值更好一点
![Screenshot_2022-10-22-16-54-51-979_com.github.android.jpg](https://user-images.githubusercontent.com/25559469/197330667-351dcc92-aa6c-401e-9564-3fad2b4bacbe.jpg)

**Comment by MonwF** [comment]
这个13就是时钟文字的大小，为了兼容网速文字的大小 所以不能去
