### ISSUE TITLE
期望增加连接耳机时扬声器静音的设置

### ISSUE THREAD

**Issue by jim4ever** [MonwF/customiuizer#441]
感谢作者的模块，解决了很多问题。期望增加一个声音设置：
原MIUI具有声音助手，可设置在连接耳机时关闭扬声器的来电和通知铃声，但是在澎湃OS中去除了，导致连接蓝牙耳机时，来电话或者通知时，扬声器和耳机同时发声，期望可以进行设置，实现此场景下来电或通知时仅耳机发声即可。

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/14340095/app.zip)

试下这个看看，在系统-声音里开启禁用高音量警告，然后重启系统界面

**Comment by jim4ever** [comment]
> [app.zip](https://github.com/MonwF/customiuizer/files/14340095/app.zip)
> 
> 试下这个看看，在系统-声音里开启禁用高音量警告，然后重启系统界面

感谢回复，测试了此版本，没有起作用。铃声状态下，连接蓝牙耳机，扬声器同样会发声。

**Comment by jim4ever** [comment]
感谢回复，刚才进行了安装和测试，同场景下依然会扬声器和耳机同时响铃。
我主要想实现的场景是：响铃或震动模式下，电话设置中的来电播报，在连接耳机时，播报声仅从耳机中发出。当前的设置会耳机和扬声器都有播报声。

**Comment by MonwF** [comment]
那暂时无解了。。。音频系统还不太熟悉 等以后吧

**Comment by jim4ever** [comment]
> 那暂时无解了。。。音频系统还不太熟悉 等以后吧

十分感谢回复。
