### ISSUE TITLE
Reduce status bar height

### ISSUE THREAD

**Issue by M7amma** [MonwF/customiuizer#442]
Hello 
Can you please allow setting the status bar height for less than 20 dp?
Thanks a lot

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/14468090/app.zip)
you can set statusbar height  with 12dp

**Comment by M7amma** [comment]
Thank you so much it worked well, hope it will be added to the next release. And if possible to allow lowering than 12 will be nice. Thanks anyway.
