### ISSUE TITLE
双排状态栏时，时钟会居中显示

### ISSUE THREAD

**Issue by Qwerto107** [MonwF/customiuizer#444]
启用双排状态栏时，时钟会显示在状态栏左半边的中间位置。
能否设置成左对齐显示？~~（有强迫症，右边是右对齐的）~~
或者能否提供一个设置项，让用户自由选择居中还是左对齐
![Screenshot_2024-02-23-23-18-18-196_com ss android ugc aweme-edit](https://github.com/MonwF/customiuizer/assets/25398342/26a0dd73-e9e0-4c6a-a32a-a3b1cb745a06)
![Screenshot_2024-02-23-23-18-35-560_com brave browser-edit](https://github.com/MonwF/customiuizer/assets/25398342/74026e69-af58-45be-a713-2d357caec492)

**Comment by MonwF** [comment]
据说是和状态栏歌词冲突

**Comment by Qwerto107** [comment]
抱歉，刚试了下的确是状态栏歌词导致的居中显示
