### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by anasfanani** [MonwF/customiuizer#446]
Cant install on hyperos 1 eu redmi note 11 spes

![Screenshot_2024-02-27-11-00-19-790_com.miui.packageinstaller.jpg](https://github.com/MonwF/customiuizer/assets/135501348/db7e192b-4c5a-44cc-9000-bf9a9d350050)

Oh sorry, after check my android version is 13. :(
![Screenshot_2024-02-27-11-03-38-600_com.android.settings.jpg](https://github.com/MonwF/customiuizer/assets/135501348/ac7ca6ba-57a4-44aa-8ef2-42b6466cfef9)

Is there alternative for android 13 ?

**Comment by MonwF** [comment]
read readme
