### ISSUE TITLE
"Secure Quick Settings" does not work.

### ISSUE THREAD

**Issue by Vader77Darth** [MonwF/customiuizer#448]
The "secured" toggles can still be turned on and off on the lock screen.

**Comment by MonwF** [comment]
，yes, another rarely used feature. maybe removed later

**Comment by Vader77Darth** [comment]
Noooo. It's such a useful feature. If someone steals your phone, they can just disable wifi, GPS, data, etc. and then you will never be able to find it again.🙁

**Comment by MonwF** [comment]
He can shutdown the phone and remove sim cards. wifi should be disconnected  automatically.

**Comment by Vader77Darth** [comment]
I disabled the power menu on lockscreen. So, there is no easy way to power off the phone.

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/14722033/app.zip)

try this build.

**Comment by Vader77Darth** [comment]
Yep! That seems to have fixed it. Thanks.
