### ISSUE TITLE
开源请求

### ISSUE THREAD

**Issue by Qwerto107** [MonwF/customiuizer#452]
源码似乎已经很久没有更新了，大佬能否同步下源码，想自定义下双排状态栏

想把双排状态栏第一行左侧的宽度限制往右调，让状态栏歌词显示更完整，我手机摄像头的位置不会挡到状态栏歌词
![Screenshot_2024-03-16-11-28-00-173_com brave browser-edit](https://github.com/MonwF/customiuizer/assets/25398342/eb75d9d4-7769-49ef-ae22-904e975d98fc)
![Screenshot_2024-03-16-11-32-04-372_com brave browser-edit](https://github.com/MonwF/customiuizer/assets/25398342/85b56a30-25d6-427b-8f04-9a31ece0ced6)

**Comment by Qwerto107** [comment]
或者大佬能不能出一个设置选项，强制使用完整屏布局，不考虑异形屏的摄像头位置

**Comment by MonwF** [comment]
右侧正常情况图标很多 左侧一般占空间比较少 所以现在是1：1分配。后续开放比例自定义吧

开源暂时没计划，之前有些规划的重构没时间做

**Comment by MonwF** [comment]
已添加双排状态栏下，左右侧宽度比

**Comment by Qwerto107** [comment]
> 已添加双排状态栏下，左右侧宽度比

感谢，新的包啥时候会出

**Comment by Qwerto107** [comment]
@MonwF 
版本：Pengeek-24.03.25-test.apk

竖屏时左右侧宽度比没有生效
有尝试过：重启系统界面、系统、关闭状态栏歌词模块
![image](https://github.com/MonwF/customiuizer/assets/25398342/f0e35300-38eb-4d89-a721-27c253b04d44)
![image](https://github.com/MonwF/customiuizer/assets/25398342/44ae3cc2-65e0-403b-9077-aed4fb6e885d)

横屏时有生效
![image](https://github.com/MonwF/customiuizer/assets/25398342/e93936ef-8e7c-4059-82f5-f25d096ea487)
![image](https://github.com/MonwF/customiuizer/assets/25398342/550c1eb4-d7f3-4f2e-978a-e6607df54af1)

**Comment by MonwF** [comment]
你的是啥设备？应该是系统不识别成全面屏

**Comment by Qwerto107** [comment]
> 你的是啥设备？应该是系统不识别成全面屏

小米14 Pro
HyperOS 1.0.27

**Comment by MonwF** [comment]
那肯定不会，标题就是全面屏时，比例放开限制。。。

**Comment by Qwerto107** [comment]
> 那肯定不会，标题就是全面屏时，比例放开限制。。。

那有办法增加个设置项，强制使用全面屏布局么

**Comment by MonwF** [comment]
直接搞个magisk的全面屏模块？

**Comment by Qwerto107** [comment]
> 直接搞个magisk的全面屏模块？

我找个magisk模块试试看，之前用 HyperCeiler 模块的时候，有一个设置项 “兼容模式 - 对所有异形屏强制开启完整屏布局”，是可以的，但是和米客的双排状态栏不兼容

**Comment by Qwerto107** [comment]
用 HyperCeiler 的 “系统框架 - 显示 - 隐藏屏幕缺口” 功能解决了，感谢
![image](https://github.com/MonwF/customiuizer/assets/25398342/d58dcd22-a415-4f0b-b8b4-915671ff3e7d)
