### ISSUE TITLE
【建议】建议自定义日期格式设置添加居中按钮

### ISSUE THREAD

**Issue by KIITTID** [MonwF/customiuizer#454]
RT。建议自定义日期格式设置添加时钟设置那种居中按钮，手动调整到居中始终有点对不齐中间。
![Screenshot_2024-03-19-11-32-07-916_name monwf customiuizer](https://github.com/MonwF/customiuizer/assets/32213083/411d9202-6a7d-4014-91a8-ae0600ae5403)
![Screenshot_2024-03-19-11-32-20-162_name monwf customiuizer](https://github.com/MonwF/customiuizer/assets/32213083/228c9b07-c7e0-4c44-b08f-6b988e069e26)

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/14650649/app.zip)

done
