### ISSUE TITLE
关于V23.11.26 清理打开方式菜单勾选淘宝会让淘宝概率启动闪退或者无法点击的问题

### ISSUE THREAD

**Issue by UNSCs117** [MonwF/customiuizer#456]
A13最后1个版本v23.11.26中新增的 系统-其他-清理打开方式菜单 中选择淘宝并勾选全部，会导致手机重启后无论哪个版本的淘宝都会直接闪退，清理全部用户数据后还会概率性打开闪退，如果运气好进去后会发现大部分东西无法点击，包括主页的一堆商品，收藏/历史订单/设置等都无法点击和打开，但是有些地方长按却能有响应。
虽然应该是淘宝自己的问题，但是这个问题在我非常详细地排查后才发现是这个功能的问题并且网络上找不到解决方法。确实A13已经不再发布新版，但我想希望通过类似评论的方式把这个问题说一声，以防有人和我一样碰到这个问题。
作者您可以直接把这个放进已解决。
另外，感谢这个模块让我的小米好用了很多！

**Comment by MonwF** [comment]
感谢 这个挺多人讨论过，去掉链接就行。其他图片之类的可以勾选
