### ISSUE TITLE
米客无法激活

### ISSUE THREAD

**Issue by Geekmemz** [MonwF/customiuizer#457]
![Screenshot_2024-03-24-01-16-41-197_com android shell](https://github.com/MonwF/customiuizer/assets/97420795/c701fd42-9a19-49d2-b81f-19858b43dbac)

![Screenshot_2024-03-24-01-16-41-197_com android shell](https://github.com/MonwF/customiuizer/assets/97420795/e025eb2c-bbc7-4ecf-adb1-0ce6e6d2eddf)
已测试3月版本和一月版本
由于我不小心卸载了米客，在重新安装后无法激活
magisk已给米客root权限(白名单模式），lsp也已激活，但在重启后依然提示未激活
设备为K70Pro,澎湃1.0.13版本
![Screenshot_2024-03-24-01-16-31-552_name monwf customiuizer](https://github.com/MonwF/customiuizer/assets/97420795/da1759bf-69a4-4cd2-8629-d716dfd9aa8b)

**Comment by Geekmemz** [comment]
![Screenshot_2024-03-24-01-16-31-552_name monwf customiuizer](https://github.com/MonwF/customiuizer/assets/97420795/27c408b9-c239-4a84-ae73-b595a2c60109)
补充米客的图片

**Comment by MonwF** [comment]
如果提示LSPosed未激活，请检查米客是否被限制了自启动，系统或者第3方模块。
另外LSPosed版本必须在1.9.2以上

**Comment by Geekmemz** [comment]
![Screenshot_2024-03-24-15-34-03-857_com android shell](https://github.com/MonwF/customiuizer/assets/97420795/f31deb62-9889-4605-8827-533e67d16cf0)
![Screenshot_2024-03-24-15-33-56-577_com miui securitycenter](https://github.com/MonwF/customiuizer/assets/97420795/445b9d64-adaf-44e5-9633-a8e29b7d3c75)
![Screenshot_2024-03-24-15-33-46-971_name monwf customiuizer](https://github.com/MonwF/customiuizer/assets/97420795/1ed0ca1e-198d-4272-8206-f5266dc21192)


> 如果提示LSPosed未激活，请检查米客是否被限制了自启动，系统或者第3方模块。 另外LSPosed版本必须在1.9.2以上

经过检查，lsp为1.9.3，米客已开启自启动，至于系统的自启动没有动过，第三方模块我也没有想到限制自启动的，因为是卸载后重装无法激活

**Comment by MonwF** [comment]
重新安装就要重新开启 99%是自启问题，如thanox之类

**Comment by Geekmemz** [comment]
![Screenshot_2024-03-24-16-19-10-012_com miui securitycenter](https://github.com/MonwF/customiuizer/assets/97420795/a6809d07-a70d-4153-902b-d1b9daeb6951)
![Screenshot_2024-03-24-16-16-42-953_com android shell-edit](https://github.com/MonwF/customiuizer/assets/97420795/1eec1086-7f37-434c-b380-cc1cf40763ac)
thanox已开启自启动 重启后依然无法激活 顺便补一个lsp应用的列表 是否需要补充lsp日志？

**Comment by MonwF** [comment]
是thanox里面，不是thanox的自启动。。不会就去酷安搜下

**Comment by Geekmemz** [comment]
> 是thanox里面，不是thanox的自启动。。不会就去酷安搜下

明白，已成功激活
