### ISSUE TITLE
可以加一个关闭状态栏下拉时钟过渡动画的选项吗

### ISSUE THREAD

**Issue by MonoiF** [MonwF/customiuizer#458]
时钟那个动画过渡好不流畅，看起来很别扭

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/14743991/app.zip)

系统-通知中心-时钟设置

**Comment by EricZhang233** [comment]
> 时钟那个动画过渡好不流畅，看起来很别扭

不顺畅是因为主题原因吧，去隔壁打开[系统界面-状态栏-时钟指示器-修复时钟反色时颜色异常]就可以了，没必要关动画
