### ISSUE TITLE
可否为"~/控制/电源键/双击动作"增加"打开侧边栏"功能

### ISSUE THREAD

**Issue by EricZhang233** [MonwF/customiuizer#459]
如题，因无法忍受全局侧边栏的悬浮条而把侧边栏唤起方式改成了左下角，但现在又忍受不了小白条占用空间，故又把小白条关了，然后发现竖屏状态下仍可以通过左下角唤出侧边栏(即使在系统设置里隐藏了小白条)，但横屏无法唤出。所以我想询问能否在"~/控制/电源键/双击动作"增加"打开侧边栏"功能，开发大大辛苦啦！

**Comment by MonwF** [comment]
没计划加这些，后面可能把现在的向内滑动停顿拆下，底部1/5可以单独设置动作。

**Comment by EricZhang233** [comment]
好的~作者辛苦~

**Comment by EricZhang233** [comment]
> 没计划加这些，后面可能把现在的向内滑动停顿拆下，底部1/5可以单独设置动作。

所以这样的话，是不是就可以在横屏状态下，即使未开启小白条也能用类似底部向内滑动的方式实现呼出全局/场景侧边栏了呢
