### ISSUE TITLE
Clock not moving center/right

### ISSUE THREAD

**Issue by Bamn09** [MonwF/customiuizer#463]
On Xiaomi 14 (1.0.14.0.UNCEUXM).
All clock mods work apart from the horizontal setting.

**Comment by MonwF** [comment]
check your settings

**Comment by Bamn09** [comment]
Can you elaborate, what would I be missing?

**Comment by MonwF** [comment]
how did you set the position? take screenshot please

**Comment by Bamn09** [comment]
Nevermind, found it, what I was looking for is under: "Change icon positions"

**Comment by Bamn09** [comment]
I did "horizontal alignment" in clock settings, but this is something else apparantly.

**Comment by Bamn09** [comment]
Appreciate your fast replies!

**Comment by Bamn09** [comment]
Cup of coffee coming your way through PayPal

**Comment by MonwF** [comment]
> Cup of coffee coming your way through PayPal

thanks

**Comment by Bamn09** [comment]
@MonwF is your PayPal right?

**Comment by MonwF** [comment]
> @MonwF is your PayPal right?

any question?

**Comment by Bamn09** [comment]
My PayPal app is force closing when trying to pay through Pengeek.
So if I search you in Paypal app, I find MonwF, that is you right?

**Comment by MonwF** [comment]
https://paypal.me/tpsxj

**Comment by Bamn09** [comment]
Thank you, it's done!

**Comment by MonwF** [comment]
thanks again

**Comment by Bamn09** [comment]
Hope it's okay to ask here:
Does your app provide an option to hide the green dot showing GPS/Camera etc is being used?
Because I've succesfully moved the clock to the right (thanks again!) but now the green dot is ugly there.
My heating system at home uses geofencing and that makes this green dot showing up a lot.

**Comment by MonwF** [comment]
> Hope it's okay to ask here: Does your app provide an option to hide the green dot showing GPS/Camera etc is being used? Because I've succesfully moved the clock to the right (thanks again!) but now the green dot is ugly there. My heating system at home uses geofencing and that makes this green dot showing up a lot.

ok, maybe later.

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/14892422/app.zip)

system-statusbar-hide icons

**Comment by Bamn09** [comment]
You are the best, thank you!
  

  

  

  
  
  
  
  
>

**Comment by Bamn09** [comment]
A future request if allowed; could we get volume steps settings in pengeek?
