### ISSUE TITLE
2 options not working on hyperos.

### ISSUE THREAD

**Issue by butinhi** [MonwF/customiuizer#467]
1. 5G tile
2. Show refresh rate tile
Pls fix it @MonwF

**Comment by MonwF** [comment]
download again. fixed at few days ago

**Comment by butinhi** [comment]
@MonwF I am on 24.04.13 but not fixed.

**Comment by MonwF** [comment]
did you redownload from releases page again? i uploaded it 3 days ago

**Comment by MonwF** [comment]
"If you can pls add lock fps (refresh rate) option to your project". may be not
