### ISSUE TITLE
最新澎湃 OS 版本 VPN 图标隐藏失败

### ISSUE THREAD

**Issue by kaedea** [MonwF/customiuizer#468]
设置了 VPN 图标隐藏，每次网络切换后又会重新出现。

**Comment by MonwF** [comment]
4.15开发版未复现

**Comment by kaedea** [comment]
> 4.15开发版未复现

小米 14 正式版 HyperOS 1.0.35.0 开始出现问题，1.0.36.0 也同样。

**Comment by kaedea** [comment]
> > 4.15开发版未复现
> 
> 小米 14 正式版 HyperOS 1.0.35.0 开始出现问题，1.0.36.0 也同样。

经过测试，LSP 需要同时对系统界面 & 系统桌面两个 app 启用才能正常 work，如果只对系统界面启用的话就会出现如上问题。
![Screenshot_2024-05-06-18-23-26-441_com.android.shell-edit.jpg](https://github.com/MonwF/customiuizer/assets/3963397/0834639d-8a1f-4897-ad5f-559e9fbdc9bb)

**Comment by MonwF** [comment]
奇怪，看了下代码，确实不需要miuihome的作用域，我试了下取消也能用

**Comment by kaedea** [comment]
> 奇怪，看了下代码，确实不需要miuihome的作用域，我试了下取消也能用

你可以试一下断开重连下 VPN 网络试试，我用的 SurfaceBoard

**Comment by Hydsiun** [comment]
Hyper os2仍无法隐藏VPN图标。
