### ISSUE TITLE
Bottom padding and IME not working 

### ISSUE THREAD

**Issue by RoyaleOne** [MonwF/customiuizer#469]
The change of bottom padding in the menu Various for google keyboard isnt working, it is hooked i made sure and i force stopped gboard many times, it used to work in the previous version 1.0.4.0, another issue is that IME enabling isnt working i hope it gets fixed sometime

Device: Poco x5 pro
Hyperos: 1.0.6.0

**Comment by MonwF** [comment]
i will not fix this bug.
maybe i will remove the feature in the next release

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/15137904/app.zip)

fixed

**Comment by MonwF** [comment]
which feature do you mean about ime? take screenshot pls. Bottom padding for gboard has been  fixed

**Comment by RoyaleOne** [comment]
> which feature do you mean about ime? take screenshot pls. Bottom padding for gboard has been fixed

![Screenshot_2024-04-27-18-27-00-567_com miui gallery-edit](https://github.com/MonwF/customiuizer/assets/68414738/c8c5aa2e-a65f-4456-8264-9e6b97e01737)
This, a feature called enhanced keyboard, but also called IME

**Comment by MonwF** [comment]
i don't think this module has the feature
