### ISSUE TITLE
Request feature: "Apply wallpaper using any app"

### ISSUE THREAD

**Issue by UniverseCodex01** [MonwF/customiuizer#47]
In future updates you can add the function of Apply wallpaper using any app? You can found it in Customiuizer/System/Lock screen and allows to set lock screen wallpapers with any app, for example Google photos. This function only works on A10 and lower. Thanks so much for your work and dedication with Customiuizer fork.

**Comment by MonwF** [comment]
how to set photo as lock screen wallpapers with google photos?

**Comment by UniverseCodex01** [comment]
> how to set photo as lock screen wallpapers with google photos?

With Customiuizer, Apply wallpapers using any app feature  is for set lock screen wallpapers with your preferred gallery app, in my case Google photos

**Comment by UniverseCodex01** [comment]
> 

Maybe you are talking about option to set lock screen wallpapers in Google photos apps, it will appear when you change launcher, in my case I'm Smart launcher V6 user

**Comment by MonwF** [comment]
> > 
> 
> Maybe you are talking about option to set lock screen wallpapers in Google photos apps, it will appear when you change launcher, in my case I'm Smart launcher V6 user

I just installed nova launcher and could set lock screen wallpaper from google photos without customiuizer setting

**Comment by UniverseCodex01** [comment]
> > > 
> > 
> > 
> > Maybe you are talking about option to set lock screen wallpapers in Google photos apps, it will appear when you change launcher, in my case I'm Smart launcher V6 user
> 
> I just installed nova launcher and could set lock screen wallpaper from google photos without customiuizer setting

@MonwF 


Yes works but miui don't detect the change, if you set a lock screen wallpaper with 3rd party galleries, lock screen clock don't change their colour in function of predominant wallpaper colour (black and white) also in wallpaper & personalization section, themes app show lock screen wallpaper applied by miui gallery app and not the wallpaper applied by for example, Google photos app

**Comment by MonwF** [comment]
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9949380/app-release.apk.zip)

try this build

**Comment by UniverseCodex01** [comment]
> [app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9949380/app-release.apk.zip)
> 
> try this build

Fully working, tested on miui 13 EU 22.10.26 and now when I apply wallpaper with Google photos and aves gallery miui lock screen clock colour change between black and white with the wallpaper and wallpaper & personalization shows the new lock screen wallpaper
