### ISSUE TITLE
通知栏无通知时，点击“暂无通知消息”文字会跳转通知设置，希望可以禁用跳转

### ISSUE THREAD

**Issue by wyf1463630616** [MonwF/customiuizer#471]
划掉通知后点击空白处，自动关闭通知栏，经常会误触暂无通知消息，跳转通知设置，希望能禁用跳转
![IMG_20240427_101620](https://github.com/MonwF/customiuizer/assets/57241248/d088eb02-be4b-4f63-ae2c-f8b42e49a26a)

**Comment by wyf1463630616** [comment]
整个水平框内点击都会跳转

**Comment by MonwF** [comment]
直接隐藏掉吧

**Comment by wyf1463630616** [comment]
求教怎么隐藏
