### ISSUE TITLE
与作用域“系统界面”相关的功能会导致熄屏一段时间屏幕解锁后无法使用全面屏手势

### ISSUE THREAD

**Issue by xushet** [MonwF/customiuizer#474]
表现为屏幕解锁后进入桌面或锁屏前停留的app时无法使用全面屏返回和底部上滑手势，通过控制中心点击进入系统设置后手势功能恢复正常，不知道是哪个功能所以只好通过排除作用域的方法排除到“系统界面”后问题消失，大佬知道这是哪个功能引起的吗

——使用环境

型号：小米14
系统版本：1.0.36.0稳定版
基于Android14，安全补丁2024-03-01
root方式：apatch

框架版本：
Zygisk - LSPosed
版本：v1.9.2（7058）
Zygisk Next
版本：v4-0.9.3(283-8d24482-release)

——

**Comment by MonwF** [comment]
试了下，解锁后直接进入停留的app，返回停顿和底部上滑没问题。。。你看下是不是隐藏导航栏导致的？

**Comment by 20171213** [comment]
> 试了下，解锁后直接进入停留的app，返回停顿和底部上滑没问题。。。你看下是不是隐藏导航栏导致的？

![Screenshot_2024-05-20-13-45-48-698_com.example.c001apk.jpg](https://github.com/MonwF/customiuizer/assets/34502902/916c0d4d-eba1-42e8-b05a-ba554d606cd6)

大佬我今天刷酷安也看到有人跟我一样的症状，这个真的没法解决么
https://www.coolapk.com/feed/55370322

**Comment by MonwF** [comment]
你描述的是划不出来，它这个是卡顿，完全不一样的现象。他这个卡顿的问题已经修复
