### ISSUE TITLE
Screenshot file format

### ISSUE THREAD

**Issue by cihaneken** [MonwF/customiuizer#477]
Setting the file format of screenshots to png on Xiaomi 14 Ultra does not work.  Files are always saved in jpg format.

**Comment by MonwF** [comment]
what is the screenshot app version, android screenshot or xiaomi screenshot?

**Comment by cihaneken** [comment]
> ekran görüntüsü uygulama sürümü, android ekran görüntüsü veya xiaomi ekran görüntüsü nedir?



> what is the screenshot app version, android screenshot or xiaomi screenshot?
![Screenshot_2024-05-08-16-47-06-830_com miui securitycenter](https://github.com/MonwF/customiuizer/assets/17432022/ecc91f4f-0c96-4daf-a74a-58f4db3d2177)

**Comment by MonwF** [comment]
i have the same version but it works.
