### ISSUE TITLE
Not working on Hyper OS 1.0.3.0

### ISSUE THREAD

**Issue by Gleb2372372** [MonwF/customiuizer#478]
Версия API
100

Защита использования Xposed API
Не включена

Оптимизатор Dex
Поддерживается

Версия фреймворк LSPosed
1.9.3 (7499)

Имя пакета менеджера
com.android.shell

Версия Android
14 (API 34)

Устройство
Xiaomi Redmi 22101316G 

Разрядность системы (ABI)
arm64-v8a

**Comment by Gleb2372372** [comment]
Not one module in Pengeek is not working. LSPosed works.

**Comment by MonwF** [comment]
1. the minimum version of  lsposed is 1.9.2
2. enable auto start for pengeek

**Comment by Gleb2372372** [comment]
I have LSPosed 1.9.3. Still none of the settings work.
