### ISSUE TITLE
I need your help and knowledge

### ISSUE THREAD

**Issue by UniverseCodex01** [MonwF/customiuizer#48]
![Screenshot_2022-10-27-14-06-33-520_com dp logcatapp](https://user-images.githubusercontent.com/93066706/198367672-d8ec7486-b585-4ec6-a2c9-3d380c4de328.jpg)

As you know in A10 MIUI global and CN use com.android.systemui.ImageWallpaper as home screen wallpaper provider but in EU ROMs deves changed from com.android.systemui.ImageWallpaper to com.miui.miwallpaper.wallpaperservice.Image wallpaper and this generated the impossibility to set home screen wallpapers without MiuiWallpaper app. In EU ROM I want to return WallpaperManagerService from com.miui.miwallpaper.wallpaperservice.Image to
com.android.systemui.ImageWallpaper, I change wallpaper services.jar and frameworks.jar classes by CN classes to return ImageWallpaper but WallpaperManagerService bind Wallpaper Component locked still in com.miui.miwallpaper.wallpaperservice.Image.

Can you tell me what I need to modify to change Bind wallpaper component locked to com.android.systemui.ImageWallpaper? Because I tried by replacing of classes and doesn't work, please help me XD but if you don't want close my issue and no problem, I understand. If you can and want to help me and need the service.jar and Frameworks.jar to check, tell me how can I send you files :) 

@MonwF

**Comment by MonwF** [comment]
i didn't read related source. sorry
