### ISSUE TITLE
下拉通知栏导致系统界面闪退

### ISSUE THREAD

**Issue by yetier55** [MonwF/customiuizer#480]
下拉通知栏这个操作有时会使系统闪退
[com.android.systemui_2024-05-13T09_54_37.411.log](https://github.com/MonwF/customiuizer/files/15310010/com.android.systemui_2024-05-13T09_54_37.411.log)

**Comment by MonwF** [comment]
米客什么版本？只要修改了时间格式，下拉动画可能会触发。。。关闭时钟动画吧，或者不要改时钟格式，系统bug，不好修复

**Comment by yetier55** [comment]
版本24.04.13 OK OK，那我就把时钟动画关了












C
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月15日(周三) 上午8:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MonwF/customiuizer] 下拉通知栏导致系统界面闪退 (Issue #480)




 
米客什么版本？只要修改了时间格式，下拉动画可能会触发。。。关闭时钟动画吧，或者不要改时钟格式，系统bug，不好修复
