### ISSUE TITLE
双排状态栏无法正确显示温度信息

### ISSUE THREAD

**Issue by liwenjie119** [MonwF/customiuizer#481]
如果把网速显示放到第二排，那么设备温度无法显示
![Screenshot_2024-05-23-20-42-37-765_name monwf customiuizer-edit](https://github.com/MonwF/customiuizer/assets/25956275/f5734525-a3e1-40b4-bf98-196b81d76445)
![Screenshot_2024-05-23-20-42-06-793_name monwf customiuizer-edit](https://github.com/MonwF/customiuizer/assets/25956275/98b5f2dd-3320-4f0b-a3ac-d78588e9061f)

**Comment by MonwF** [comment]
有重启系统界面吗？理论上双排时，功率不会显示在上排右边

**Comment by liwenjie119** [comment]
重启界面了，我只有把电池信息和设备温度的右侧显示打开，才能在第二排显示
![IMG_20240523_220712](https://github.com/MonwF/customiuizer/assets/25956275/ce2ab6cb-0534-4528-ab88-9743a96cc18d)

**Comment by liwenjie119** [comment]
> 有重启系统界面吗？理论上双排时，功率不会显示在上排右边

重启了，只有开启设备温度和电池信息时，才能显示到第二排，否则根本不显示
![IMG_20240523_220712](https://github.com/MonwF/customiuizer/assets/25956275/0739ca76-e64c-4af9-b295-92f6df96d854)

**Comment by MonwF** [comment]
如果只开设备温度，不开电池信息，就不会显示？

**Comment by liwenjie119** [comment]
> 如果只开设备温度，不开电池信息，就不会显示？

两个不论哪一个，不开右侧显示，就不会显示，两者不互相影响
![Screenshot_2024-05-23-22-15-21-191_name monwf customiuizer-edit](https://github.com/MonwF/customiuizer/assets/25956275/7037c312-ebc6-49f6-a3cd-44e5ea9bac47)
![Screenshot_2024-05-23-22-15-21-191_name monwf customiuizer-edit](https://github.com/MonwF/customiuizer/assets/25956275/d4a914b0-640a-4a47-bf1b-6accd6ac89b7)

**Comment by MonwF** [comment]
不开网速显示在第2排就正常？你时钟是跨双排显示吗

**Comment by MonwF** [comment]
系统版本？我试了，不开右侧显示，会显示在左侧，没任何问题

**Comment by liwenjie119** [comment]
> 不开网速显示在第2排就正常？你时钟是跨双排显示吗



> 不开网速显示在第2排就正常？你时钟是跨双排显示吗

是的，时钟跨双排。关掉这个显示也不正常，只能开靠右，最新开发板，可能的确与版本有关，

**Comment by MonwF** [comment]
系统版本，不是模块版本
