### ISSUE TITLE
手势--长滑动锁屏BUG

### ISSUE THREAD

**Issue by cyedn1xH** [MonwF/customiuizer#487]
不知道为什么，设置了全屏手势，边沿向内长滑动这个动作设置一个熄屏功能之后，每次开发版更新，一个版本可用，一个版本不可用，梅花间竹的出现不可用的症状表现为震动一下，并没有任何功能出现，然后下个开发版之后又可用了，比较奇怪。

**Comment by MonwF** [comment]
dex优化的问题。。。安装下miuihome就行

**Comment by cyedn1xH** [comment]
> dex优化的问题。。。安装下miuihome就行

请问这个miuihome是啥东东？在哪里找哇？

**Comment by MonwF** [comment]
就是桌面。。重新安装就行

**Comment by cyedn1xH** [comment]
> 就是桌面。。重新安装就行

这样。。。我找找去。。谢谢大佬~

**Comment by cyedn1xH** [comment]
> 就是桌面。。重新安装就行

请问大佬 我尝试过重新下载完整ROM刷一下，还是出现这种问题，上周更新不可用，本周又更新了，这个功能又可用了，是不是代表我直接在本周的系统内提取这个miuihome，下周更新不可用的话，直接安装这个apk即可呢？

**Comment by MonwF** [comment]
是的

**Comment by cyedn1xH** [comment]
> 是的

好的，感谢~
