### ISSUE TITLE
Network speed indicator bug

### ISSUE THREAD

**Issue by erfirya** [MonwF/customiuizer#49]
when I turned on the 'move networkspeed indicator to the right' the network speed indicator mod, 'reduce visibility when inactive' doesn't work. but it was working before on the left side.

**Comment by erfirya** [comment]
![Screenshot_2022-10-28-08-06-26-014_name monwf customiuizer](https://user-images.githubusercontent.com/71990871/198419862-ed5591ef-0820-4ba9-abe4-2070dd23377c.jpg)

**Comment by erfirya** [comment]
btw my device is Xiaomi POCO X3 NFC running xiaomi.eu MIUI 13.0.1 Android 12

**Comment by MonwF** [comment]
i removed this option in the latest build. i have to change alpha of three color with alpha channel. i think that  the option is rarely useful
