### ISSUE TITLE
[Feature Request] Add allow speaker sound feature.

### ISSUE THREAD

**Issue by DevyDesign** [MonwF/customiuizer#492]
Really needed this feature which is missing in Hyper OS but recently available till Miui 14 under Settings/Sound & Vibration/Sound assistant.
Added Screenshot for reference 
![Screenshot_2024-07-03-21-58-44-272_com miui misound](https://github.com/MonwF/customiuizer/assets/60316367/c7540554-dc7d-495b-9090-90a11e577728)

**Comment by MonwF** [comment]
duplicate with https://github.com/MonwF/customiuizer/issues/441. it's a hard work
