### ISSUE TITLE
Problem parsing package 

### ISSUE THREAD

**Issue by LorrdWealth** [MonwF/customiuizer#493]
I can't install the app.. I'm on HyperOS A13. 
What could be the problem?

**Comment by MonwF** [comment]
get the apk for a13

**Comment by LorrdWealth** [comment]
Okay.. but I don't seem to find the perfect version for hyperos android 13.. please help.

**Comment by MonwF** [comment]
there is no perfect version because i don't have the specific device

**Comment by LorrdWealth** [comment]
The 23.12.30 version I have works but the clock background part doesn't work.
