### ISSUE TITLE
AudioVisualizerHook Failed to hook

### ISSUE THREAD

**Issue by illuminatad** [MonwF/customiuizer#5]
[LSPosed_2022-07-11T20_32_28.615.zip](https://github.com/MonwF/customiuizer/files/9084008/LSPosed_2022-07-11T20_32_28.615.zip)

**Comment by MonwF** [comment]
i've made a new version
please try it and give me some feedback

**Comment by illuminatad** [comment]
It's fine now... Thanks dev, I'll report soon if I find any bug.

**Comment by MmyGgithubAaccount** [comment]
Is the visualizer intended to be this blurry?
![IMG_20220712_190533](https://user-images.githubusercontent.com/58236619/178503313-a55aea39-718d-49f4-9687-32fcfc31dfc6.jpg)
![IMG_20220712_190416](https://user-images.githubusercontent.com/58236619/178503364-d764a906-b55c-43e4-b50c-a2a5768c6cb5.jpg)
These are my settings:
![Screenshot_2022-07-12-19-07-32-981_name monwf customiuizer](https://user-images.githubusercontent.com/58236619/178503567-b64ddff3-ca59-4b18-8d70-9ed64e04555a.png)

Device: alioth (Redmi K40/POCO F3/Mi 11X)
MIUI 13 22.7.8

**Comment by illuminatad** [comment]
Yeah, somehow I've just mangaed it to work by adjusting the transparent and glow a little bit

**Comment by MonwF** [comment]
> Is the visualizer intended to be this blurry? ![IMG_20220712_190533](https://user-images.githubusercontent.com/58236619/178503313-a55aea39-718d-49f4-9687-32fcfc31dfc6.jpg) ![IMG_20220712_190416](https://user-images.githubusercontent.com/58236619/178503364-d764a906-b55c-43e4-b50c-a2a5768c6cb5.jpg) These are my settings: ![Screenshot_2022-07-12-19-07-32-981_name monwf customiuizer](https://user-images.githubusercontent.com/58236619/178503567-b64ddff3-ca59-4b18-8d70-9ed64e04555a.png)
> 
> Device: alioth (Redmi K40/POCO F3/Mi 11X) MIUI 13 22.7.8

match album art or wallpaper won't work now. try set color with another option

**Comment by MmyGgithubAaccount** [comment]
@illuminatad could you share your settings?
As for the centred clock, it's one of the built in options in Settings>AoD and Lock Screen>Lock screen clock format

**Comment by illuminatad** [comment]
Yes, I am using custom color right now

**Comment by MmyGgithubAaccount** [comment]
Yes, custom color fixes the issues. Thanks MonwF

**Comment by MmyGgithubAaccount** [comment]
> > @illuminatad could you share your settings? As for the centred clock, it's one of the built in options in Settings>AoD and Lock Screen>Lock screen clock format
> 
> Yes but how did you manage to have a seconds though

It's from another module. Both "ChiMi" and "Woobox for MIUI" have that option. Both can be found in the lsposed module repo

**Comment by MonwF** [comment]
> Yes, custom color fixes the issues. Thanks MonwF

option "match album art or wallpaper" is working now
