### ISSUE TITLE
Please add gap between icon

### ISSUE THREAD

**Issue by backzaa** [MonwF/customiuizer#50]
I have problem with gap between signal icon and battery percent. Can you add some gapp for that?

![IMG_20221028_093649](https://user-images.githubusercontent.com/36920655/198473979-e1c04430-697a-446c-b787-e0921e2ce492.jpg)

**Comment by MonwF** [comment]
down the latest apk

**Comment by backzaa** [comment]
I'm use 22.10.27
This problem occurs when hide battery image.

![IMG_20221028_232406](https://user-images.githubusercontent.com/36920655/198686011-46520d34-d32f-4ad8-b68b-ba472e29f5c5.jpg)

![IMG_20221028_232351](https://user-images.githubusercontent.com/36920655/198686017-8963158f-2d68-47c2-928b-492ed40f0e26.jpg)

**Comment by MonwF** [comment]
get latest apk. you can set right margin then

**Comment by backzaa** [comment]
It's work great 😀
Thank you

![IMG_20221029_114434](https://user-images.githubusercontent.com/36920655/198814378-c8096d0b-262e-42ff-b59d-ca8ec4d858c2.jpg)
