### ISSUE TITLE
HyperOs Android 13 support?

### ISSUE THREAD

**Issue by Byron22HD** [MonwF/customiuizer#502]
I tried to install the apk for my redmi note 11 spes, but it cant be installed

**Comment by Byron22HD** [comment]
I just want Keep phone unlocked in a trusted environment (Bluetooth and Wi-Fi) please

**Comment by MonwF** [comment]
download  the apk for miui14 with !13

**Comment by Byron22HD** [comment]
It didn't work

**Comment by Byron22HD** [comment]
The phone doesn't keep unlocked

**Comment by Byron22HD** [comment]
Can you just add sdk min to 33 and ill test it

**Comment by Byron22HD** [comment]
Oh my i tried again and it worked! Thanks!
