### ISSUE TITLE
最新版双排状态栏不修改锁屏无效

### ISSUE THREAD

**Issue by Xagaboy** [MonwF/customiuizer#503]
最新版双排状态栏设置不修改不生效强制显示双排状态栏并且显示错位
hyperos 1.0.10
![Screenshot_2024-08-07-15-25-03-660_lockscreen.jpg](https://github.com/user-attachments/assets/e0846657-9223-4b76-bf2f-789b16f98f65)

**Comment by MonwF** [comment]
看不懂

**Comment by Xagaboy** [comment]
看我圈起来的图片，在锁屏时显示双排状态栏。我进去设置不修改锁屏状态栏设置无效仍然保持这个样子。解锁后一切正常锁屏这里字体错位![IMG_20240807_154744.jpg](https://github.com/user-attachments/assets/cebaf55e-a8fe-41e6-9f30-bccbe70b69c7)

**Comment by MonwF** [comment]
已更新，重新下载吧
