### ISSUE TITLE
bug:从v22.10.09开始的 记住浮窗状态功能增强，会导致

### ISSUE THREAD

**Issue by wzgrx** [MonwF/customiuizer#51]
从桌面打开任意应用，应用有几率小窗化
不知道能不能把这个 记住浮窗状态功能增强 功能回退一下
![Screenshot_2022-10-28-14-49-15-019_org lsposed manager](https://user-images.githubusercontent.com/39661556/198522873-e6ebd377-9f6b-4716-acc0-4e9f1cd65db5.jpg)
![Screenshot_2022-10-28-14-43-34-514_com hupu games](https://user-images.githubusercontent.com/39661556/198522899-132461a1-ed9b-4b2b-b1ee-a1f42241ccd7.jpg)

**Comment by MonwF** [comment]
要想下次打开不是小窗，你得手动全屏一次

**Comment by wzgrx** [comment]
> 要想下次打开不是小窗，你得手动全屏一次

能不能取消这个功能？感觉没有什么用啊，没个应用都要重新全屏一遍

**Comment by MonwF** [comment]
这个开关就是这个作用的，不想用不要开启就行了

**Comment by chenxiccc** [comment]
你不需要记住小窗状态的功能，你就把这个记住小窗状态的选项关掉就好了呀。
