### ISSUE TITLE
经典控制中心添加的上午中午傍晚等字体太细，和原来的字体粗细不一

### ISSUE THREAD

**Issue by freedomspiritJohn** [MonwF/customiuizer#513]
![Screenshot_2024-08-12-15-03-06-553_com miui home-edit](https://github.com/user-attachments/assets/2f69439b-da8a-4ac9-8e57-1e6204dc6a01)
![Screenshot_2024-08-12-15-03-19-426_com miui home-edit](https://github.com/user-attachments/assets/4cab035f-769f-4ead-bd3a-2d871aad5767)

**Comment by MonwF** [comment]
可能因为它不是系统字体，中英文字体不同导致的

**Comment by freedomspiritJohn** [comment]
> 可能因为它不是系统字体，中英文字体不同导致的

大佬，有没有修改的方法啊，我直接修改系统文件。这样看着很别扭
