### ISSUE TITLE
Not working features and bugs

### ISSUE THREAD

**Issue by kawarask** [MonwF/customiuizer#517]
Hi,

I'm on HyperOS 1.0.12.0.UNCMIXM

What i found using pengeek is that when trying to use old-styled control center (CC) - brightness slider will glitch. CC disappears once you try to adjust it manually. Thus using old CC is not possdible.

Another frustrating bug is that you cannot turn on the feature of old launch animation (revert app opening transition to a previoud one).  Once you turn it on animation remains as it were but adds a sort of useless and unwanted blink when swithching apps.

As far as new CC and stupid animation to previous app are the most hated things about HyperOS, pengeek turns out to be mostly useless =)

**Comment by MonwF** [comment]
legacy cc is deprecated from the hyperos system. so more bugs will appear. pengeek just forces showing the entry. i will remove the switch in the hyperos 2.0
