### ISSUE TITLE
控制 导航栏 长按功能无效与应用标题显示不全

### ISSUE THREAD

**Issue by scnjdx108** [MonwF/customiuizer#522]
![IMG_20240902_001845.jpg](https://github.com/user-attachments/assets/eb203fff-07e0-4c6f-a047-52dbbe502648)

![IMG_20240902_002212.jpg](https://github.com/user-attachments/assets/433586fc-98c6-450b-8927-10cb82c1488e)

![IMG_20240902_003527.jpg](https://github.com/user-attachments/assets/5183aafb-8253-4126-9c61-f99b4deb3d1d)

 系统运行环境 官方 Hyper Os 1.0.4.0 Android 14

**Comment by MonwF** [comment]
hyperos 长按动作的实现逻辑大改了，系统提供的快捷方式不满足吗？

**Comment by scnjdx108** [comment]
> hyperos 长按动作的实现逻辑大改了，系统提供的快捷方式不满足吗？


![Screenshot_2024-09-05-14-28-59-488_com.miui.gallery.png](https://github.com/user-attachments/assets/6bfe2b2d-d0ad-45c2-8bcd-2a0259b62aa4)

如果使用 系统快捷锁屏方式 需要 点两下，先点home键 然后 再点系统快捷锁屏，所以个人认为使用虚拟HOME键 长按锁屏， 才是最方便省事儿 且对实体电源键无损耗的锁屏操作方式！


![Screenshot_2024-09-05-14-32-05-200_com.android.shell-edit.jpg](https://github.com/user-attachments/assets/51f8b821-28f2-4323-93d7-f03ebb1ee644)

**Comment by MonwF** [comment]
双击状态栏也一样呀。虚拟键使用的人较少，而且这个修起来看着也比较麻烦，每次调试都得重启系统，后续可能直接移除了

**Comment by MonwF** [comment]
我发现系统本身就支持长按home键锁屏。。。直接搜按键快捷方式

**Comment by scnjdx108** [comment]
> 双击状态栏也一样呀。虚拟键使用的人较少，而且这个修起来看着也比较麻烦，每次调试都得重启系统，后续可能直接移除了



这个 双击状态栏锁屏 很早多年前就在用了，单手操作不方便，还不如 系统快捷方式锁屏！

**Comment by scnjdx108** [comment]
> 我发现系统本身就支持长按home键锁屏。。。直接搜按键快捷方式


![Screenshot_2024-09-05-14-58-14-506_com.miui.securitycore.jpg](https://github.com/user-attachments/assets/f42a6721-6497-41cd-9c74-1ff84d7e3867)


对，但那是 以前MIUI老版本才是，Hyper OS没有了！

**Comment by MonwF** [comment]
经典导航栏的长按动作已经在hyperos 2里修复
