### ISSUE TITLE
双排状态栏通知图标能否跨双排

### ISSUE THREAD

**Issue by 2315506431** [MonwF/customiuizer#525]
双排状态栏下，时钟可以跨双排，但通知图标不行。
![Screenshot_2024-09-09-00-43-25-352_com.android.settings.jpg](https://github.com/user-attachments/assets/e5f467ea-9c57-4553-9015-2725c7e3926a)

**Comment by MonwF** [comment]
都跨双排显示了 那双排的意义何在

**Comment by 2315506431** [comment]
> 都跨双排显示了 那双排的意义何在

只想要右侧双排提高信息密度，左边本来就没什么东西，所以准确说我想要的是单侧双排
