### ISSUE TITLE
13u 升级到1.0.16后模块失效

### ISSUE THREAD

**Issue by liwenjie119** [MonwF/customiuizer#526]
上次升级到1.0.15后也存在失效问题，但是清除米客数据然后重新设置并重启手机可用了，但是这回升级到1.0.16后，清除数据并重新设置也无法起效，不知道是不是个例

**Comment by liwenjie119** [comment]
附上lsp的日志
[LSPosed_2024-09-14T15_25_13.309956.zip](https://github.com/user-attachments/files/17001447/LSPosed_2024-09-14T15_25_13.309956.zip)

**Comment by MonwF** [comment]
是无法激活吗？

**Comment by liwenjie119** [comment]
> 是无法激活吗？

看到了k60那个issue，我测试了一下，的确是时钟模块问题，关掉时钟设置模块，重启界面后其他的设置都生效了

**Comment by MonwF** [comment]
那就只是系统界面相关的触发安全模式 失效了

**Comment by MonwF** [comment]
有空提取下系统界面apk 我看看

**Comment by liwenjie119** [comment]
> 有空提取下系统界面apk 我看看

[系统界面-com.android.systemui-20230316.0.zip](https://github.com/user-attachments/files/17022385/-com.android.systemui-20230316.0.zip)

**Comment by MonwF** [comment]
[app.zip](https://github.com/user-attachments/files/17053415/app.zip)
试试，这个失效和状态栏时间格式有关
