### ISSUE TITLE
双排状态栏下左侧宽度占比问题

### ISSUE THREAD

**Issue by Qwerto107** [MonwF/customiuizer#529]
您好，**“双排状态栏” - “全面屏设备下左侧宽度占比”** 设置的精度能否提高到两位小数。范围 0 - 0.70，间隔 0.01

![Screenshot_2024-09-20-23-25-51-815_name monwf customiuizer-edit](https://github.com/user-attachments/assets/1dcc2cda-7d84-4dd7-8428-931669d209a0)

**Comment by MonwF** [comment]
没啥计划
