### ISSUE TITLE
show wifi standard bug

### ISSUE THREAD

**Issue by erfirya** [MonwF/customiuizer#53]
wifi standard not displaying correctly. its inconsistent, sometimes it shows 4 even though I'm connected to 5Ghz and vice versa. and sometimes its 0, like in the screenshot.

**Comment by erfirya** [comment]
![Screenshot_2022-10-30-16-11-26-282_name monwf customiuizer](https://user-images.githubusercontent.com/71990871/198869086-4cd58422-ff39-4f08-a803-13d282eecac6.jpg)
![Screenshot_2022-10-30-16-12-08-242_com android settings](https://user-images.githubusercontent.com/71990871/198869091-6b5b6193-c347-4097-96d5-680b13a45c36.jpg)

**Comment by erfirya** [comment]
xiaomi.eu MIUI v13.0.1 Android 12

**Comment by MonwF** [comment]
tap the right arrow to view wifi detail and take screenshot

**Comment by erfirya** [comment]
![Screenshot_2022-10-31-08-25-54-083_com android settings](https://user-images.githubusercontent.com/71990871/198909715-53215dba-4514-45bc-ad96-52c72fa0a210.jpg)
![Screenshot_2022-10-31-08-25-11-750_com android settings](https://user-images.githubusercontent.com/71990871/198909726-09706a0d-63ed-4492-9033-708978df7564.jpg)

**Comment by erfirya** [comment]
while in this, it shows 5 when connected to 2.4G network
![Screenshot_2022-10-31-11-44-54-552_com android settings](https://user-images.githubusercontent.com/71990871/198927155-cabf6782-397d-4ea3-a547-3e8309914066.jpg)

**Comment by MonwF** [comment]
it is a bug from miui. i will try to fix it later

**Comment by erfirya** [comment]
thank you for your work. keep it up

**Comment by MonwF** [comment]
when wifi standard is 0, it is hiding now

**Comment by erfirya** [comment]
just updated the app. its fixed now, it doesn't display 0 anymore and the wifi standard is shown correctly

**Comment by MonwF** [comment]
ok. i will close this issue
