### ISSUE TITLE
Pengeek no support for android 13

### ISSUE THREAD

**Issue by Avinash1234-robotics** [MonwF/customiuizer#530]
There is hyperos android 13, why can't I use it on android 13 then? Pls help..

**Comment by MonwF** [comment]
please download the release for miui14 with  a13

**Comment by Avinash1234-robotics** [comment]
But I wish I could use the new features u added for hyperos

**Comment by Avinash1234-robotics** [comment]
The MIUI 14 version doesn't have that so...

**Comment by MonwF** [comment]
yeah.new features are only for a14. i don't have much time and an a13 device
