### ISSUE TITLE
Bug with back gesture when "Swipe across the screen..." is used

### ISSUE THREAD

**Issue by resiehnnes** [MonwF/customiuizer#535]
There is a bug with back gesture when an action is set in "Controls -> Full screen navigation gestures -> Swipe across the screen..." When I set any action (in my example it is "Open power menu"), and activating it by swiping across the screen, the first back gesture which is used after the power menu is opened does not register, and when I do a second back gesture it performs back gesture two times in a row. I recorded a video so it is easier to understand what's going on.

Xiaomi 14 Ultra, 1.0.12.0.UNAEUXM

Thank you for amazing tweaker to everyone who is involved. 🤝 Donated. ❤️

https://github.com/user-attachments/assets/eda6e2f5-0594-4e35-b5a6-7bedf81e76d8

**Comment by MonwF** [comment]
thanks. if you swipe from the other direction when the power menu is opened, back gesture is normal and power menu can be closed. i will try to fix it later

**Comment by resiehnnes** [comment]
@MonwF This indeed works without needing to use back gesture twice.

I just had a weird thing when back gesture was not working four times, and only registered on fifth try. I was not using "Swipe across the screen..." this time, but am using left and right corner gestures occasionally. Will let you know if I will figure out the pattern what triggers it.

**Comment by MonwF** [comment]
I tried a fix but failed.It is weird that a delay trigger for power menu action doesn't work. it is related to miuihome somehow

**Comment by resiehnnes** [comment]
@MonwF Power menu was just an example. In my case anything that is set to "Swipe across the screen..." gesture after triggering it has this bug (launching app, activity, control panel, etc)

After reading your message I played with the gesture again and for some reason it was working perfectly when I was triggering it from the right side + back gesture from the same side, but was bugged if doing the same from the left side. After that I restarted the launcher and now both sides are bugged again. Is this function related to system launcher (com.miui.home) ? I actually downgraded launcher couple of days ago because the one which came with OTA was bugged (Fix animation in pengeek was not working anymore + broken recents.RecentsActivity), so I had to go back to 4.39.14.8168-07312121 from 4.39.30.8604-08262248. 

Anyways, thank you for attempting to fix it 🤝

**Comment by MonwF** [comment]
the gesture is attached to miuihome. Maybe touch event is broken when the top app has been switched.

**Comment by MonwF** [comment]
[app.zip](https://github.com/user-attachments/files/17809146/app.zip) should fix it.

upgrade miuihome to  version 4.39.30

**Comment by resiehnnes** [comment]
@MonwF Thanks. I tried it and it indeed does fix the problem with "Swipe across the screen" + back gesture, but now whenever I use just "back" gesture (from any side) it triggers action which was used for "Swipe across the screen" gesture, for example, if I have it set to open Control Panel then the regular "back" gesture instead of going back opens Control Panel. I tried different launcher versions 4.39.30.XX and all of them have same problem.

**Comment by MonwF** [comment]
[Pengeek-24.10.12.apk.zip](https://github.com/user-attachments/files/17831881/Pengeek-24.10.12.apk.zip)
please test again

**Comment by resiehnnes** [comment]
@MonwF I can confirm it works great now 👍 Tested with System Launcher V4.39.14.XX and V4.39.30.XX builds. Only minor bug I noticed is the "Do not vibrate" switch doesn't work for me. Other than that very pleased that you found a workaround 👏 Cheers!

![606f3bc3-1acc-47e9-8fb2-87164e1585e6](https://github.com/user-attachments/assets/0b306340-c35a-4797-96fc-1ce20214fb6a)
