### ISSUE TITLE
Add option to disable "Sensitive Permissions Notifications" / Privacy indicator 

### ISSUE THREAD

**Issue by AlexS2412** [MonwF/customiuizer#536]
on xiaomi devices it is tied to the security application and only some versions have the toggle for this. i would prefer it be disabled as i often screencast for long periods and it causes this to appear. if you can add the modifications needed i would be very greatful.
![Screenshot_2024-10-15-19-13-16-962_com miui securitycenter-edit](https://github.com/user-attachments/assets/999f5e9f-a429-4e22-a7ab-87edca123ae9)

it is the com.miui.securitycenter package i believe that controls this.

**Comment by MonwF** [comment]
You can close the proper notification channel. to hide the indicator dot you can do it with peek

**Comment by AlexS2412** [comment]
> You can close the proper notification channel. to hide the indicator dot you can do it with pengeek

can you tell me how to hide the dot please? i could not find such an option. it is why i made the issue. sorry in advance for disturbing you.

**Comment by MonwF** [comment]
Your os version? The option is available in Hyper OS with a14 only

**Comment by AlexS2412** [comment]
> Your os version? The option is available in Hyper OS with a14 only

i am on hyperoa v1.0.6 and android 14. where would i find the setting? security center itself doesn't allow me to change it as privacy awareness doesnt exist in it and i cannot find the setting inside tour application

**Comment by MonwF** [comment]
system - statusbar - hide icons

**Comment by AlexS2412** [comment]
> system - statusbar - hide icons

thank you this works. sorry for the inconvenience.
