### ISSUE TITLE
开启状态时间显秒后有小bug

### ISSUE THREAD

**Issue by 3166265725** [MonwF/customiuizer#54]
通知图标和时间之间的间隙变大，不知道算不算bug，给你提一下。
![103020163683_0IMG_20221030_201508](https://user-images.githubusercontent.com/61723005/198878305-57ce9865-40a2-4dc3-96db-32bcea083c1f.jpg)

**Comment by MonwF** [comment]
不算 本身固定宽度的 防止右边相邻抖动 现在时间里数字1比较多 所以空白间距大点，后续可能会开放配置

**Comment by 3166265725** [comment]
@MonwF 请问作者以后可以增加波纹充电动画吗？

**Comment by MonwF** [comment]
应该不太会加
