### ISSUE TITLE
经典控制中心的截屏按钮不能自动隐藏控制中心

### ISSUE THREAD

**Issue by leifan8440** [MonwF/customiuizer#541]
小米15 澎湃os2 2.0.16
米客版本24.11.11
点截屏只会截到如下
![Screenshot_2024-11-12-01-11-37-471_com miui home](https://github.com/user-attachments/assets/0a0ee7c1-2008-4987-b487-4ada09f5dbb5)

**Comment by MonwF** [comment]
经典控制中心 已经停止维护
