### ISSUE TITLE
Verify method to check the mod is running hyperos 2

### ISSUE THREAD

**Issue by Bamn09** [MonwF/customiuizer#542]
Just hope for a tip, how can i check if the mods are working?
The pengeek section is there in settings, so all seems fine however, i cannot find a setting to try which actually works.

All things im trying dont seem to work, so im doubting my setup now.

**Comment by MonwF** [comment]
if you can see the pengeek entry in settings app, it is working. one tip: if you reinstall the lsposed, you should resync settings to lsp by backup and restore in pengeek

**Comment by Bamn09** [comment]
Hi, thanks for your reply!
  
I backupped and restored, but still many options not working.
  

  
I manages to confirm something that is working, so setup is okay.
  

  
Maybe somethings are not working because off xiaomi.eu rom.
  

  
Most important 3 things for me that are not working:
  
- Privacy green dit (while gps active).
  
- Move clock to right side
  
- Skip 10 sec countdown for some settings (like accessibility)
  

  
Just so you know, appreciate your work and dont except fixes soon.
  

  

  
  
  
  
  
>

**Comment by MonwF** [comment]
In fact, my phone is running on miui eu rom. the three features are working.  Toggle the checkbox may help

**Comment by MonwF** [comment]
sorry. i'm on hyperos 1

**Comment by Bamn09** [comment]
No problem, appreciate all your efforts.
  
If there is something i can do(test) let me know.
  

  

  

  
  
  
  
  
>

**Comment by Bamn09** [comment]
Which checkbox do you mean?
  

  

  

  
  
  
  
  
>

**Comment by Bamn09** [comment]
Which checkbox do you mean?
  

  

  

  
  
  
  
  
>

**Comment by MonwF** [comment]
features switch in the pengeek

**Comment by Bamn09** [comment]
You mean switch off and on again the things i need/like?
  

  
This ive tried.
  

  

  

  
  
  
  
  
>

**Comment by MonwF** [comment]
> You mean switch off and on again the things i need/like? This ive tried.
> […](#)
> On 13 nov 2024 at 11:11, monwf ***@***.***> wrote: features switch in the pengeek — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

yes. i will fix it later

**Comment by Bamn09** [comment]
Ok, no hurries, thanks for your support!
  

  

  

  
  
  
  
  
>

**Comment by MonwF** [comment]
[app.zip](https://github.com/user-attachments/files/17731863/app.zip)

clock postion adjust is fixed. the other two features are working on my test device

**Comment by Bamn09** [comment]
You are the best!   
  
All seem to be working now!
  
Thanks a million!
  

  

  

  
  
  
  
  
>
