### ISSUE TITLE
"Force Enable CC style switch" setting doesn't show up

### ISSUE THREAD

**Issue by resiehnnes** [MonwF/customiuizer#544]
If I understand correctly the meaning of this tweak when I turn on "Force Enable CC style switch" there should appear a "Control centre style" in Settings -> Nootification & status bar (see screenshot), but for some reason it does not work. This tweak does work in HyperCeiler.

Pengeek 24.10.12
Xiaomi 14 Ultra 1.0.13.0.UNAEUXM

![control centre style](https://github.com/user-attachments/assets/efe62ae0-f01d-4f62-b798-1ae1882392b8)

**Comment by MonwF** [comment]
won't fix. if you want new cc style. just turn off from pengeek. this feature will be removed on android 15

**Comment by resiehnnes** [comment]
@MonwF I see, I actually do not use the "old" cc style, just observed that the feature doesn't work. And you mentioned that in another bug report before, should use search first before making bug report. Thanks, looking forward for Android 15 version!

**Comment by MonwF** [comment]
The test release of pengeek is out now. you can get the link from the readme
