### ISSUE TITLE
selective alarm icon visibility not working

### ISSUE THREAD

**Issue by erfirya** [MonwF/customiuizer#55]
like what the title says. i'm not sure if i misunderstood this setting but i think it shouldn't display the alarm icon until its 8 hrs. before the alarm rings. btw i'm using the stock clock app
![Screenshot_2022-11-01-16-53-42-497_name monwf customiuizer](https://user-images.githubusercontent.com/71990871/199197850-5f393463-76d2-47b8-baee-d77ff5ed75a9.jpg)
![Screenshot_2022-11-01-16-53-53-323_com android deskclock](https://user-images.githubusercontent.com/71990871/199197890-4be2787f-6c5e-470c-8bb1-18b17bd8f59d.jpg)

**Comment by erfirya** [comment]
i hope you don't take this badly, you know because lately i've been submitting issues/bugs regarding your app. i just want your app to be better.

**Comment by erfirya** [comment]
its still there. i'm already using the latest version

**Comment by MonwF** [comment]
> its still there. i'm already using the latest version btw. but i've downloaded and installed your attached file just to be sure

restart system ui

**Comment by erfirya** [comment]
i've done that but sadly its not fixed
![Screenshot_2022-11-01-18-35-04-293_com android deskclock](https://user-images.githubusercontent.com/71990871/199214947-1e353d0f-a187-42d9-b3ae-3b7a6aa5700c.jpg)

**Comment by MonwF** [comment]
is it working in a minute?

**Comment by MonwF** [comment]
[app.zip](https://github.com/MonwF/customiuizer/files/9909483/app.zip)

please try gain

**Comment by erfirya** [comment]
just tried it but no luck
![Screenshot_2022-11-01-20-02-57-024_com miui securitycenter](https://user-images.githubusercontent.com/71990871/199228830-274b4b4b-a150-47fc-b322-1d2e9705e5d1.jpg)
![Screenshot_2022-11-01-20-03-03-711_com android deskclock](https://user-images.githubusercontent.com/71990871/199228858-d4ff6d65-9e9b-4e3b-83d5-70ea1ceb1478.jpg)
![Screenshot_2022-11-01-20-03-12-447_name monwf customiuizer](https://user-images.githubusercontent.com/71990871/199228860-bebb4dfd-459b-44df-af44-19b885acfc78.jpg)

**Comment by erfirya** [comment]
i've restarted systemui everytime i change something

**Comment by MonwF** [comment]
try to move icon to right first?

**Comment by erfirya** [comment]
it worked but my camera cutout is in the center so i had to move the network indicator to the left because if i don't it won't have enough space

**Comment by MonwF** [comment]
i will fix it tomorrow. are you from Southeast Asia

**Comment by erfirya** [comment]
thanks really appreciate it. yes i am, why do you ask?

**Comment by MonwF** [comment]
> thanks really appreciate it. yes i am, why do you ask?

because of timzezone. you can try signal in 2 rows btw

**Comment by erfirya** [comment]
sorry but i don't like the look of dual row signal bars. i prefer the default. i think its much better if you could stack them but keep the default design

**Comment by erfirya** [comment]
anyway this is how it looks now. the red dot would be where the camera is
![Screenshot_2022-11-01-21-05-26-054_com teslacoilsw launcher](https://user-images.githubusercontent.com/71990871/199241032-1e4d1cfc-6d4e-41a3-a11a-a67d425aebfb.jpg)
![Screenshot_2022-11-01-21-05-22-598_com teslacoilsw launcher](https://user-images.githubusercontent.com/71990871/199241051-6ef210c2-3fb9-462a-9615-258629ebfdf8.jpg)

**Comment by erfirya** [comment]
i hope you fix it. thanks again

**Comment by MonwF** [comment]
> i hope you fix it. thanks again


[app.zip](https://github.com/MonwF/customiuizer/files/9915142/app.zip)

**Comment by erfirya** [comment]
wow that was fast. its fixed now, thank you for your work 🫡
