### ISSUE TITLE
Multiple issues with A15 (HyperOS2.0)

### ISSUE THREAD

**Issue by Theliel** [MonwF/customiuizer#550]
Magisk v28 + lsposed Delta (same with others fork)

Upgrading from A14 without problems, just a issue with a Magisk module to move certificates to the system (disabled for now). Modules loaded by lsposed work correctly.

Specifically Pengeek (both stable and test versions) work very erratically, most of the functionalities are broken or require several reboots. Shortcuts to reboot launcher/systemUI, dont work either...

Am I missing something? The module installs correctly without giving any apparent error, the detailed log doesn't show much, I'll upload it tomorrow anyway

thank anyway

**Comment by MonwF** [comment]
most features are working on a15. maybe lsposed cleared the prefs
