### ISSUE TITLE
Battery Bar not working

### ISSUE THREAD

**Issue by eng3** [MonwF/customiuizer#554]
I know you list support for Android 14.  I assume you will go up to 15 someday.
I'm running with Xiaomi.eu HyperOS 2.0.13.0 (Android 15)
So I'll start reporting.  Most functions are working fine.
The only thing I haven't been able to get to work is the Battery Bar Indicator.
The strange thing is that the TEST function does work and displays the animation of the battery bar.
Otherwise, nothing is shown

**Comment by MonwF** [comment]
did you try to get the test apk from the tg channel?

**Comment by eng3** [comment]
I didnt know there was a version on the tg channel.
That worked.  Thanks!
