### ISSUE TITLE
Please re add use miui package installer feature.

### ISSUE THREAD

**Issue by RahulXD6T9** [MonwF/customiuizer#6]
![IMG_20220713_144816](https://user-images.githubusercontent.com/101616222/178699467-2b4012c3-1a44-46a8-902b-a6bba8b90fc0.jpg)
I found this one on first build. Can you please re add this feature in future builds. Thank-you. Sorry for bad English.

**Comment by RahulXD6T9** [comment]
> 

I am talking about xiaomi default installer will allow to upgrade system apps. That's missing in latest updates. customiuizer/various/use miui package installer. This one.

**Comment by MonwF** [comment]
> 

get customiuizer-miui13-a12-0713.apk and see if it works (only allow it to update system apps)

**Comment by RahulXD6T9** [comment]
> > > 
> > 
> > 
> > I am talking about xiaomi default installer will allow to upgrade system apps. That's missing in latest updates. customiuizer/various/use miui package installer. This one.
> 
> get customiuizer-miui13-a12-0713.apk and see if it works (only allow it to update system apps)

Thankyou now it's working fine.
