### ISSUE TITLE
Display Next Alarm on lockscreen not working when dual clock enabled

### ISSUE THREAD

**Issue by aravind-alpha07** [MonwF/customiuizer#60]
System-->Lock Screen-->Display Next Alarm 

If dual clock enabled, the above mentioned feature is not working. Please fix this if its not a bug then kindly add this feature when dual clock enabled.
![Screenshot_2022-11-13-14-31-49-050_name monwf customiuizer](https://user-images.githubusercontent.com/93417425/201515136-d49bdf01-ad03-4a04-b488-8978d3c1718a.png)
![Screenshot_2022-11-13-14-31-12-374_lockscreen](https://user-images.githubusercontent.com/93417425/201515259-077d9183-c716-4fe8-85f6-a12222ba8fb3.png)
![Screenshot_2022-11-13-14-31-01-925_lockscreen](https://user-images.githubusercontent.com/93417425/201515272-55cd1284-7435-4012-944f-4820834fa490.png)

**Comment by MonwF** [comment]
[customiuizer13-1115-test.apk.zip](https://github.com/MonwF/customiuizer/files/10013254/customiuizer13-1115-test.apk.zip)

try this build

**Comment by aravind-alpha07** [comment]
> [customiuizer13-1115-test.apk.zip](https://github.com/MonwF/customiuizer/files/10013254/customiuizer13-1115-test.apk.zip)
> 
> try this build

Thanks a lot... It's working now!!

![Screenshot_2022-11-15-19-56-59-946_lockscreen.png](https://user-images.githubusercontent.com/93417425/201947184-d54a73a7-7930-4457-9a98-23f2db4b695d.png)
