### ISSUE TITLE
Support for adding classic widgets in app vault

### ISSUE THREAD

**Issue by aravind-alpha07** [MonwF/customiuizer#61]
Hi proo 1st of all thanks for this great module. I'm back with another #feature_request hope you consider this too. 

Can you add support for 

1. **Adding (drag & drop) classic widgets (Android widgets) in app vault (-1 screen)** 

2. **Hide MIUI widgets title under MIUI widgets in home screen (if possible)**

I have to use another module **(MIUIHOME)** just for this single feature.. it would be nice if you add this.. Thanks in advance

![IMG_20221115_205212.jpg](https://user-images.githubusercontent.com/93417425/201959602-9b5ad17d-89da-4254-b289-2a87dcace307.jpg)

![IMG_20221115_205130.jpg](https://user-images.githubusercontent.com/93417425/201960392-d02718ed-4460-4894-846c-0203abd796ef.jpg)

**Comment by MonwF** [comment]
why not just keep using miuihomer? it's focus on miui home. these features are not planned now, sorry

**Comment by aravind-alpha07** [comment]
> why not just keep using miuihomer? it's focus on miui home. these features are not planned now, sorry

Thats only one feature i use in that module so I thought if added i can uninstall that. Okay no problem thank you btw.

**Comment by MonwF** [comment]
lastest miui launcher add the feature, remove widget text
