### ISSUE TITLE
CostoMIUI

### ISSUE THREAD

**Issue by Joseph070707** [MonwF/customiuizer#62]
hi, can I add a function to move the network icons to the left and remove the clock, or the ability to drag the clock to any position?
![Screenshot_2022-11-19-15-41-16-762-edit_name monwf customiuizer](https://user-images.githubusercontent.com/118602153/202846702-dad4bde0-9579-452b-9822-01d7c7f339d7.jpg)

**Comment by MonwF** [comment]
you can move clock to right of the battery icon only

**Comment by MonwF** [comment]
not planned
