### ISSUE TITLE
3 rows at control center- Fingerprint scanner shortcuts doesn't work

### ISSUE THREAD

**Issue by NC503** [MonwF/customiuizer#63]
Hi mate. Congrats for your hard work. You're the man!

Can we change the row number at the new control center?

And Fingerprint scanner actions doesn't work for me.

Miui 13.0.7 /a12/ sweet global/ 8-128

![Screenshot_2022-11-19-22-39-03-917_com opera browser](https://user-images.githubusercontent.com/96506619/202868485-47580dc2-e8d0-4408-b111-fa4ad8314710.jpg)
![Screenshot_2022-11-19-22-39-17-100_name monwf customiuizer](https://user-images.githubusercontent.com/96506619/202868498-1968038b-8a5c-4c9b-804a-b30fd58b3813.jpg)

**Comment by MonwF** [comment]
fingerprint actions are not working because my phone dosen't support. i'll add 3 rows in cc later

**Comment by NC503** [comment]
Maybe my phone doesn't support too . What's your model?

**Comment by MonwF** [comment]
> Maybe my phone doesn't support too . What's your model?

i mean that I can't fix fingerprint related features. it's broken for all models

**Comment by NC503** [comment]
Okay bro.

**Comment by NC503** [comment]
Thanks at all

**Comment by MonwF** [comment]
control center supports custom rols and rows now

**Comment by NC503** [comment]
I saw bro it works perfectly. You re the man. Btw can you add more options than 5, such as 4 or 3 for rows?

**Comment by MonwF** [comment]
> I saw bro it works perfectly. You re the man. Btw can you add more options than 5, such as 4 or 3 for rows?

minimum rows can be set to 3 now
