### ISSUE TITLE
Feature: call volume shortcut at the call screen

### ISSUE THREAD

**Issue by NC503** [MonwF/customiuizer#64]
Hi bro, can we add volume shortcut to the call screen? 
![Screenshot_2022-11-20-07-37-56-528_com android incallui](https://user-images.githubusercontent.com/96506619/202885855-430d8844-191f-40ec-917f-d2d065bc86a2.jpg)

**Comment by MonwF** [comment]
add left volume icon to open volume dialog?

**Comment by NC503** [comment]
This icon opens handsfree mode(speaker).. Maybe it can be add that long press action opens call volume dialog... In this situation, we won't need to use hardware volume buttons..
