### ISSUE TITLE
双排网速/信号上下间隔太小

### ISSUE THREAD

**Issue by actforjason** [MonwF/customiuizer#65]
如图，字交叉在一块了，能调节吗？
MIUI稳定版13.0.41
![Screenshot_2022-11-20-12-29-41-899_com.coolapk.market.png](https://user-images.githubusercontent.com/57058325/202885948-fff441b9-9df6-4edd-931d-1611d3409d43.png)

**Comment by MonwF** [comment]
文字调小点

**Comment by MonwF** [comment]
确实 当显示箭头的时候显示不太友好

**Comment by MonwF** [comment]
[customiuizer13-1121-test.apk.zip](https://github.com/MonwF/customiuizer/files/10052782/customiuizer13-1121-test.apk.zip)

试下这个包

**Comment by actforjason** [comment]
应该跟字体有关系，用的Misans，行距比较小

**Comment by MonwF** [comment]
> 应该跟字体有关系，用的Misans，行距比较小

嗯，我现在重新调了下，misans没问题了，试下

**Comment by actforjason** [comment]
没问题了
