### ISSUE TITLE
更新后无限重启卸载后正常

### ISSUE THREAD

**Issue by Cross0ver** [MonwF/customiuizer#66]
没有什么log了
3303177935@qq.com

**Comment by MonwF** [comment]
至少系统版本、app从哪个版本更新到哪个版本，开启了哪些功能得说下吧 让我猜 我也不知道是啥 还没日志

**Comment by Cross0ver** [comment]
功能的话太多没法记
![Screenshot_2022-11-20-13-04-46-582_com android settings](https://user-images.githubusercontent.com/54066704/202886559-ec05cef4-08df-4fe4-8120-40f5944f78e3.jpg)
系统版本如图
软件应该是10月份的版本具体哪个拿不准应该是1020

**Comment by Cross0ver** [comment]
> 功能的话太多没法记 ![Screenshot_2022-11-20-13-04-46-582_com android settings](https://user-images.githubusercontent.com/54066704/202886559-ec05cef4-08df-4fe4-8120-40f5944f78e3.jpg) 系统版本如图 软件应该是10月份的版本具体哪个拿不准应该是1020



> 至少系统版本、app从哪个版本更新到哪个版本，开启了哪些功能得说下吧 让我猜 我也不知道是啥 还没日志

https://github.com/MonwF/customiuizer/issues/66#issuecomment-1321040557

**Comment by Cross0ver** [comment]
> 功能的话太多没法记 ![Screenshot_2022-11-20-13-04-46-582_com android settings](https://user-images.githubusercontent.com/54066704/202886559-ec05cef4-08df-4fe4-8120-40f5944f78e3.jpg) 系统版本如图 软件应该是10月份的版本具体哪个拿不准应该是1020

刚才忙着干饭去了实属抱歉

**Comment by MonwF** [comment]
你对着最近的更新日志，把新功能都不开启试下

**Comment by MonwF** [comment]
10月底某个版本开启图标显示在右侧时，确实会重启。你是升级到11月的版本也发生了重启吗
