### ISSUE TITLE
中孔屏状态栏右侧图标会自动隐藏

### ISSUE THREAD

**Issue by actforjason** [MonwF/customiuizer#68]
例如这样，虽然右侧还有很大空间，但是加个闹钟图标后，网速就隐藏了，不能更接近中孔，造成空间浪费。
![Screenshot_2022-11-21-17-04-36-995_com.github.android.png](https://user-images.githubusercontent.com/57058325/203009594-3af355de-20ed-4065-b605-107748d7def2.png)

**Comment by MonwF** [comment]
很大空间是多少

**Comment by actforjason** [comment]
截图上看不出来，直观上能放下一个闹钟⏰的空间

**Comment by actforjason** [comment]
![IMG_20221121_173644_edit_1114850269598113.jpg](https://user-images.githubusercontent.com/57058325/203017675-a3179e17-c84b-416c-83a8-2cc2d240bb21.jpg)

**Comment by MonwF** [comment]
现在是闹钟图标加进去了？如果网速文字较宽，会隐藏？

**Comment by actforjason** [comment]
理想情况是稍微遮挡些也没关系，或者状态栏右边距可以缩小

**Comment by actforjason** [comment]
闹钟加进去后网速隐藏，有一大片空白
![Screenshot_2022-11-21-18-09-09-986_com.miui.home.png](https://user-images.githubusercontent.com/57058325/203023701-5b10d934-dc6a-4ebb-aace-02f67773ee7c.png)

**Comment by actforjason** [comment]
或者看这张图，恰好有闹钟又有又有网速的临界状态，此时网速如果多增加一位就会消失，但是可以看到中孔边缘还是有三个字左右的空间

**Comment by MonwF** [comment]
现在左侧是有预留一定的空白间距(3dp)的，你可以去掉试下，我没设备，如果你开启了网速间距，这个更大

**Comment by actforjason** [comment]
没有开启网速间距。3dp的开关在哪里，这里好像没有
![Screenshot_2022-11-21-18-38-37-451_name.monwf.customiuizer.png](https://user-images.githubusercontent.com/57058325/203029928-2f3636a4-bf54-4220-a8cc-951f22e2081a.png)

**Comment by actforjason** [comment]
不过3dp我感觉还是小了点，另外建议可不可以让网速取整数，小数点没必要，还容易看错

**Comment by MonwF** [comment]
> 现在左侧是有预留一定的空白间距(3dp)的，你可以去掉试下，我没设备，如果你开启了网速间距，这个更大

去掉3dp 没代码，写死的 你可以自己编译。确实，不是m的情况下，小数意义不大

**Comment by actforjason** [comment]
我觉得m也不需要小数，小数部分是kb，现在流量都很多，也没有意义，网速也很难超过GB/s

**Comment by actforjason** [comment]
> 我觉得m也不需要小数，小数部分是kb，现在流量都很多，也没有意义，网速也很难超过GB/s

这个可能仁智互见，设个选项话可能不错

**Comment by MonwF** [comment]
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/10056083/app-release.apk.zip)

移除了3dp，看下能不能放下

**Comment by actforjason** [comment]
> [app-release.apk.zip](https://github.com/MonwF/customiuizer/files/10056083/app-release.apk.zip)
> 
> 移除了3dp，看下能不能放下

这个好像强制把时间移到右边了，修改不管用

**Comment by MonwF** [comment]
这个没有动时间，只改了网速

**Comment by actforjason** [comment]
![Screenshot_2022-11-21-19-45-18-925_name.monwf.customiuizer.png](https://user-images.githubusercontent.com/57058325/203043596-f740ac77-dc11-4c71-8040-8323c6c33ac2.png)

**Comment by MonwF** [comment]
时间右移，开关没开也会生效？？？

**Comment by actforjason** [comment]
确实，我手机重启了也还是这样

**Comment by MonwF** [comment]
完全没动到这块代码，看下有没其他模块？重启系统界面就行

**Comment by actforjason** [comment]
不好意思是我开了其他模块😣。

不过情况好像并没改善，xx.x kb/s再多加一位就消失了

**Comment by MonwF** [comment]
这3dp可能不够显示一位的，可能孔周围的安全区确实比较大，先这样吧
