### ISSUE TITLE
Floating from notification center

### ISSUE THREAD

**Issue by 3zozHashim** [MonwF/customiuizer#69]
it would be cool if an option to open as floating was added when long pressing the notifications in notifications center.

As always, great module, great work, thank you very much 👍

![Screenshot_2022-11-23-03-32-34-961_com mi android globallauncher](https://user-images.githubusercontent.com/115328790/203453799-8f5aa2f7-6f44-413e-9558-e431d2bf6774.png)

**Comment by MonwF** [comment]
maybe in future release. You can slide down the notification to open app in floating window now

**Comment by 3zozHashim** [comment]
> maybe in future release. You can slide down the notification to open app in floating window now

great, thank you!

yeah, you can slide down the heads-up notification to open floating window but once the heads-up is gone, you can forget ever opening the notifications as floating.

**Comment by MonwF** [comment]
> Btw, I wana ask where we find option to enable extra toggle for that, like after long press we see more option including force to stop option and app info option from notification pannel only, I think I have seen this option somewhere but now unable to find... Or may be it was in some other lspossed module, idk but I know there was one option like that, which was really usefull atleast for me..
> 
> If found then surely tell me...

disable app in detail page?

**Comment by Ankit2502** [comment]
![Screenshot_2022-12-12-11-54-52-819_com android chrome](https://user-images.githubusercontent.com/89592455/206975874-fe51cc0f-f4af-4539-8eae-1730fc3bc132.jpg)
I was talking about this one, got it in system/notification

**Comment by MonwF** [comment]
> ![Screenshot_2022-12-12-11-54-52-819_com android chrome](https://user-images.githubusercontent.com/89592455/206975874-fe51cc0f-f4af-4539-8eae-1730fc3bc132.jpg) I was talking about this one, got it in system/notification
> 
> Btw, can u do something of scrolling screenshot. It doesn't work in landscape mode, in apps, even in website I rarely see it working.. I have tab and usually use it in landscape mode... Hopefully any solution to that...

maybe i'll replace 'force close' to open in floating window

**Comment by Ankit2502** [comment]
> > ![Screenshot_2022-12-12-11-54-52-819_com android chrome](https://user-images.githubusercontent.com/89592455/206975874-fe51cc0f-f4af-4539-8eae-1730fc3bc132.jpg) I was talking about this one, got it in system/notification
> > Btw, can u do something of scrolling screenshot. It doesn't work in landscape mode, in apps, even in website I rarely see it working.. I have tab and usually use it in landscape mode... Hopefully any solution to that...
> 
> maybe i'll replace 'force close' to open in floating window

If you want to add new tile that's would be great but replacing force to close will not, as I use that force to kill lot... Also floting window can be opened by just swipe down from the pill shown bellow notification so that's not necessarily, but if you think u had to then just always give option to select force to close option or floating window option...😇

**Comment by 3zozHashim** [comment]
> > ![Screenshot_2022-12-12-11-54-52-819_com android chrome](https://user-images.githubusercontent.com/89592455/206975874-fe51cc0f-f4af-4539-8eae-1730fc3bc132.jpg) I was talking about this one, got it in system/notification
> > Btw, can u do something of scrolling screenshot. It doesn't work in landscape mode, in apps, even in website I rarely see it working.. I have tab and usually use it in landscape mode... Hopefully any solution to that...
> 
> maybe i'll replace 'force close' to open in floating window

yay!



> > > ![Screenshot_2022-12-12-11-54-52-819_com android chrome](https://user-images.githubusercontent.com/89592455/206975874-fe51cc0f-f4af-4539-8eae-1730fc3bc132.jpg) I was talking about this one, got it in system/notification
> > > Btw, can u do something of scrolling screenshot. It doesn't work in landscape mode, in apps, even in website I rarely see it working.. I have tab and usually use it in landscape mode... Hopefully any solution to that...
> > 
> > 
> > maybe i'll replace 'force close' to open in floating window
> 
> If you want to add new tile that's would be great but replacing force to close will not, as I use that force to kill lot... Also floting window can be opened by just swipe down from the pill shown bellow notification so that's not necessarily, but if you think u had to then just always give option to select force to close option or floating window option...😇

😢

**Comment by MonwF** [comment]
[customiuizer13-230103-test.apk.zip](https://github.com/MonwF/customiuizer/files/10337681/customiuizer13-230103-test.apk.zip)

get this build and feedback @Ankit2502 @3zozHashim

**Comment by 3zozHashim** [comment]
> [customiuizer13-230103-test.apk.zip](https://github.com/MonwF/customiuizer/files/10337681/customiuizer13-230103-test.apk.zip)
> 
> get this build and feedback @Ankit2502 @3zozHashim

Awesome! works great.

Thank you for your continuous support!

![IMG_20230103_184330](https://user-images.githubusercontent.com/115328790/210401661-93609e64-23b6-40e8-a0e7-65e7e294f82d.png)

![IMG_20230103_184340](https://user-images.githubusercontent.com/115328790/210401682-8043126c-5885-48ff-a025-843ca1b34d63.png)

**Comment by Ankit2502** [comment]
Yeah, it is little glitchy on miui pad but working great
