### ISSUE TITLE
Some hooks that are not working

### ISSUE THREAD

**Issue by MmyGgithubAaccount** [MonwF/customiuizer#7]
Device: alioth (Redmi K40/POCO F3/Mi 11X)
Android 12
MIUI 13 22.7.12

The following hooks are not working:

~**Auto brightness range**~ 65fff24c8214d5d68dde39530f3a9618d57c9ef7
~Brightness always maxes out on enabling this hook~

~~**Notification volume slider**~~ 9ff00065f8c13b3a235364f14f7af79c24ac84dc
~~`[ 2022-07-14T13:54:26.307     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][NotificationVolumeDialogHook] Failed to hook initDialog method in com.android.systemui.miui.volume.MiuiVolumeDialogImpl`~~

~~**Extended timers for silent and DND**~~ 255a1929b6800f70a4442da880ad70a79fa5a403
~~Doesn't work. Timer levels stay the same in the expanded notification panel~~

~**Show icon and label for toasts**~ b9dad579e5429e595790af24ac8aaa747dea92a8
~`[ 2022-07-14T13:54:24.998     1000:  4379:  4379 I/LSPosed-Bridge  ] [CustoMIUIzer][IconLabelToastsHook] Failed to hook addAppName method in android.widget.ToastInjector`~

~**Disable VoWiFi icon**~ f1c47730d32b2fc223e90aa0bdd170b71821d4db
~`[ 2022-07-14T12:35:34.483     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][HideIconsVoWiFiHook] Failed to hook apply method in com.android.systemui.statusbar.SignalClusterView`~

~~**Detailed network speed indicator**~~ 6608f7dc1ba2e4a3e202fad9ba75f4dfaf90a52d
~~`[ 2022-07-14T13:54:26.267     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][DetailedNetSpeedHook] Failed to hook onTextChanged method in com.android.systemui.statusbar.NetworkSpeedView`
`[ 2022-07-14T13:54:26.268     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][DetailedNetSpeedHook] Failed to hook com.android.systemui.statusbar.NetworkSpeedView constructor`
`[ 2022-07-14T13:54:26.270     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][DetailedNetSpeedHook] No NetworkSpeed view or controller`~~

**Show Illuminance Text**
`[ 2022-07-14T12:35:34.449     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][BrightnessLuxHook] Failed to hook constructor in com.android.systemui.settings.ToggleSliderView`
`[ 2022-07-14T12:35:34.450     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][BrightnessLuxHook] Failed to hook constructor in com.android.systemui.miui.controlcenter.QCToggleSliderView`
`[ 2022-07-14T12:35:34.457     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][BrightnessLuxHook] Failed to hook setListening method in com.android.systemui.miui.controlcenter.QSControlCenterPanel`
`[ 2022-07-14T12:35:34.457     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][BrightnessLuxHook] Failed to hook updateResources method in com.android.systemui.miui.controlcenter.QSControlCenterPanel`
`[ 2022-07-14T12:35:34.458     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][BrightnessLuxHook] Failed to hook onScreenTurnedOff method in com.android.systemui.statusbar.phone.StatusBar`
`[ 2022-07-14T12:35:34.464     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][BrightnessLuxHook] Failed to hook onScreenTurnedOn method in com.android.systemui.statusbar.phone.StatusBar`

~~**Show brightness percentage**~~ 69b56b9c24fb6d4252113d154e1e930bb3fda8ae
~~`[ 2022-07-14T13:54:26.331     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][BrightnessPctHook] Failed to hook showMirror method in com.android.systemui.miui.controlcenter.policy.QCBrightnessMirrorController`
`[ 2022-07-14T13:54:26.332     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][BrightnessPctHook] Failed to hook hideMirror method in com.android.systemui.miui.controlcenter.policy.QCBrightnessMirrorController`
`[ 2022-07-14T13:54:26.332     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][BrightnessPctHook] Failed to hook onChanged method in com.android.systemui.settings.BrightnessController`~~

~**Change calendar app from notifications/control center** (this was working until very recently. Not sure when this broke)~ 8d3a3f0fca8647122baf28d8b7063afdfbba01ff
~`[ 2022-07-14T12:35:34.484     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][ReplaceCalendarAppHook] Failed to hook onFinishInflate method in com.android.systemui.statusbar.HeaderView`~

**Keep Notification after unlock**
`[ 2022-07-14T12:35:34.398     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][ShowNotificationsAfterUnlockHook] Failed to hook hasShownAfterUnlock method in com.android.systemui.miui.statusbar.ExpandedNotification`
`[ 2022-07-14T12:35:34.399     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][ShowNotificationsAfterUnlockHook] Failed to hook setHasShownAfterUnlock method in com.android.systemui.miui.statusbar.ExpandedNotification`

**More notifications from single app**
`[ 2022-07-14T13:54:26.359     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][MoreNotificationsHook] Failed to hook shouldRemove method in com.android.systemui.statusbar.NotificationData`

**Disable any notifications**
`[ 2022-07-14T13:54:15.546     1000:  2272:  2272 I/LSPosed-Bridge  ] [CustoMIUIzer][DisableAnyNotificationBlockHook] Failed to hook setBlockableSystem method in android.app.NotificationChannel`

**Compact Notifications** (this is seems to be doing *something.* Notifications take *slightly* less space after enabling this)
`[ 2022-07-14T12:35:34.405     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][CompactNotificationsHook] Failed to hook wrap method in com.android.systemui.statusbar.notification.NotificationViewWrapper`
`[ 2022-07-14T12:35:34.405     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][CompactNotificationsHook] Failed to hook setGoogleContentMargins method in com.android.systemui.statusbar.notification.NotificationTemplateViewWrapper$GoogleStyleProcessor`
`[ 2022-07-14T12:35:34.407     1000:  4629:  4629 I/LSPosed-Bridge  ] [CustoMIUIzer][CompactNotificationsHook] Failed to hook setMiuiContentMargins method in com.android.systemui.statusbar.notification.NotificationTemplateViewWrapper$MiuiStyleProcessor`

**Minimalistic collapsed view**
`[ 2022-07-14T13:54:26.389     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][MinimalNotificationViewHook] Failed to hook updateNotification method in com.android.systemui.statusbar.phone.StatusBar`

~**Open channel settings**~ 383e1bf3b5556706061f570fbe5e1ec8c02a8cde
~`[ 2022-07-14T13:54:26.390     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][NotificationChannelSettingsHook] Failed to hook onClickMenuSettings method in com.android.systemui.statusbar.phone.StatusBar`~

**MultiWindow+**
`[ 2022-07-14T13:54:26.361     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][MultiWindowPlusNativeHook] Failed to hook onBusEvent method in com.android.systemui.recents.views.RecentMenuView`

**Album art as lockscreen wallpaper**
`[ 2022-07-14T13:54:26.270     1000:  4538:  4538 I/LSPosed-Bridge  ] [CustoMIUIzer][LockScreenAlbumArtHook] No getLockWallpaper(Cache) methods found`

**No password after boot** (my device is unencrypted)
`[ 2022-07-14T13:54:15.543     1000:  2272:  2272 I/LSPosed-Bridge  ] [CustoMIUIzer][NoPasswordHook] Failed to hook isBiometricAllowedForUser method in com.android.internal.widget.LockPatternUtils$StrongAuthTracker`

**Fingerprint scanner long press action**
`[ 2022-07-14T13:54:16.024     1000:  2272:  2272 I/LSPosed-Bridge  ] [CustoMIUIzer][FingerprintEventsHook] Failed to hook startClient method in com.android.server.biometrics.BiometricServiceBase`
`[ 2022-07-14T13:54:16.024     1000:  2272:  2272 I/LSPosed-Bridge  ] [CustoMIUIzer][FingerprintEventsHook] Failed to hook removeClient method in com.android.server.biometrics.BiometricServiceBase`

**Comment by MmyGgithubAaccount** [comment]
Also, how do I grant these permissions to the app?

https://github.com/MonwF/customiuizer/blob/6cac1fc5fc307346a7f5fb8865271998df0e51c6/app/src/main/java/name/mikanoshi/customiuizer/subs/System.java#L550-L563

**Comment by MonwF** [comment]
thanks for the feedback. i will gradually fix bugs

**Comment by MonwF** [comment]
> 

you dont need to grant all these perms manually.
i'll add them to AndroidManifest

**Comment by MonwF** [comment]
> Also, how do I grant these permissions to the app?
> 
> https://github.com/MonwF/customiuizer/blob/6cac1fc5fc307346a7f5fb8865271998df0e51c6/app/src/main/java/name/mikanoshi/customiuizer/subs/System.java#L550-L563

you dont need to grant all these perms manually.
i'll add them to AndroidManifest

**Comment by MonwF** [comment]
bugs listed above are almost fixed and you can test them.
 Except below:
 > Show Illuminance Text: useless, maybe just leave it
 > MultiWindow+ 
 > Album art as lockscreen wallpaper: hard, pr is welcome
 > Fingerprint scanner long press action: without a featured phone

**Comment by MonwF** [comment]
fixed:
MultiWindow+
Album art as lockscreen wallpaper

**Comment by MmyGgithubAaccount** [comment]
Closing since most of these seem to be working now
