### ISSUE TITLE
无法隐藏状态栏HD图标

### ISSUE THREAD

**Issue by vumb5j** [MonwF/customiuizer#70]
环境：k30s，MIUI 13.0.6

重现方式见录屏：
[https://user-images.githubusercontent.com/107930956/203755928-db0bc89b-b469-4f8f-875e-ca7c286f9a70.mp4](https://user-images.githubusercontent.com/107930956/203755928-db0bc89b-b469-4f8f-875e-ca7c286f9a70.mp4)

**Comment by MonwF** [comment]
是重启了系统界面吗？

**Comment by vumb5j** [comment]
> 是重启了系统界面吗？

是的。重启手机也不行

**Comment by MonwF** [comment]
> > 是重启了系统界面吗？
> 
> 是的。重启手机也不行

蓝奏下载最新测试版试下，重启系统界面就行了

**Comment by vumb5j** [comment]
经测试，蓝奏11.22.24版仍然无效。

重现过程见录屏：

[https://user-images.githubusercontent.com/107930956/203836067-dc18bec0-9515-40be-b408-8e34f5261210.mp4](https://user-images.githubusercontent.com/107930956/203836067-dc18bec0-9515-40be-b408-8e34f5261210.mp4)

**Comment by MonwF** [comment]
lsposed里面有没错误日志，有开启其他模块不

**Comment by MonwF** [comment]
先把双排关掉试下

**Comment by MonwF** [comment]
> 经测试，蓝奏11.22.24版仍然无效。
> 

再下载11.25试下

**Comment by vumb5j** [comment]
最新版关闭双排信号后依然无效

详细日志：
`----part 5 start----
[ 2022-11-25T15:01:24.519        0:   859:  2002 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2022-11-25T15:01:24.518.log
[ 2022-11-25T15:01:29.623        0:   859:  1925 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2022-11-25T15:01:29.624        0:   859:  2002 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2022-11-25T15:01:29.624.log
[ 2022-11-25T15:02:09.177        0:   859:  1925 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2022-11-25T15:02:09.178        0:   859:  2002 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2022-11-25T15:02:09.178.log
[ 2022-11-25T15:02:46.519     1000: 18091: 18091 I/LSPosed         ] Loading xposed for com.android.systemui/1000
[ 2022-11-25T15:02:46.522     1000: 18091: 18091 I/LSPosed-Bridge  ] Loading module name.monwf.customiuizer from /data/app/~~hTFdhzzmTnmCxosz6ENzWg==/name.monwf.customiuizer-oR-2dm7-gb7yvq32i-k81Q==/base.apk
[ 2022-11-25T15:02:46.533     1000: 18091: 18091 I/LSPosed-Bridge  ]   Loading class name.mikanoshi.customiuizer.MainModule
[ 2022-11-25T15:02:46.651     1000: 18091: 18091 I/LSPosed-Bridge  ] [CustoMIUIzer][BackGestureAreaHeightHook] Cannot hook GestureStubView
[ 2022-11-25T15:02:46.652     1000: 18091: 18091 I/LSPosed-Bridge  ] [CustoMIUIzer][NoSilentVibrateHook] Failed to hook vibrateH method in com.android.systemui.miui.volume.MiuiVolumeDialogImpl
[ 2022-11-25T15:02:49.095        0:   859:  1925 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 144)
[ 2022-11-25T15:02:49.151        0:   859: 18295 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 148)
[ 2022-11-25T15:02:49.154        0:   859: 18297 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 132)
[ 2022-11-25T15:02:49.173        0:   859: 18298 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 152)
[ 2022-11-25T15:02:49.321        0:   859:  1776 I/lspd            ] Background concurrent copying GC freed 232607(15MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 7738KB/15MB, paused 83us total 184.185ms
[ 2022-11-25T15:04:57.591        0:   859: 18340 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2022-11-25T15:04:57.593        0:   859:  2002 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2022-11-25T15:04:57.592.log
[ 2022-11-25T15:05:20.506     1000: 19158: 19158 I/LSPosed         ] Loading xposed for com.android.systemui/1000
[ 2022-11-25T15:05:20.509     1000: 19158: 19158 I/LSPosed-Bridge  ] Loading module name.monwf.customiuizer from /data/app/~~hTFdhzzmTnmCxosz6ENzWg==/name.monwf.customiuizer-oR-2dm7-gb7yvq32i-k81Q==/base.apk
[ 2022-11-25T15:05:20.520     1000: 19158: 19158 I/LSPosed-Bridge  ]   Loading class name.mikanoshi.customiuizer.MainModule
[ 2022-11-25T15:05:20.632     1000: 19158: 19158 I/LSPosed-Bridge  ] [CustoMIUIzer][BackGestureAreaHeightHook] Cannot hook GestureStubView
[ 2022-11-25T15:05:20.633     1000: 19158: 19158 I/LSPosed-Bridge  ] [CustoMIUIzer][NoSilentVibrateHook] Failed to hook vibrateH method in com.android.systemui.miui.volume.MiuiVolumeDialogImpl
[ 2022-11-25T15:05:22.792        0:   859: 19353 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 116)
[ 2022-11-25T15:05:22.918        0:   859:  1776 I/lspd            ] Background young concurrent copying GC freed 139239(9228KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 9160KB/15MB, paused 113us total 120.708ms
[ 2022-11-25T15:05:23.065        0:   859: 19359 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 132)
[ 2022-11-25T15:05:23.204        0:   859:  1776 I/lspd            ] Background concurrent copying GC freed 219050(14MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 4023KB/8047KB, paused 111us total 153.208ms
[ 2022-11-25T15:06:05.094        0:   859: 16826 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2022-11-25T15:06:05.096        0:   859:  2002 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2022-11-25T15:06:05.095.log
[ 2022-11-25T15:06:34.192        0:   859: 16826 I/LSPosedLogcat   ] !!refresh_modules!!
[ 2022-11-25T15:06:34.194        0:   859:  2002 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/modules_2022-11-25T15:06:34.193.log
[ 2022-11-25T15:07:10.000     1000: 19954: 19954 I/LSPosed         ] Loading xposed for com.android.systemui/1000
[ 2022-11-25T15:07:10.003     1000: 19954: 19954 I/LSPosed-Bridge  ] Loading module name.monwf.customiuizer from /data/app/~~hTFdhzzmTnmCxosz6ENzWg==/name.monwf.customiuizer-oR-2dm7-gb7yvq32i-k81Q==/base.apk
[ 2022-11-25T15:07:10.014     1000: 19954: 19954 I/LSPosed-Bridge  ]   Loading class name.mikanoshi.customiuizer.MainModule
[ 2022-11-25T15:07:10.116     1000: 19954: 19954 I/LSPosed-Bridge  ] [CustoMIUIzer][BackGestureAreaHeightHook] Cannot hook GestureStubView
[ 2022-11-25T15:07:10.117     1000: 19954: 19954 I/LSPosed-Bridge  ] [CustoMIUIzer][NoSilentVibrateHook] Failed to hook vibrateH method in com.android.systemui.miui.volume.MiuiVolumeDialogImpl
[ 2022-11-25T15:07:12.386        0:   859: 16826 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 140)
[ 2022-11-25T15:07:12.391        0:   859: 16826 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 140)
[ 2022-11-25T15:07:12.475        0:   859:  1776 I/lspd            ] Background young concurrent copying GC freed 29540(1747KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 12MB/12MB, paused 74us total 103.913ms
[ 2022-11-25T15:07:12.500        0:   859: 20171 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 144)
[ 2022-11-25T15:07:12.502        0:   859: 20171 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 144)
[ 2022-11-25T15:07:12.554        0:   859: 16826 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 132)
[ 2022-11-25T15:07:12.558        0:   859: 16826 E/JavaBinder      ] !!! FAILED BINDER TRANSACTION !!!  (parcel size = 132)
[ 2022-11-25T15:07:12.597        0:   859:  1776 I/lspd            ] Background concurrent copying GC freed 179752(11MB) AllocSpace objects, 0(0B) LOS objects, 49% free, 6767KB/13MB, paused 2.635ms total 121.778ms`

录屏：

https://user-images.githubusercontent.com/107930956/203924150-570bf22a-8d93-48aa-8818-a499f1d67066.mp4

**Comment by MonwF** [comment]
试着关闭 振动-不振动测试 试下？

**Comment by vumb5j** [comment]
关闭不振动测试后仍然无效：


https://user-images.githubusercontent.com/107930956/203927056-f8fabaa3-4a92-4865-9cf8-9f4437570b9b.mp4

**Comment by MonwF** [comment]
如果能提供下systemui apk，或许能排查下

**Comment by vumb5j** [comment]
/system_ext/priv-app/MiuiSystemUI/MiuiSystemUI.apk


[MiuiSystemUI.zip](https://github.com/MonwF/customiuizer/files/10089748/MiuiSystemUI.zip)

**Comment by MonwF** [comment]
没看出什么异常的，有用主题吗？第1例这个开关无效的，试下其他模块看能否隐藏呢？

**Comment by vumb5j** [comment]
经测试乌堆可隐藏，它有三个HD选项，可能与此有关。

https://www.coolapk.com/apk/com.lt2333.simplicitytools
https://github.com/Simplicity-Team/WooBoxForMIUI

![20ed794c65f26bbee4f8e3bc503cf07](https://user-images.githubusercontent.com/107930956/203945092-14cbebeb-5508-49b5-b706-ee4c2f4c426d.jpg)

**Comment by MonwF** [comment]
感觉代码没啥区别。。。 先用它吧

**Comment by vumb5j** [comment]
经测试，将miui升级至1.0.7后问题解决

**Comment by MonwF** [comment]
这个真的很神奇。能否帮忙测试下扩展电源菜单是否生效？

**Comment by vumb5j** [comment]
扩展电源无效，日志如图
![Screenshot_2022-11-25-21-15-13-982-edit_com android shell](https://user-images.githubusercontent.com/107930956/203993610-83b63e13-ec77-4c6d-83f1-e016196a7944.jpg)

**Comment by MonwF** [comment]
这条错误无关，下载最新的之后，重启系统界面了吗？

**Comment by vumb5j** [comment]
> 这条错误无关，下载最新的之后，重启系统界面了吗？

刚试了下3小时前的最新版，已经可以用了

**Comment by MonwF** [comment]
感谢测试，还修复了音量弹窗相关和静音切换振动关闭的bug
