### ISSUE TITLE
Brightness automatically goes down every time I open control center on mi pads

### ISSUE THREAD

**Issue by Ankit2502** [MonwF/customiuizer#74]
The issue is that whenever I open notification panel or control centre the brightness automatically reduced to zero doesn't matter if auto brightness is on or not, I did some work around and found out that this issue usually occurs when I enable show brightness percentage mode...[well not sure as it also occured all time when I mess up with my control center like enabling weather in control center or shows second...]

Sometimes even idk what trigger

https://user-images.githubusercontent.com/89592455/204817950-8365d81c-4b68-430f-a470-c7925b631826.mp4

 this bug... But only solution I found to remove customisermiui13 completely and then reupdate/flash device with latest frimware...

Hope developers will fix this issue as soon as possible...

**Comment by MonwF** [comment]
try to turn off brightness limit and show brightness percent?

**Comment by Ankit2502** [comment]
It doesn't mainly occur due to that it occurs automatically when I mess up with status bar or control center settings, 

And right now I have flash whole new frimware, hence not having this bug anymore and I don't even want to... But still if I face it then definitely try that out and tell u result..

[ Even after flashing rom again when I installed customiser again and did some tweaking I was having this issue then I disable multiple statusbar tweak and control center tweak including brightness limit and shower... After reboot problem was fixed...]

**Comment by MonwF** [comment]
try to turn off statusbar gesture control @Ankit2502

**Comment by Ankit2502** [comment]
Not facing this issue anymore simple solution I found never to turn on brightness label.

**Comment by Ankit2502** [comment]
> try to turn off statusbar gesture control @Ankit2502

I did that and it fixes the issue, enabling it, bring the issue back

**Comment by Ankit2502** [comment]
> try to turn off brightness limit and show brightness percent?

It's already off, I did not enable it...

**Comment by MonwF** [comment]
it caused by turning on show pct. i fixed it in the latest version. you can use gesture conctrol now. but show pct is in bug

**Comment by Ankit2502** [comment]
> it caused by turning on show pct. i fixed it in the latest version. you can use gesture conctrol now. but show pct is in bug

After update, it not working anymore but yeah not giving any issues too...
