### ISSUE TITLE
Round rect cc

### ISSUE THREAD

**Issue by R9TRH** [MonwF/customiuizer#75]
In the last update you added round rectangle control center style, but it's not showing menu, and if I try to open it via searching, customiuizer crashes.

**Comment by MonwF** [comment]
send me lsp log?
in system - quick settings, scroll down to the bottom

**Comment by MonwF** [comment]
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/10133178/app-release.apk.zip)

**Comment by R9TRH** [comment]
> [app-release.apk.zip](https://github.com/MonwF/customiuizer/files/10133178/app-release.apk.zip)

Thanks! This APK fixed issue.
