### ISSUE TITLE
Floating Window mods don't work on A12 MIUI 13

### ISSUE THREAD

**Issue by ThePlayer14** [MonwF/customiuizer#78]
I have a Redmi 10C (`220333QNY`), "`rain`" phone. This originally came with A11-based MIUI 13, with the ROM version `13.0.7.0.RGEEUXM`. The ROM version `13.0.3.0.RGEEUXM` did not have Floating window blacklisting, but the `13.0.7.0.RGEEUXM` version started using it. The CustoMIUIzerMod fork of the original utility worked well with the A11-based one, but then now, the A12-based `13.0.3.0.SGEEUXM` update became available, and the Floating window blacklisting is seemingly back. Is there something that can be done to try and fix this problem?

**Comment by MonwF** [comment]
i can't test and fix it for you now

**Comment by MonwF** [comment]
blacklist removal is ok on every tester's device with a12.
