### ISSUE TITLE
Open With Dialog "Remember my choice"

### ISSUE THREAD

**Issue by anuraag488** [MonwF/customiuizer#79]
Hi
Can you bring back "Remember my choice" check box on open with dialog. It used to present on MIUI 12.5 roms but on MIUI 13.0 it's removed.

https://i.imgur.com/76BB5An.jpg

**Comment by 3zozHashim** [comment]
> Hi Can you bring back "Remember my choice" check box on open with dialog. It used to present on MIUI 12.5 roms but on MIUI 13.0 it's removed.
> 
> https://i.imgur.com/76BB5An.jpg

delete mi browser

when you click more, you'll get the list of apps and you'll get remember my choice

if you delete mi browser, you'll get the list of apps by default

**Comment by anuraag488** [comment]
My MIUI rom doesn't contain Mi Browser.

**Comment by 3zozHashim** [comment]
> My MIUI rom doesn't contain Mi Browser.

but the image says mi browser?

**Comment by anuraag488** [comment]
> > My MIUI rom doesn't contain Mi Browser.
> 
> but the image says mi browser?

I have just copied image from Google Search to show that checkbox.
