### ISSUE TITLE
Seconds issue

### ISSUE THREAD

**Issue by yxngazvest** [MonwF/customiuizer#80]
Hi, is there any fix to this issue?

![IMG_20221216_005055](https://user-images.githubusercontent.com/91827106/207990691-7e201d4d-233d-4c82-b523-4f89aafec1e1.jpg)

**Comment by MonwF** [comment]
the clock textview has a fixed with now. its max width is calculated based on digits 6 and 8 in mi sans font. in next version i will add extra width tweak

**Comment by MonwF** [comment]
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/10253522/app-release.apk.zip)
increase extra width  in settings
