### ISSUE TITLE
状态栏显示电流增加仅充电时显示

### ISSUE THREAD

**Issue by 778897** [MonwF/customiuizer#82]
希望这个状态栏显示电流上再增加一个仅在充电时显示的开关，不充电时隐藏，同时可以再加个电流永远为正数，不会在充电时电流变成负数
![7e86e98c3c7f2e470ca099cddbd04d36](https://user-images.githubusercontent.com/41319890/208247727-f4b38095-b327-4e59-9781-b183aea8158e.jpg)

**Comment by MonwF** [comment]
已添加 仅在充电时显示
网盘里下载
