### ISSUE TITLE
快速设置面板上滑还有通知面板

### ISSUE THREAD

**Issue by actforjason** [MonwF/customiuizer#83]
MIUI14设置导航键长按显示快速设置面板，不能直接返回而是显示通知面板![Screenshot_2022-12-19-18-50-18-698_name.monwf.customiuizer.png](https://user-images.githubusercontent.com/57058325/208410488-2ca9d8ee-0686-451c-b11d-dc41e8c3424e.png)

**Comment by MonwF** [comment]
新版控制中心还是旧版

**Comment by MonwF** [comment]
网盘下载最新版

**Comment by actforjason** [comment]
解决了，感谢
