### ISSUE TITLE
freeze on unlocking

### ISSUE THREAD

**Issue by anuraag488** [MonwF/customiuizer#85]
Hi
My device freezes after unlocking. I have relock and unlock device to make my device work. So there is some hook causing problem.
Can you add some logging so that i can see what's causing freeze?

**Comment by MonwF** [comment]
may be caused by double tap gesture in statusbar? try to turn off it

**Comment by MonwF** [comment]
> I'm not using double tap gesture. I think it's caused by HideProximityWarningHook

ok. glad that you solved it

**Comment by anuraag488** [comment]
Ok i have solved the problem. I have blocked prepareHintWindow method instead of showHint method and it working fine. You should change the method used in HideProximityWarningHook.

**Comment by MonwF** [comment]
> Ok i have solved the problem. I have blocked prepareHintWindow method instead of showHint method and it working fine. You should change the method used in HideProximityWarningHook.

thanks. i will add later. btw, can you explain the function?

**Comment by anuraag488** [comment]
`    public void prepareHintWindow() {
        FrameLayout frameLayout = new FrameLayout(new ContextThemeWrapper(this.mContext, 16973931));
        this.mHintContainer = frameLayout;
        frameLayout.setOnTouchListener(new View.OnTouchListener() { // from class: com.android.server.policy.MiuiScreenOnProximityLock.3
            @Override // android.view.View.OnTouchListener
            public boolean onTouch(View v, MotionEvent event) {
                MiuiScreenOnProximityLock.this.forceShow();
                return MiuiScreenOnProximityLock.DEBUG;
            }
        });
        WindowManager.LayoutParams lp = new WindowManager.LayoutParams(-1, -1, 2009, 25366784, -3);
        lp.inputFeatures |= 4;
        lp.layoutInDisplayCutoutMode = EVENT_PREPARE_VIEW;
        lp.gravity = 17;
        lp.setTitle("ScreenOnProximitySensorGuide");
        WindowManager wm = (WindowManager) this.mContext.getSystemService("window");
        wm.addView(this.mHintContainer, lp);
        this.mKeyguardDelegate.enableUserActivity(false);
    }`

This is what written on prepareHintWindow method. I think it's creating blocking window. showHint method only shows ways to remove that blocking window.

**Comment by MonwF** [comment]
> ` public void prepareHintWindow() { FrameLayout frameLayout = new FrameLayout(new ContextThemeWrapper(this.mContext, 16973931)); this.mHintContainer = frameLayout; frameLayout.setOnTouchListener(new View.OnTouchListener() { // from class: com.android.server.policy.MiuiScreenOnProximityLock.3 @Override // android.view.View.OnTouchListener public boolean onTouch(View v, MotionEvent event) { MiuiScreenOnProximityLock.this.forceShow(); return MiuiScreenOnProximityLock.DEBUG; } }); WindowManager.LayoutParams lp = new WindowManager.LayoutParams(-1, -1, 2009, 25366784, -3); lp.inputFeatures |= 4; lp.layoutInDisplayCutoutMode = EVENT_PREPARE_VIEW; lp.gravity = 17; lp.setTitle("ScreenOnProximitySensorGuide"); WindowManager wm = (WindowManager) this.mContext.getSystemService("window"); wm.addView(this.mHintContainer, lp); this.mKeyguardDelegate.enableUserActivity(false); }`
> 
> This is what written on prepareHintWindow method. I think it's creating blocking window. showHint method only shows ways to remove that blocking window.

how can i test this mod? i dont know what's the meaning with the option?

**Comment by anuraag488** [comment]
I have only blocked that method. The code written above is copied from miui-services.jar. 

```
public static void HideProximityWarningHook(LoadPackageParam lpparam) {
        Helpers.findAndHookMethod("com.android.server.policy.MiuiScreenOnProximityLock", lpparam.classLoader, "prepareHintWindow", XC_MethodReplacement.DO_NOTHING);
    }
```

**Comment by MonwF** [comment]
> I have only blocked that method. The code written above is copied from miui-services.jar.
> 
> ```
> public static void HideProximityWarningHook(LoadPackageParam lpparam) {
>         Helpers.findAndHookMethod("com.android.server.policy.MiuiScreenOnProximityLock", lpparam.classLoader, "prepareHintWindow", XC_MethodReplacement.DO_NOTHING);
>     }
> ```

explain the switch notc code

**Comment by anuraag488** [comment]
> > I have only blocked that method. The code written above is copied from miui-services.jar.
> > ```
> > public static void HideProximityWarningHook(LoadPackageParam lpparam) {
> >         Helpers.findAndHookMethod("com.android.server.policy.MiuiScreenOnProximityLock", lpparam.classLoader, "prepareHintWindow", XC_MethodReplacement.DO_NOTHING);
> >     }
> > ```
> 
> explain the switch notc code

I couldn't understand what you mean. I have already explained [here](https://github.com/MonwF/customiuizer/issues/85#issuecomment-1367656288) what's written on framework. I'm not a coder to explain much further. I have tested this method with xprivacylua app.

**Comment by MonwF** [comment]
> > > I have only blocked that method. The code written above is copied from miui-services.jar.
> > > ```
> > > public static void HideProximityWarningHook(LoadPackageParam lpparam) {
> > >         Helpers.findAndHookMethod("com.android.server.policy.MiuiScreenOnProximityLock", lpparam.classLoader, "prepareHintWindow", XC_MethodReplacement.DO_NOTHING);
> > >     }
> > > ```
> > 
> > 
> > explain the switch notc code
> 
> I couldn't understand what you mean. I have already explained [here](https://github.com/MonwF/customiuizer/issues/85#issuecomment-1367656288) what's written on framework. I'm not a coder to explain much further. I have tested this method with xprivacylua app.

i don't understand the description in customiuizer. i want to know how the switch works?

**Comment by anuraag488** [comment]
![2022-12-30-07-11-07](https://user-images.githubusercontent.com/7353086/210026260-19c67c7a-2e81-483c-a42c-ee0d2e0562c8.png)

**Comment by MonwF** [comment]
> System > Other > ![2022-12-30-07-11-07](https://user-images.githubusercontent.com/7353086/210026260-19c67c7a-2e81-483c-a42c-ee0d2e0562c8.png)

how can i trigger this kind of warning?

**Comment by anuraag488** [comment]
> > System > Other > ![2022-12-30-07-11-07](https://user-images.githubusercontent.com/7353086/210026260-19c67c7a-2e81-483c-a42c-ee0d2e0562c8.png)
> 
> how can i trigger this kind of warning?
![1562102043_pocket-mode](https://user-images.githiubusercontent.com/7353086/210030440-a3e21baf-ace1-4b35-986a-86635b89d006.jpg)

It triggers on dark places and when miui think touches are done accidentally. So usually it will trigger on night.
This is how it looks when it triggers.

**Comment by MonwF** [comment]
ok. i change the hook in commit 0df5816154968c807f5befba58501652d4fc044a. thanks again
