### ISSUE TITLE
bug 录屏画面极小

### ISSUE THREAD

**Issue by 778897** [MonwF/customiuizer#86]
在原生支持屏幕录制90帧的机型上开启强制解锁90
![Screenshot_2022-12-23-23-03-11-277_com miui video](https://user-images.githubusercontent.com/41319890/209356986-46cf9173-9467-4482-a45b-3ef6e77e77f5.jpg)
，会导致录屏的画面贼小。

**Comment by MonwF** [comment]
已经支持 90fps，强制开启，不打算修了
