### ISSUE TITLE
BUG Screen Lock MIUI 14

### ISSUE THREAD

**Issue by sq-dev** [MonwF/customiuizer#88]
![Screenshot_2022-12-26-10-48-50-214_name.monwf.customiuizer.png](https://user-images.githubusercontent.com/79777081/209508373-58a7603d-5135-49e4-b227-6d9dfbe97607.png)

![Screenshot_2022-12-26-10-49-07-714_lockscreen.jpg](https://user-images.githubusercontent.com/79777081/209508389-b4d460a8-64e4-4a29-a6ec-6b89f07e99cb.jpg)

**Comment by MonwF** [comment]
fixed in commit fe93a48e6ca508dc1426e1a032ee41da6e3e0334
