### ISSUE TITLE
希望添加，强制关闭智能剪切板的功能

### ISSUE THREAD

**Issue by XY50** [MonwF/customiuizer#89]
希望添加，强制关闭智障剪切板的功能，目前找不到可以关闭MIUI14智障剪切板的模块
![Screenshot_2022-12-26-18-23-08-840_com lbe security miui](https://user-images.githubusercontent.com/121076219/209538027-5c17e4dc-7524-45d6-8d86-9e63cca70b0d.png)

**Comment by MonwF** [comment]
不显示这个确认，默认行为是拒绝？

**Comment by XY50** [comment]
> 不显示这个确认，默认行为是拒绝？

默认只有拒绝，我要全部始终允许，手动改的话要一个个的弄好麻烦

**Comment by XY50** [comment]
https://s.xiaomi.cn/c/NMVXM8gA?channel=Share
  
https://s.xiaomi.cn/c/YBSXhrC4?channel=Share

看看这两个帖子底下的评论，就知道这个智能剪贴板有多烦了，以前MIUI13还可以手动关闭，现在MIUI14都没法关

**Comment by MonwF** [comment]
这样默认允许好危险。。。那还不如加个批量允许的功能

**Comment by XY50** [comment]
把这个MIUI14被隐藏的选项显示出来就行了，关闭之后弹窗就变成始终允许或拒绝了
![f6d05e335a1c0c0c3707f84d817ad3a2](https://user-images.githubusercontent.com/121076219/210103112-d49c217a-5481-4c59-b014-8b2e020d8e60.jpeg)
![Screenshot_2022-12-31-02-46-53-077_com miui securitycenter](https://user-images.githubusercontent.com/121076219/210103128-1bd431df-94c1-4073-b92f-039063d9667d.png)

**Comment by MonwF** [comment]
看代码得稳定版自动有剪切板保护和模糊定位，而且混淆很多 即使加了开关 可能下个版本的手机管家就又失效了，建议直接使用魔改版手机管家。。我现在是eu，也不方便测试

**Comment by XY50** [comment]
修改版的管家MIUI14用不了，安装之后无限重启救砖模块都救不回来

**Comment by MonwF** [comment]
> 修改版的管家MIUI14用不了，安装之后无限重启救砖模块都救不回来

酷安上一堆人发修改的，应该能用吧，magisk刷入

**Comment by XY50** [comment]
我就是刚才用模块刷入的无限重启，看了一下评论区也有和我一样的
![Screenshot_2022-12-31-19-33-54](https://user-images.githubusercontent.com/121076219/210135281-05cb8b9a-a2b3-4fc2-94e9-9d8b45ce8018.png)
![Screenshot_2022-12-31-19-33-11](https://user-images.githubusercontent.com/121076219/210135290-741958c3-cffc-4187-91d1-ce121a6f9ba0.png)

**Comment by MonwF** [comment]
单独的核心破解，然后直接安装

**Comment by MonwF** [comment]
下载app-debug.apk，mtk音量模糊+剪切板隐私保护开关都添加了。分别在系统-声音和杂项里

**Comment by XY50** [comment]
完美
![Screenshot_2023-01-02-17-27-17-426_com miui securitycenter](https://user-images.githubusercontent.com/121076219/210213793-a4da3aea-23c8-4d67-abc7-539067fc5a27.png)

**Comment by XY50** [comment]
@MonwF 好像不太行关闭后过段时间又自动打开了

**Comment by MonwF** [comment]
这个估计开发版都这样，目前只是让开关可见，功能可用
