### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by fres-a** [MonwF/customiuizer#9]
broken apk or now only for a12?
![Screenshot_2022-08-03-21-28-44-744_com google android packageinstaller](https://user-images.githubusercontent.com/37847673/182683100-c5ad016f-b445-4b3c-a75e-fed7ce7fbae7.jpg)
![Screenshot_2022-08-03-21-31-39-065_com android settings](https://user-images.githubusercontent.com/37847673/182683220-085cd68a-116c-473a-9bad-a7a013f3bf63.jpg)

**Comment by fres-a** [comment]
try from github and lanzouv

**Comment by MonwF** [comment]
> try from github and lanzouv

limit to android 12 from version 0802
you can set minsdk and build it by yourself

**Comment by fres-a** [comment]
ok, thx

**Comment by vonguyenkhang** [comment]
> limit to android 12 from version 0802 you can set minsdk and build it by yourself

What are the considerations that lead to the decision of limiting to Android 12? 
For laymen as me, it's not easy to build themselves. There's no guide to build in the readme yet (if there's a guide, it needs to be maintained by the developers also).

**Comment by MonwF** [comment]
> 

i don't have a phone with android 11.  
There are many forks that are focus on android 11

**Comment by vonguyenkhang** [comment]
> i don't have a phone with android 11. There are many forks that are focus on android 11

I see. You don't want to release without actual testing on the real devices.
However, it's also very time consuming (and maybe impossible) to do the exhaustive test on every device before every release. For many other open-source projects, the developers can only test on whatever device available on hand, and let the end-users provide feedback if there's issue on other devices.
What are the risks of releasing without testing on Android 11? If the risks are low, would you consider to add the Disclaimer in the readme that "**_This CustoMIUIzer fork is mainly intended for Android 12. MIUI based on Android 11 are not guaranteed to be working and will not receive support_**" ? The reason is that I've tried one other fork [CustoMIUIzerMod](https://github.com/liyafe1997/CustoMIUIzerMod) and there are more broken features than this fork.

**Comment by MonwF** [comment]
> I see. You don't want to release without actual testing on the real devices. However, it's also very time consuming (and maybe impossible) to do the exhaustive test on every device before every release. For many other open-source projects, the developers can only test on whatever device available on hand, and let the end-users provide feedback if there's issue on other devices. What are the risks of releasing without testing on Android 11? If the risks are low, would you consider to add the Disclaimer in the readme that "**_This CustoMIUIzer fork is mainly intended for Android 12. MIUI based on Android 11 are not guaranteed to be working and will not receive support_**" and lower the `minsdk`? The reason is that I've tried one other fork [CustoMIUIzerMod](https://github.com/liyafe1997/CustoMIUIzerMod) and there are more broken features than this fork (I'm using [v220714](https://github.com/MonwF/customiuizer/releases/tag/v220712) on Redmi Note 9 Pro Global (joyeuse)).

I don't have enough time to maintain two versions. this is the question. you can try to contact the maintainer of [CustoMIUIzerMod](https://github.com/liyafe1997/CustoMIUIzerMod)

**Comment by vonguyenkhang** [comment]
> I don't have enough time to maintain two versions. this is the question. you can try to contact the maintainer of [CustoMIUIzerMod](https://github.com/liyafe1997/CustoMIUIzerMod)

I thought it's just lowering the ```minsdk``?

**Comment by MonwF** [comment]
> > I don't have enough time to maintain two versions. this is the question. you can try to contact the maintainer of [CustoMIUIzerMod](https://github.com/liyafe1997/CustoMIUIzerMod)
> 
> I thought it's just lowering the `minsdk`?

can you help test it? just ensure that it can be launched

**Comment by vonguyenkhang** [comment]
> > > I don't have enough time to maintain two versions. this is the question. you can try to contact the maintainer of [CustoMIUIzerMod](https://github.com/liyafe1997/CustoMIUIzerMod)
> > 
> > 
> > I thought it's just lowering the `minsdk`?
> 
> can you help test it? just ensure that it can be launched

Gladly!

**Comment by MonwF** [comment]
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9378925/app-release.apk.zip)

**Comment by vonguyenkhang** [comment]
> [app-release.apk.zip](https://github.com/MonwF/customiuizer/files/9378925/app-release.apk.zip)

![Screenshot_2022-08-19-11-22-06-328_name monwf customiuizer](https://user-images.githubusercontent.com/15910168/185536275-116a62f6-60b9-4356-bfb3-8c7ad1128d51.png)
- Can launch (LSPosed requires reboot after installation)
- Screenshot save as PNG works (although file extension is `.JPG` but not really an issue)
- Other features are not tested
