### ISSUE TITLE
BUG. Display battery temp and current. MIUI 13

### ISSUE THREAD

**Issue by YurKa336** [MonwF/customiuizer#91]
The temperature and current data are overlaid on the telecommunications operator data on the lock screen.  It would be nice if there was a separate button to turn off the temperature and current on the lock screen.
![IMG_20221229_135731](https://user-images.githubusercontent.com/107347313/209948879-8f582a01-fdde-4e8e-ae99-3d67b92835c7.jpg)

**Comment by MonwF** [comment]
it should be hidden on lockscreen. your rom? show your settings

**Comment by YurKa336** [comment]
Redmi Note 10 pro. MIUI Global 13.0.16
![Screenshot_2022-12-29-14-21-23-380_name monwf customiuizer](https://user-images.githubusercontent.com/107347313/209951411-c7298df2-33fc-4254-87b4-eadc3283d088.jpg)
![Screenshot_2022-12-29-14-21-27-976_name monwf customiuizer](https://user-images.githubusercontent.com/107347313/209951424-ef7710ba-48fb-4725-b326-8573948a801d.jpg)
![Screenshot_2022-12-29-14-21-33-565_name monwf customiuizer](https://user-images.githubusercontent.com/107347313/209951444-96f59126-f60f-4639-971b-a2e3610e9c0a.jpg)
![Screenshot_2022-12-29-14-21-37-819_name monwf customiuizer](https://user-images.githubusercontent.com/107347313/209951455-5d516ed6-2830-4ce6-b524-6408bf72a77c.jpg)

**Comment by MonwF** [comment]
get apk from https://github.com/MonwF/customiuizer/releases/tag/v22.12.29
