### ISSUE TITLE
BUG. Turn on the screen when headphones are connected. MIUI 13

### ISSUE THREAD

**Issue by YurKa336** [MonwF/customiuizer#93]
On Redmi Note 10 pro, MIUI 13 Global 13.0.16, the "Do not turn on the screen when headphones are connected" function does not work

**Comment by MonwF** [comment]
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/10322946/app-release.apk.zip)

**Comment by YurKa336** [comment]
It works.  Thank you for your work
