### ISSUE TITLE
BUG. Blurring the volume dialog background 

### ISSUE THREAD

**Issue by YurKa336** [MonwF/customiuizer#97]
When set to "standard" for "collapsed dialog" and when set to non-standard for "expanded dialog", a background appears when the volume is changed
![Screenshot_2023-01-02-13-16-15-133_com miui home](https://user-images.githubusercontent.com/107347313/210224922-24131604-6b50-489c-b50e-f4b10063322f.jpg)
![Screenshot_2023-01-02-13-16-19-903_com miui home](https://user-images.githubusercontent.com/107347313/210224929-a2e0ea14-a826-487c-bd85-7529e862c9b5.jpg)
![Screenshot_2023-01-02-13-18-49-138_name monwf customiuizer](https://user-images.githubusercontent.com/107347313/210224932-7b4e33ab-1178-4f09-81ca-7028d9fbcee6.jpg)

**Comment by YurKa336** [comment]
I decided to send you my logs.  Perhaps they will help you in solving some bugs


[2023-01-02T13:15:13.470

1000: 1712: 1712 I/

LSPosed-Bridge ] [CustoMIUIzer] [MuffledVibrationHook]

Failed to hook systemReady method in com.android.server. VibratorService

[ 2023-01-02T13:15:13.471

1000: 1712: 1712 I/

LSPosed-Bridge ] [CustoMIUIzer] [MuffledVibrationHook] Failed to hook doVibratorOn method in com.android.server. VibratorService

[2023-01-02T13:15:25.579

1000: 3287: 3287 I/

LSPosed-Bridge ] [CustoMIUIzer] [NoMoreIconHook] Failed to hook setIconsVisibility method in com.android.systemui.statusb ar.phone. NotificationIconAreaController

[ 2023-01-02T13:15:25.655

1000: 3287: 3287 I/

LSPosed-Bridge ] [CustoMIUIzer] [AllowDirectReplyHook] Failed to hook setLockScreenAllowRemote Input method in com.android.systemui.statusbar.phone.StatusBar

3287 I/

[2023-01-02T13:15:25.669 1000: 3287: LSPosed-Bridge ] [CustoMIUIzer] [Volume DialogDNDSwitchHook]

Failed to hook updateState method in com.android.systemui.miui .volume.MiuiRinger ModeLayout. Ringer ButtonHelper

[ 2023-01-02T13:15:25.707

1000: 3287: 3287 I/

LSPosed-Bridge ] [CustoMIUIzer] [Minimal NotificationViewHook]

Failed to hook updateNotification method in com.android.systemui.statusbar.phone.StatusBar

![IMG_20230102_143705](https://user-images.githubusercontent.com/107347313/210232931-460dbdd4-0974-4504-bb97-f8015995f822.jpg)
![IMG_20230102_143631](https://user-images.githubusercontent.com/107347313/210232934-4017e714-d56d-40df-9eae-0911766b5d27.jpg)
![IMG_20230102_143539](https://user-images.githubusercontent.com/107347313/210232937-e278e89e-3917-441e-a555-18012d5088ef.jpg)

**Comment by MonwF** [comment]
rom version

**Comment by MonwF** [comment]
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/10331866/app-release.apk.zip)

try this build

**Comment by YurKa336** [comment]
This work. Thanks:)
