### ISSUE TITLE
[Request] List of apps in sidebar

### ISSUE THREAD

**Issue by 3zozHashim** [MonwF/customiuizer#98]
It would be incredible if an "add to sidebar" option would be added in custoMIUIzer13 like the one with applock

**Option:**
List of Apps in sidebar
(Enhanced version of Sidebar option that allows to sidebar any installed app)

**Explanation:**
Currently most/all apps are allowed to be floatable but not all apps can be added to sidebar. There is a way to bypass that by opening app then change it to float then it'll be addable to sidebar but the bypass doesnt work on all apps

**AppLock Option Referenced:**

![IMG_20230103_014116](https://user-images.githubusercontent.com/115328790/210285234-d2ffa667-c314-4fca-82eb-b2d6818d256b.jpg)

**Comment by MonwF** [comment]
[app-develop.zip](https://github.com/MonwF/customiuizer/files/10676882/app-develop.zip)
 
turn of "Various - Disable suggestion blacklist xxx"
