### ISSUE TITLE
[Request] statusbar network speed vertical offset

### ISSUE THREAD

**Issue by 3zozHashim** [MonwF/customiuizer#99]
When you decrease the size of Network Speed and Battery Temperature the numbers are center aligned.

It would be amazing if there was an option to make it bottom aligned.

Edit: battery temperature had an option to offset vertical.

**Reference:**
![IMG_20230103_015249](https://user-images.githubusercontent.com/115328790/210285661-0cf7e35b-04e5-4410-9645-d91c26b1068f.png)

**Comment by MonwF** [comment]
[app-release.apk.zip](https://github.com/MonwF/customiuizer/files/10335737/app-release.apk.zip)

get this apk
